### ISSUE TITLE
[Feature request] - More detailed documentation/info

### ISSUE THREAD

**Issue by Darth-Coin** [stackernews/stacker.news#1]
1. FAQ page. You need to give more information about how to use this and fees applied, votes etc
2. Using the free credits to post - OK. But after posting those, it doesn't say how much I need to pay for a new post.
3. It should be also available the option to just pay a LN invoice for a new paid post, if I do not have enough funds in wallet

**Comment by huumn** [comment]
Thanks for popping my Issues.

As for 1 and 2, every action (posting/commenting/upvoting) is 1 sat and I don't intend to ever change this on the main page. I agree though that this should be made clear. I have this planned as part of my work for the upcoming week which I usually post of twitter https://twitter.com/k00bideh/status/1410650020454572037

For 3, if it's just 1 sat to post, do you still want this mechanic? The fees might be higher than the action cost if you don't have a channel with my node.

**Comment by Darth-Coin** [comment]
Fair enough. Thanks for answering

**Comment by huumn** [comment]
Tooltip now shows dust cost of actions. Going to close. If this is insufficient please let me know

<img width="344" alt="Screen Shot 2021-07-08 at 1 52 12 PM" src="https://user-images.githubusercontent.com/34140557/124975787-055e1c00-dff4-11eb-839c-f05893b363e7.png">
<img width="299" alt="Screen Shot 2021-07-08 at 1 51 56 PM" src="https://user-images.githubusercontent.com/34140557/124975789-05f6b280-dff4-11eb-896b-8ed8962cf0d9.png">

**Comment by huumn** [comment]
I've also written a FAQ to make things clearer.

**Comment by jsarenik** [comment]
Thank you @huumn! Perfect wording: "These will never cost more than 1 sat." ! Yes!

**Comment by ekzyis** [comment]
lol, by accidentally linking this issue in #566, I realized that

> It should be also available the option to just pay a LN invoice for a new paid post, if I do not have enough funds in wallet

was apparently one of the first issues and we finally did that in #336
