### ISSUE TITLE
Mobile nav bar not fixed to bottom when page is short

### ISSUE THREAD

**Issue by SatsAllDay** [stackernews/stacker.news#1004]
**Description**
On stacker profile pages where there is no bio, when using a mobile browser, the fixed footer isn't fixed to the bottom of the screen. 

**Steps to Reproduce**
Open the profile page of a stacker without a bio set on a mobile device. 

**Expected behavior**
Nav bar should be fixed to bottom of viewport. 

**Screenshots**
![image](https://github.com/stackernews/stacker.news/assets/128755788/ceec3897-2789-4837-b568-e631f671cb00)

**Logs**
Couldn't capture, on iOS PWA

**Environment:**
If you only experience the issue on certain devices or browsers, provide that info.
 - Device: iPhone
 - OS: iOS
 - Browser: Safari PWA
 - Version: ¯\\\_(ツ)_/¯ 

**Additional context**

**Comment by benalleng** [comment]
Can't reproduce on chromium or firefox on android

**Comment by felipebueno** [comment]
Can't reproduce on Firefox Nightly and Brave on Android

**Comment by benalleng** [comment]
curious if there is a `flex-grow` issue on mobile safari or something?

**Comment by SatsAllDay** [comment]
Here's another example of this happening for me, this time on the wallet page
![image](https://github.com/stackernews/stacker.news/assets/128755788/23bd8a85-ddef-49cf-8675-0aaf4fdab174)

**Comment by benalleng** [comment]
that one is wack, I've never seen a `margin: auto` break like that... I am trying some fixes for #993 and hopefully I can fix these as well with my changes

**Comment by benalleng** [comment]
I have a prototype for the navbar fix for #993 here https://github.com/benalleng/stacker.news/tree/issue993, it still has some issues but I wanted to see if you could fork and test that it fixes these issues as well before i put more time into refactoring the css

**Comment by benalleng** [comment]
@SatsAllDay now that #1011 is in prod i just wanted to ping you to see if you were still able to reproduce these bugs?

**Comment by SatsAllDay** [comment]
I'll test again over the weekend and see if they're reproducible for me.

I did start to pull in your PR locally to test yesterday but wasn't able to keep up with the frequent changes, so I didn't get to really verify. Sorry about that!

**Comment by benalleng** [comment]
@SatsAllDay circling back to this one, can you still reproduce this bug?

**Comment by SatsAllDay** [comment]
> @SatsAllDay circling back to this one, can you still reproduce this bug?

I am no longer able to reproduce. I don't think it was 100% consistent before but I tried several times just now and it never happened.
