### ISSUE TITLE
User Profile pages don't show common page footer

### ISSUE THREAD

**Issue by SatsAllDay** [stackernews/stacker.news#1016]
**Description**
I noticed that the common page footer is not present on user profile pages. Is that intentional?

**Steps to Reproduce**
1. Nav to any user profile page e.g. https://stacker.news/WeAreAllSatoshi
2. Observe that the page footer is not present

**Expected behavior**
Expect page footer on profile pages

**Screenshots**
<img width="1263" alt="image" src="https://github.com/stackernews/stacker.news/assets/128755788/2407ce96-1d23-4498-93ef-68762dfb52bd">

**Logs**
N/A

**Environment:**
N/A

**Additional context**
N/A

**Comment by huumn** [comment]
I removed it on a bunch of pages. There's no rhyme or reason though. I just didn't like the way it looked when there wasn't a bio.

**Comment by SouthKoreaLN** [comment]
This is what it looks like if I re-add the `Footer` here:
```
export function UserLayout ({ user, children, containClassName }) {
  return (
    <Layout user={user} footer={false} containClassName={containClassName}>
      <UserHeader user={user} />
      {children}
    <Footer /> 
    </Layout>
  )
}
```
<img width="1407" alt="Screenshot 2024-04-05 at 12 00 28 AM" src="https://github.com/stackernews/stacker.news/assets/11783268/63e39622-c3f7-4b1b-a971-d90cfb736216">

Maybe a bit heavy indeed. Without Footer on the user page it looks ok to me too.
Maybe I can try adding a conditional to check if a Bio is present or not... after I learn how to do that.

**Comment by benalleng** [comment]
There is also the static page footer, which is a little lighter
![image](https://github.com/stackernews/stacker.news/assets/108441023/75d3b4f7-e6ca-4ae7-9245-a5b3c1c25f7a)

**Comment by huumn** [comment]
Lighter footer is on purpose

**Comment by benalleng** [comment]
Ok! I just meant we could use that if we felt the regular footer was too busy
