### ISSUE TITLE
Territories Dropdown Empty When Posting

### ISSUE THREAD

**Issue by kepford** [stackernews/stacker.news#1025]
**Description**

When I try to make a post at https://stacker.news/post I see that the territories drop down does not have any values.

**Steps to Reproduce**

Visit https://stacker.news/post while logged in and click the territories dropdown

**Expected behavior**

Territories to be listed

**Screenshots**

![image](https://github.com/stackernews/stacker.news/assets/164552/b88e0119-054c-4516-9a6e-258417ed0209)

**Environment:**

FF 124.0.1, Linux

**Comment by ekzyis** [comment]
Fixed in https://github.com/stackernews/stacker.news/commit/657ce1a4f8fa9f9485137a75efcb954159962aac

See https://github.com/stackernews/stacker.news/issues/1026#issuecomment-2040147448
