### ISSUE TITLE
Territory dropdown broken?

### ISSUE THREAD

**Issue by benalleng** [stackernews/stacker.news#1026]
**Description**
Only the home and create territory are listed

**Steps to Reproduce**
Click the territories dropdown

**Expected behavior**
All the territories should be listed

**Screenshots**
![image](https://github.com/stackernews/stacker.news/assets/108441023/959b1a70-bd2b-4e5c-b06f-2735b4eec0c7)

**Additional Context**
I'm not sure if this is just a bug on my machine as everyone else seems to be posting up a storm

**Comment by ekzyis** [comment]
Yes, can confirm that it's broken. I can reproduce locally with https://github.com/stackernews/stacker.news/commit/1d4ba7 (we just released that commit) but it's working with 2c9e6681.  We're investigating.

**Comment by huumn** [comment]
Fixed here: 657ce1a4f8fa9f9485137a75efcb954159962aac

Caused by 5a1f39d076c9e4a2791c93573fca01d0899c0f2c
