### ISSUE TITLE
local dev optional env var to lengthen polling interval for cleaner network debugging

### ISSUE THREAD

**Issue by SatsAllDay** [stackernews/stacker.news#1033]
**Is your feature request related to a problem? Please describe.**
While developing locally, I often get frustrated trying to look at network requests in the browser dev tools because there are _so many_, given our frequent polling interval for `notifications`, `me`, etc. Usually I'm looking for a certain request, but since all URLs are `/api/graphql`, you can't easily filter the network requests.

**Describe the solution you'd like**
Supporting an optional env var(s) like `NOTES_POLLING_INTERVAL`, `ME_POLLING_INTERVAL` that are only honored in local dev would be an easy way to improve this developer experience without risking accidentally changing how this polling works in prod.

**Describe alternatives you've considered**
In the past, I've often modified the polling interval in code, and just carried around an unstaged change to solve this problem. That isn't the cleanest approach, and is also prone to accidentally checking in an unwanted change.

**Additional context**
N/A

I am posing this question/enhancement suggestion to see if it would be useful to others. If we think it's not useful, I'll squash the idea. Open to feedback :)

**Comment by ekzyis** [comment]
> I often get frustrated trying to look at network requests in the browser dev tools because there are so many

Same here!

> In the past, I've often modified the polling interval in code, and just carried around an unstaged change to solve this problem.

I started to live with simply stopping recording network requests except when I want to and then immediately stop to make the search space smaller, lol.

But having the poll interval in an env variable as you suggest would decrease the amount of magic numbers we use and allow different configs for local dev.

I support this ticket.

**Comment by SatsAllDay** [comment]
> I think the better solution would be to make it mandatory but set a default in .env.sample. Would be more straightforward than different code running in prod vs dev

I agree, I like this better for minimizing diff between dev and prod. Good idea.

> I support this ticket.

Hooray!

**Comment by ekzyis** [comment]
It's one of those tickets where I got so used to my workflow that I don't think about improvements anymore :)

**Comment by SatsAllDay** [comment]
Here's a list of all the polling intervals I've found in the UI:
* block height: 30000
* fee button: 1000
* footer rewards: 60000
* invoice: 1000
* lightning auth: 1000
* me: 1000
* price: 30000
* sub select: 300000
* has new notes: 30000
* full invoice: 1000
* rewards page: 1000
* ln qr withdrawal from wallet page: 1000
* ln withdrawal from withdrawal page: 1000

Only some of these are targets of my original intent for this ticket, like me and has new notes. But, for consistency, we could move all of them to env vars.

Also, I think it might be nice to consolidate them in the existing constants file, as well. So really, this would entail:

1. Define a constant for each of these polling intervals in `lib/constants.js`
2. Source the value for each of these constants from the corresponding env var

Thoughts?

**Comment by ekzyis** [comment]
Maybe we can have `QUICK_POLL`, `NORMAL_POLL` and `LONG_POLL`. I see a lot of duplicate values. It's also closer to intent: we care about how fast we poll, not about what we poll

**Comment by SatsAllDay** [comment]
What is the process to introduce new env variables such that they are made available in production. Does it use `.env.sample` as a baseline? For some reason I was thinking it was only used on local dev, but I don't see anything else in the repo related to exposing env vars for production.

**Comment by ekzyis** [comment]
I think @huumn manages the environment in prod via [AWS Copilot](https://aws.amazon.com/blogs/containers/introducing-aws-copilot/). So every new env var has to be set once.

I think this means it makes sense to add another check in the PR template checklist for this:

- [ ] new environment variables added?

**Comment by SatsAllDay** [comment]
I can do that in my PR for this issue if you like.

**Comment by huumn** [comment]
Can confirm, I add new env vars manually. Sometimes in copilot. Sometimes in elasticbeanstalk.
