### ISSUE TITLE
Strike through real fee for freebie actions

### ISSUE THREAD

**Issue by ekzyis** [stackernews/stacker.news#1039]
**Is your feature request related to a problem? Please describe.**

While reviewing #1031, I found our current UX when we show `free` to be confusing. It hides the real fee and mixes two cases together: when the action is really free or it's just free because it's an action for which you don't have enough sats and freebie is allowed ("freebie action").[^1]

**Describe the solution you'd like**

I think we should only show `free` when it's really free. When it's 1 sat and you can pay, we show nothing as currently (the overlay shows 1 sat).

For freebie actions (`total >= 1` + freebie is allowed + you can't pay), we show the fee but striked through:

![2024-04-07-203532_135x59_scrot](https://github.com/stackernews/stacker.news/assets/27162016/a4e59bc3-9625-4a74-8dad-b36ddbb3045d)

I think this would make it more clear when something is free for freebie reasons while also not hiding the real fee. I think it's nice to know how much it would actually cost.

**Describe alternatives you've considered**

doing nothing

**Additional context**

n/a

[^1]: One can tell from the help icon for the freebie dialog if it's really free or just freebie since it only shows up for freebie actions, but I think it's still confusing.

**Comment by huumn** [comment]
> I think this would make it more clear when something is free for freebie reasons while also not hiding the real fee. I think it's nice to know how much it would actually cost.

Is that true for a new user that’s never posted before?

**Comment by ekzyis** [comment]
> Is that true for a new user that’s never posted before?

Mhhh, they probably don't immediately care. At least I only started to care after I had been using external wallets for a while and noticed I don't see the real fee anymore, only "free" all the time. Then in #1031 I additionally noticed how free can have two meanings now.[^1]

My idea with the striked through text was to make the UX more consistent since we do show the fee inside the button text if you're able to pay.

However, I can see how it's probably too much immediate information for newbies and showing a fee when you will pay it is obviously more important than showing a fee you won't pay. An alternative for curious minds could be to show how much it would cost in the freebie info dialog. 

However, feel free to close this ticket. Just wanted to have a discussion about this and I have to rework how freebies work with attached wallets and this then might become obsolete anyway.

[^1]: Maybe we shouldn't show "free" for edits as my suggested fix in #1031 would do since afaik, it's the only truly free action and we can assume stackers realize it's free even though the button looks the same as for actions that cost 1 sat? The overlay would clarify though.

**Comment by huumn** [comment]
I'm happy to discuss it. My main UX fear is us developing myopia around a power users perspective because it's the easiest thing for us to imagine as power users. My mental checklist usually is:

- [ ] is this more confusing for new stackers
- [ ] is this more confusing for old stackers
- [ ] is this good for new stackers
- [ ] is this good for old stackers

One of the bottom two should be checked (ideally both) and the top two shouldn't.

Another example of this is having a link to attached wallet logs on the main wallet page. For the majority of people that don't have attached wallets, it opens up an empty log.
