### ISSUE TITLE
Referrals graph reporting referral before my account existed

### ISSUE THREAD

**Issue by SatsAllDay** [stackernews/stacker.news#1044]
**Description**
The referrals page indicates that I have a referral from year 2021, before my account even existed (created in 2023).

**Steps to Reproduce**
1. Navigate to https://stacker.news/referrals/forever
2. Observer referrals

**Expected behavior**
Only expect to see actual referrals?

**Screenshots**
<img width="742" alt="image" src="https://github.com/stackernews/stacker.news/assets/128755788/11cf6023-ac41-4fcb-bf1e-c74113b5f2ea">

**Logs**
N/A

**Environment:**
N/A

**Additional context**
I verified this data is included in the API response, so I don't think it's a UI bug.

**Comment by huumn** [comment]
This is a side effect of ffa86ab which allows (knowingly) referrals to get attributed on login/auth linking. 

We plan to change referrals to be even more dynamic than this. Meaning, your active referrer will be the the last referral link you clicked regardless of whether you had a previous referrer or not. 

This was a weird eureka we had over the weekend observing the effect of ffa86ab. It'll incentivize both external *and internal link sharing (ie evergreeness).

**Comment by SatsAllDay** [comment]
Ah, so basically someone who joined back in 10/21 (according to my graph screenshot) followed a referral link of mine at some point? Anyway, thanks for providing the context!

**Comment by huumn** [comment]
> Ah, so basically someone who joined back in 10/21 (according to my graph screenshot) followed a referral link of mine at some point?

Exactly!

**Comment by SatsAllDay** [comment]
Just to follow up here, I think what brought my attention to the referrals chart today is that I've received 3 push notifications indicating that someone joined SN using one of my referral links, which is a rarity for me. Am I seeing these push notifications more often due to the aforementioned commit? If so, we might want another ticket tracking updating the wording on the push notification, since it doesn't really mean a new user joined, but rather I became a user's most recent referrer (wording is hard 😅 )

Also, while I did receive push notifications, I did not see anything at `/notifications`, which seems incorrect, as well? I can open a separate issue for that, if you'd like.

**Comment by ekzyis** [comment]
> If so, we might want another ticket tracking updating the wording on the push notification, since it doesn't really mean a new user joined, but rather I became a user's most recent referrer (wording is hard 😅 )

Makes sense to me

> Also, while I did receive push notifications, I did not see anything at /notifications, which seems incorrect, as well? I can open a separate issue for that, if you'd like.

Sounds like a bug to me, too

**Comment by ekzyis** [comment]
> Sounds like a bug to me, too

Bug happens because we assume that the referral was created at the time the user was created. So you don't see a notification in /notifications because it's considered to be a very old notification:

https://github.com/stackernews/stacker.news/blob/c7d926df30a8942b8dacc4cf392217b0ed18c3a1/api/resolvers/notifications.js#L238-L259

One way to fix this would be to store a separate timestamp for referrals.

**Comment by SatsAllDay** [comment]
I opened #1046 and #1047 to track each of the subsequently identified issues from this thread.
