### ISSUE TITLE
Hidden prepopulated section entry potentially missed for deletion if user does not unroll the hidden section

### ISSUE THREAD

**Issue by SouthKoreaLN** [stackernews/stacker.news#1045]
**Description**
Check [this post](https://stacker.news/items/499422) for instance. I had started posting something a while ago (the 3blue1brown video), but then decided against it. Today, I decided to post something else (in this case, the link to Calle's Ecash post). I noticed the title and link were still populated by the title and link I had inputted for the 3blue1brown video. I deleted them and replaced them with the link for the Ecash video link and title. I did not click the options dropdown menu, so didn't see that the context was still prepulated. Resulting in this mismatch between current link/title and context.

**Steps to Reproduce**
1. Start a link post. Fill in title, link and context.
2. Do not click post. Navigate back to the main page.
3. Start a new post link. Notice the title and link being prepopulated. Delete these entries and replace them with new entries.
4. Optionally notice that if you click on options, the context entry is still prepopulated. If you do not notice this because it is collapsed, you'll post without noticing.

**Expected behavior**
Two potential solutions:
- Delete prepopulated context if user deletes prepopulated title and link entres
- If anything is prepopulated, automatically unroll the options section so that the user notices the hidden prepopulated entries.

**Additional context**
I remember another recent post by another user who encountered this same issue. I'll update here if I find it.

**Comment by benalleng** [comment]
I generally think that the `cancel` button should clear all inputs in this case. If I want to save for later I could just click back or close the tab

**Comment by SouthKoreaLN** [comment]
> I generally think that the `cancel` button should clear all inputs in this case. If I want to save for later I could just click back or close the tab

Indeed. But in the case I describe here, I did not click cancel. I just navigated way/closed the tab/clicked back. It is thus saved for later, but if I don't end up posting what I saved, I might forget that the hidden "options" section may contain saved data...

**Comment by ekzyis** [comment]
Yes, I think we should simply uncollapse. No automated deletion since it might be confusing and unexpected since imo, problem is restricted to it being easy to not see, not the deletion of old inputs.

**Comment by computerdev21** [comment]
Can I also try resolving this or is there a sequence as to who gets to solve something first?

**Comment by SouthKoreaLN** [comment]
Go ahead, got distracted with work stuff.

**Comment by benalleng** [comment]
I think I inadvertently found a solution for this one when working on my [branch](https://github.com/benalleng/stacker.news/tree/issue491) for #491 but i feel like its pretty messy still. I'm going to make a draft PR soon for some help cleaning this one up to ship as I think this has pretty decent priority as I see posts like this often enough
