### ISSUE TITLE
New referral user push notification text is misleading

### ISSUE THREAD

**Issue by SatsAllDay** [stackernews/stacker.news#1046]
**Description**
Forked from [this comment](https://github.com/stackernews/stacker.news/issues/1044#issuecomment-2043988299) on #1044 

The push notification sent for new referrals suggests that a new user signed up, but with the recent changes to how referrals work, that's not necessarily true any more. It can also occur just when an existing user follows one of your referral links (is that all that triggers it? or do they have to be zapped, too?)

**Steps to Reproduce**
1. As user 1, follow a referral link from user 2

**Expected behavior**
The push notification wording should be updated to reflect the change in referral behavior.

**Screenshots**
I didn't capture any screenshots when this happened in prod, unfortunately.

**Logs**
N/A

**Environment:**
N/A

**Additional context**
N/A

**Comment by benalleng** [comment]
Without changing the logic of how these referral notifications work what do you think a good way to change the copy would be?

**Comment by SatsAllDay** [comment]
I don't fully understand what triggers the push notification. Is it when:
1. an existing user follows one of your referral links?
2. or a new user signs up having followed one of your referral links?

If so, I'd suggest something like "someone followed one of your referral links"

If we can differentiate between existing users + new user signups, the text could vary accordingly.

**Comment by huumn** [comment]
Oh no worries fren!

**Comment by huumn** [comment]
closing in favor of https://github.com/stackernews/stacker.news/issues/1047 removing these
