### ISSUE TITLE
Create a related section on posts

### ISSUE THREAD

**Issue by huumn** [stackernews/stacker.news#105]
This is fairly trivial to implement in elastic search: it's called a "more like this" query.

This allows users to find additional context/discussion without anyone having to provide it in the comments.

**Comment by cointastical** [comment]
There's a related feature request from this SN post [[Feature Request: implement the “Déjà vu” feature natively](https://stacker.news/items/66567)](https://stacker.news/items/66567)

**Comment by cointastical** [comment]
Has this issue been resolved (and thus this issue closed), with the "Related" drop down that was added in October?

*SN release: related posts*
https://stacker.news/items/86375

**Comment by huumn** [comment]
Yep closing!
