### ISSUE TITLE
Navigation in /rewards sticky header not clickable

### ISSUE THREAD

**Issue by ekzyis** [stackernews/stacker.news#1060]
**Description**

For some reason, the navigation of the sticky header in /rewards is not clickable.

**Steps to Reproduce**

1. Go to /rewards
2. Scroll down until sticky header appears
3. Try to click back, logo or search

**Expected behavior**

Everything clickable as usual

**Video**

https://github.com/stackernews/stacker.news/assets/27162016/76609b15-481d-4d06-98d5-bb2e1e2a9462

**Environment:**
If you only experience the issue on certain devices or browsers, provide that info.
 - Device: Desktop
 - OS: Linux
 - Browser: Brave
 - Version: [Version 1.62.165 Chromium: 121.0.6167.184 (Official Build) (64-bit)](https://brave.com/latest/)

**Additional context**

Bug does not exist in mobile sticky header.

**Comment by huumn** [comment]
It's only when you scroll down. I think it's because the pie chart column has a higher z-index.
