### ISSUE TITLE
Ability to search through bookmarked posts

### ISSUE THREAD

**Issue by aChrisYouKnow** [stackernews/stacker.news#1064]
Either having a search bar on the bookmarks screen (https://stacker.news/[USER]/bookmarks), or a search filter that only searches posts I have bookmarked (listed on this page with the other filter hints: https://stacker.news/search) would be a really nice feature. 

Useful for when you are trying to find something you know you bookmarked a while back.

**Comment by huumn** [comment]
Great request! I've wanted this myself. 

Implementation hint: It'll require storing bookmarks in open search.

**Comment by SatsAllDay** [comment]
This one is interesting to me. Cool if I self-assign even if it takes a while to get through it? I don't see a priority, so I think that should mean it's ok, but I don't want to hog it if someone else has more time/capacity than I do.

**Comment by huumn** [comment]
Yep self-assign away!

**Comment by aChrisYouKnow** [comment]
> Implementation hint: It'll require storing bookmarks in open search.

Sounds like quite a reasonable concession

Glad to hear there is other interest out there!

**Comment by huumn** [comment]
Hint hint: bookmarks can either be stored as:

1. a field in items in the existing item index, e.g. `item.bookmarkedBy = [userid1, userid2]`
2. as a new index all together

Given the mappings on the item index would need to be reproduced in (2), I'd recommend (1), but (2) will work too.

**Comment by huumn** [comment]
@aChrisYouKnow do you have a lightning address I can send the sats for this to?

**Comment by aChrisYouKnow** [comment]
@huumn ACYK@stacker.news works. Thanks! I somehow lost access to the aChrisYouKnow SN username. I get "email is no good" when I try to log into that one so I started over with ACYN.
