### ISSUE TITLE
Rewards page has faulty resonsive flex column vs flex row design

### ISSUE THREAD

**Issue by benalleng** [stackernews/stacker.news#1067]
*Note: this template is meant to help you report the bug so that we can fix it faster, ie not all of these sections are required*

**Description**
Pointed out in #1006

> while using the inspect tools in Chrome, I noticed that the leaderboard goes below the pie chart when the screen is not wide enough but it doesn't come back to the right-hand side when the screen is wide again. If I reload the page, the leaderboard comes back to the right hand side.

The page layout is responsive as you size down the page as it goes from a row to a column but as the page size grows this column of elements is not restored to a row is it is on an initial page load

**Steps to Reproduce**
- go to `/rewards` with a page size lg ~990px and then shrink the page until the elements form a column and the size the page back up to a lg screen and the elements are not properly re-arranged

**Expected behavior**
All the elements should return to their proper position on all responsize screen size changes

**Screenshots**

https://private-user-images.githubusercontent.com/6998593/319674086-98802065-e5fa-4ede-b2eb-897102dfc8f1.mov?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMxMjExMTgsIm5iZiI6MTcxMzEyMDgxOCwicGF0aCI6Ii82OTk4NTkzLzMxOTY3NDA4Ni05ODgwMjA2NS1lNWZhLTRlZGUtYjJlYi04OTcxMDJkZmM4ZjEubW92P1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQxNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MTRUMTg1MzM4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9M2ZhZjU2NDNhNjhmMDk0N2JmMDUzZThkY2U2MTFiNTRjYjRmNDczMjVmYjBhNGMzNDBjZTIyNjgyNGYxNTY2OSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.GcoVme-Fv8CDdQLw__i7ZLIrEWOrps3Q6miI3ljmscU

**Environment:**
If you only experience the issue on certain devices or browsers, provide that info.
 - Chrome and Firefox

**Additional context**
Credit to @abhiShandy for finding and documenting the bug

**Comment by huumn** [comment]
I've noticed this but I thought it might be a `sticky` `flex` bug in those browsers.
