### ISSUE TITLE
Image alt attributes leak data

### ISSUE THREAD

**Issue by ekzyis** [stackernews/stacker.news#1096]
**Is your feature request related to a problem? Please describe.**

When users upload an image, we use the provided filename in the markdown image syntax for the image alt attribute. We use it as a marker so we know which text we can replace when upload is finished:

https://github.com/stackernews/stacker.news/blob/d7ecbbae3a86ac62d3ad30f5affa8d240c722ce0/components/form.js#L316-L343

However, this can leak information like when the image was taken as in this example:

`![2024-04-20-124417_247x23_scrot.png](https://m.stacker.news/27429)`

**Describe the solution you'd like**

Overwrite filename with random string or simply delete string for the image alt attribute. 

**Describe alternatives you've considered**

n/a

**Additional context**

When to overwrite filenames or delete them is not clear. If we do this on upload, then the user might be confused which image was uploaded since the filename no longer matches what they uploaded. The code also needs unique identifiers so simply deleting it on upload would break the `onSuccess` callback. We could do this after `onSuccess` though.

We could do this on submit on the client or server but then we need to parse for image alt attributes and then it's not clear which was provided by the user and which should be replaced. We could limit this replacement to images from `m.stacker.news` though.

[_sats for this ticket go to @Darth-Coin even though he probably does not want them_](https://stacker.news/items/512387)

**Comment by Darth-Coin** [comment]
>[sats for this ticket go to @Darth-Coin even though he probably does not want them](https://stacker.news/items/512387)

hahaha nah man, I was about to post this issue on GH, that's why I asked first on SN if is possible.
Who doesn't want sats? Only that I would give them to the one that is fixing this, instead of going to me, that I just reported.

So, do you think is fixable?

**Comment by ekzyis** [comment]
> Only that I would give them to the one that is fixing this, instead of going to me, that I just reported.

we give sats to [tickets](https://github.com/stackernews/stacker.news?tab=readme-ov-file#issue-specification-awards) + [pull requests](https://github.com/stackernews/stacker.news?tab=readme-ov-file#pull-request-awards)

> So, do you think is fixable?

yes, definitely, just need to figure out best UX. I think simply replacing the filename when upload was finished is probably the simplest and least confusing (but still confusing).
