### ISSUE TITLE
Use global view for top ranking

### ISSUE THREAD

**Issue by ekzyis** [stackernews/stacker.news#1097]
**Is your feature request related to a problem? Please describe.**

Top is currently personalized. This is confusing.

**Describe the solution you'd like**

Make top use global consensus view.

**Describe alternatives you've considered**

n/a

**Additional context**

https://stacker.news/items/512507

> It’s about the easiest entry point to understanding how we use the algorithms results. Most of the required changes will be in ‘api/resolvers/item’ where ‘me’ is set and ‘sort=top’. It shouldn’t require more than a handful of lines

**Comment by kravhen** [comment]
Should be closed by #1202 I think
