### ISSUE TITLE
Possible comment bug reported by user

### ISSUE THREAD

**Issue by huumn** [stackernews/stacker.news#110]
Reported in Stackerz Chat

https://t.me/stackernews/378

> right, I think this is something to do with replying to your own comment while its timing out. Steps to reproduce:
> 1) make a comment, submit it. Your comment will appear at the top of the list
> 2) before the edit-window times out, refresh the page with your browser, your comment appears at the bottom
> 3) Reply to your own comment at the bottom of the list before the edit-window times out...  Now you have two edit-windows counting down.
> 4) Wait for both edit-windows to time-out and refresh the page. Your reply will be in response to the previously-last comment in the list rather than to your own

**Comment by lazaruslarue** [comment]
Looks like this could be getting confused because `replyOpen` is being shared among the various reply components.

Maybe [here](https://github.com/stackernews/stacker.news/blob/master/components/comment.js#L177)?

**Comment by huumn** [comment]
Possibly related issue reported by darthcoin https://stacker.news/items/29464

**Comment by huumn** [comment]
I couldn't recreate this when I tried today and no one has reported anything like it for a over a year. Going to close. I think this was mostly a misunderstanding/user error.
