### ISSUE TITLE
Mining Fees in Header Stuck at 116 sat/vB

### ISSUE THREAD

**Issue by SatsAllDay** [stackernews/stacker.news#1124]
**Description**
The approximate mining fees in the header carousel appears to be stuck at 116 sat/vB

**Steps to Reproduce**
1. View page header
2. Click on carousel until you land on approximate fees

**Expected behavior**
The mining fees used to follow reality pretty well. But for some reason, it's stuck now.

**Screenshots**
<img width="1014" alt="image" src="https://github.com/stackernews/stacker.news/assets/128755788/0bf829d9-a9b0-4b45-9779-6f7643a13e63">

**Logs**
N/A

**Environment:**
N/A

**Additional context**
Discussed [here](https://stacker.news/items/522551/r/WeAreAllSatoshi?commentId=522975) and [here](https://stacker.news/items/521675/r/WeAreAllSatoshi?commentId=522401)

@ekzyis suggested maybe switching to use mempool.space's API instead of whatever we're doing (querying our LND node, I believe?)

It remains to be determined if the issue is with LND, or something in our app layer itself.

**Comment by SatsAllDay** [comment]
OK well now that I filed a bug, it shows as 43 sat/vB now... Probably still warrants an investigation to see what went wrong, if it may become a persistent issue, etc.

**Comment by ekzyis** [comment]
I think our node is just bad at estimating fees. mempool.space seems to be running a custom mempool config since they can show mempools larger than 300MB which is the default.

**Comment by huumn** [comment]
We are currently getting these fees from lnd. I wonder if there's something we can config to make the estimate tighter.

**Comment by tsmith123** [comment]
I might take this on if no one else is?

**Comment by huumn** [comment]
Go for it! Using something like mempool.space would be okay by me

**Comment by tsmith123** [comment]
PR submitted. Apologies if I've not followed any particular etiquette. I've just forked the repo and created the PR back into your master branch. Hope that's the right approach. I have requested to join dev chat.
