### ISSUE TITLE
Notifications with post titles without word breaks overflow horizontally

### ISSUE THREAD

**Issue by SatsAllDay** [stackernews/stacker.news#1125]
**Description**
On mobile, when viewing the notifications page, if a notification references a post that has a very long single word in it, the word is not broken via css, and therefore the notification overflows in the x-direction.

**Steps to Reproduce**
1. Somehow get notified of a post that has a very long word in the title
2. View notifications page

**Expected behavior**
Post titles and links in notifications should probably have some CSS word break behavior so that long words in titles don't cause overflow

**Screenshots**
![IMG_9970](https://github.com/stackernews/stacker.news/assets/128755788/4bcce117-c3a6-492e-b538-8bcc9baebcfb)
![IMG_9969](https://github.com/stackernews/stacker.news/assets/128755788/7ea6a204-dd78-4920-b55e-d8c0c45f6424)
![IMG_9968](https://github.com/stackernews/stacker.news/assets/128755788/2abdeeb3-89ff-4cf4-8ce9-36e1ab8c70ac)
![IMG_9967](https://github.com/stackernews/stacker.news/assets/128755788/55b43317-b849-4396-ae5d-67e056f3c1c8)

**Logs**
N/A

**Environment:**
Likely only an issue on mobile, not desktop

**Additional context**
N/A

**Comment by benalleng** [comment]
I am not able to reproduce this bug at the moment. tested with comment and zap notifications

The only thing I need to do more testing with is once the notification is hidden beyond the "more" notifications button perhaps there is some width that it overflows where it doesn't if contained in an initial render.

**Comment by benalleng** [comment]
Do you remember how you created these seemingly unbreakable strings? lol I found it on prod under your items and it seems to be the only one that does this.

**Comment by benalleng** [comment]
Ok, so a little deeper It seems to only be a problem on chrome, firefox seems to break this link title normally

**Comment by SatsAllDay** [comment]
It happens for me on iOS PWA too, meaning safari as well

**Comment by benalleng** [comment]
Ok, I Guess first handles word-breaks for links where the others do not
