### ISSUE TITLE
With Server Error page, include in the Footer the links for FAQ and the others 

### ISSUE THREAD

**Issue by sgornick** [stackernews/stacker.news#113]
When the Server Error 500 page is presented, there's nothing that helps the visitor seeing that to know how to report an issue (to report an outage, or to provide details as to how this 500 is occurring).

At a minimum, the footer should look as normal -- with links for "faq \ story \ analytics \ chat \ rss", which would let me do a Chat, for support.  

Additionally, the FAQ could probably include an entry for "How do check server status?" or something like that, like some other sites will have.  And then if the status page shows "No issues", but I'm experiencing an outage, that status page should have something that tells me how to report an outage.

**Comment by sgornick** [comment]
This issue was discovered after an authentication issue, and that has been reported as Issue #114.

**Comment by huumn** [comment]
Fixed locally.
