### ISSUE TITLE
Unable to view Wallet Statistics page

### ISSUE THREAD

**Issue by itsrealfake** [stackernews/stacker.news#1132]
*Note: this template is meant to help you report the bug so that we can fix it faster, ie not all of these sections are required*

**Description**

Previously, i could view wallet statitstics. Now, i can not.

**Steps to Reproduce**

Login on Firefox or Safari
Go to `https://stacker.news/wallet`
Click 'wallet history'

**Expected behavior**

I would expect to see the history of wallet changes (specifically, i was looking for my `sndev` chat login credentials

**Screenshots**

`stacker.news/wallet` page, with the hover-text for the 'wallet history' link displayed in lower left:
<img width="588" alt="image" src="https://github.com/stackernews/stacker.news/assets/107151866/bc997cc7-7a90-47a0-9902-ff07036ce1b5">

empty `statistics` page
<img width="603" alt="image" src="https://github.com/stackernews/stacker.news/assets/107151866/d02443f6-47ac-48c2-b09c-c0843de15e6c">

**Logs**
If applicable, add your browsers console logs.

**Environment:**
 - Device: desktop
 - Browser Firefox & Safari

**Additional context**

I was able to view details in the wallet history ~20 hours ago in order to get logged into the chat. i've restarted my computer, and now i'm unable to log in to the chat (didn't save the URL or the password, go figure)

**Comment by huumn** [comment]
Good catch. I'll submit a fix now

**Comment by itsrealfake** [comment]
i think it's here: https://github.com/stackernews/stacker.news/commit/8a735791ce54e6ba0ec72a98c699092a3909a949#diff-f3a6fdd385a77e0711da0571fc7c9e850e23d39014a9c77196f35ced75936fe1R210
