### ISSUE TITLE
Deleted items are zapable in certain timing window

### ISSUE THREAD

**Issue by SatsAllDay** [stackernews/stacker.news#1139]
**Description**
There was a report of a deleted comment being zapped [here](https://stacker.news/items/526635/r/WeAreAllSatoshi?commentId=526806).

The theory is that you can still zap a post/comment if it's live on your page, even if it's been deleted since you loaded your page. basically, a rare timing condition. This would be remedied by checking whether an item's been deleted server-side before allowing the zap to succeed, despite what it shows on the zapping users' client.

**Steps to Reproduce**
1. User 1 make a post
2. User 2 open the post
3. User 1 delete the post
4. Without refreshing the page, User 2 zap the post.

**Expected behavior**
Zap should fail in this case since the item's been deleted

**Screenshots**
I don't have any.

**Logs**
Didn't capture.

**Environment:**
N/A

**Additional context**
N/A

**Comment by abhiShandy** [comment]
I think this bugs extends to all interactions with deleted posts.

## Steps to reproduce
1. User 1 make a post
2. User 2 open the post
3. User 1 delete the post
4. Without refreshing the page, User 2 adds a comment.
