### ISSUE TITLE
Unable to see login button on Mobile - CSS issue (presumably)

### ISSUE THREAD

**Issue by cointastical** [stackernews/stacker.news#1163]
When I attempt to log in via mobile, I press the "SN" button to get the div for the "login" and "sign up" buttons, but all I see is a yellow progress bar across the top and then nothing more.  If I scroll down I see "sign up" button, but never the "login" button.

**Comment by cointastical** [comment]
Taking another look at this, I now see there is an icon for login.  But I've previously used that SN button before to cause the login to appear.  That appears to have changed ... I think.  Or maybe I am misremembering how login UX on mobile works.  Either way, if sign In button appears, so should login, no?

**Comment by huumn** [comment]
I don't fully understand the issue. Could you grab a screenshot?

**Comment by ekzyis** [comment]
> But I've previously used that SN button before to cause the login to appear. That appears to have changed ... I think

We've switched the bottom nav bar. The SN button is now on the left where the way to login was before (iirc).

You need to click the right icon to login now:

![stacker news_(iPhone SE)](https://github.com/stackernews/stacker.news/assets/27162016/ce25a39c-f29e-4cc8-b0fd-84cdc11e5560)
![stacker news_(iPhone SE) (1)](https://github.com/stackernews/stacker.news/assets/27162016/5e6d9ad0-416c-4caa-b55c-ec01f001192f)

> If I scroll down I see "sign up" button, but never the "login" button.

Good point, you're right, we only show "sign up" in the top nav bar. This doesn't feel consistent with the rest of the UI.

![stacker news_(iPhone SE) (2)](https://github.com/stackernews/stacker.news/assets/27162016/657202fa-5990-4bd1-b149-a5002cb3dd26)

Does that answer your questions?

**Comment by cointastical** [comment]
> we only show "sign up" in the top nav bar.
>
> Does that answer your questions?

Yes.

I don't think I had ever noticed that scrolling up would reveal top nav bar.  So then when that was the only login method I saw I found it lacking, thinking it had changed to now have only the "sign up" button.

> The SN button is now on the left 

Ah, ... I trusted muscle memory more than I trusted what my own eyes were seeing.

Closing this ticket.
