### ISSUE TITLE
No red square pop-up when a new post appears in a territory I've subscribed to

### ISSUE THREAD

**Issue by OneOneSeven117** [stackernews/stacker.news#1164]
**Description**
Not getting the red square on the notification bell upon a new post in a subscribed territory.

**Steps to Reproduce**
Sub to territory, wait for post in said territory.

**Expected behavior**
Red square upon new post, like when a subscribed stacker posts something.

**Screenshots**
Today I subbed to a couple extra territories to be sure of the bug, no red square when these were posted.
![image](https://github.com/stackernews/stacker.news/assets/40964558/2096df69-f261-4e3c-9242-a9e0ce4a49f2)

---
The screenshot below did have a red square, because of the subscribed stacker
---
![image](https://github.com/stackernews/stacker.news/assets/40964558/9c54bf62-9759-4e30-9ced-b98c47389f77)

**Environment:**
Browser (Brave and Chrome) and PWA

**Additional context**
Has been doing this to me for a while actually:

https://stacker.news/items/441695/r/OneOneSeven?commentId=442970
https://stacker.news/items/430488/r/OneOneSeven?commentId=430959

**Comment by ekzyis** [comment]
I forgot to add a corresponding query to the `user.hasNewNotes` resolver in #745
