### ISSUE TITLE
When a link to a nostr note is shared, extract noteid or nevent from url, and embed the note

### ISSUE THREAD

**Issue by huumn** [stackernews/stacker.news#1170]

**Comment by benalleng** [comment]
For some reference I know that Primal uses `noteId` vs what appears to be the more standard `nEvent` so we would likely need to have at least 2 ways to recognize a nostr note

These two links lead to the same event
https://primal.net/e/note1prrgyfue7xxaazapa3lg3p568tpd8883hnunta0ddvmu5ptljyhs2quhg8

https://snort.social/nevent1qqsq335zy7vlrrw73ws7cl5gs6dr4sknnncme7f47hkkkd72q4leztcpr9mhxue69uhhyetvv9ujuumwdae8gtnnda3kjctv9upzqpxfzhdwlm3cx9l6wdzyft8w8y9gy607tqgtyfq7tekaxs7lhmxfqvzqqqqqqyh0nfrc

Do you have any design ideas on how you might want the embed styled?

**Comment by huumn** [comment]
It doesn't need to be too fancy.

**Comment by sfr0xyz** [comment]
[Njump](https://njump.me/about)'s website widget `<script src="https://njump.me/embed/<nip-19-entity>" />` might be handy for this. It creates an embed from any NIP-19 entity.

**Comment by benalleng** [comment]
I'll check it out! I rolled my own from standard nostr-tools functions but I'll see if this is better for us

**Comment by benalleng** [comment]
Still have some stypling to do but WoW! 
![image](https://github.com/stackernews/stacker.news/assets/108441023/e36f0864-0b56-4d0c-aaa0-79ed75a0fa15)
@sfr0xyz Definitely want to pay you half of this PR, I would have been working on this for ages had I not known about this njump embed!

**Comment by sfr0xyz** [comment]
Looks great!

Thanks a lot! Very glad I could help.
