### ISSUE TITLE
Muting Error

### ISSUE THREAD

**Issue by Radentor** [stackernews/stacker.news#1177]
## Description
After [this update](https://stacker.news/items/540701), clicking "mute (stacker's nym)" button now returns an error message.

## Steps to Reproduce
1. Go to any stacker profile page (can also be done from homepage)
2. Click 3 dots menu button
3. Click "mute (stacker's nym)"
4. Error message shows up
![20240517_033710](https://github.com/stackernews/stacker.news/assets/166531701/cb2db1a4-8ef2-490a-a39e-9655190a7542)

## Expected behavior
Muting works normally before this update, but there is an alternative way to mute stacker :

1. Go to their profile
2. Subscribe to them
3. Unsubscribe
4. Mute them
5. Stacker is successfully muted

**Comment by huumn** [comment]
Nice catch!
