### ISSUE TITLE
Make polls anonymous

### ISSUE THREAD

**Issue by huumn** [stackernews/stacker.news#1192]
We current record a person's poll choice. For bitcoin-related polls this limits participation.

We should record that a person voted in a poll and prevent voting again, but we don't need to know their poll choice.

It'd be nice to also apply this retroactively.

**Comment by SatsAllDay** [comment]
I guess technically the selected poll option for a user could be determined if all users voted for the same option, but there's not really anything to be done about that.

**Comment by huumn** [comment]
Yeah the anonymity set could be small but better than what we currently have.
