### ISSUE TITLE
Images are no longer reserving vertical space

### ISSUE THREAD

**Issue by huumn** [stackernews/stacker.news#1193]
I'm not sure what broke but layout shift is back for images.

**Comment by tsmith123** [comment]
Any screenshots to go with this @huumn? Might take a look at some point.

**Comment by huumn** [comment]
It happens for a split second so it's tricky to shoot it, but I believe it's because `--aspect-ratio` on images is not being set

<img width="536" alt="Screenshot 2024-05-28 at 4 06 54 PM" src="https://github.com/stackernews/stacker.news/assets/34140557/3590a54f-c00c-4db5-a543-8e596794a090">

Testing this locally without imgproxy pro won't work (which makes me silly for expecting it be done), but it should be enough to make sure `--aspect-ratio` is set properly.

**Comment by huumn** [comment]
This was fixed in [b6e4f97](https://github.com/stackernews/stacker.news/commit/b6e4f9766884cc648abc0001a16206ed55670a83). 

It was caused by the worker accidentally loading env variables after imports were loaded so the imgproxy url was undefined.
