### ISSUE TITLE
implement sndev fund_nym

### ISSUE THREAD

**Issue by huumn** [stackernews/stacker.news#1199]
If you aren't running the `payments` docker compose profile, there's no way to top up the custodial wallet of a stacker for testing.

Provide a `sndev fund_nym NYM` in the `sndev` script that does something like 

```sh
docker__exec db psql -U sn -d stackernews -c 'update users set msats = 1000000 where name = 'NYM''
```

**Comment by ekzyis** [comment]
I would also use a command that zeroes the balance so I can easier test attached wallets

**Comment by huumn** [comment]
hmmm maybe the command should be `set_balance`
