### ISSUE TITLE
Allow appends to posts/comments after edit window

### ISSUE THREAD

**Issue by huumn** [stackernews/stacker.news#121]
https://stacker.news/items/13929

Main concern here is additional complexity ... alternative though is to allow editing indefinitely.

**Comment by jnmclarty** [comment]
What about exposing the change-log of a post?  Via git-diff like visual?

Allow infinite edits, but just expose full audit function.

In your other thread, you said something crazy like "allow anything if you pay enough".  Taking that to the limit, and the above idea - what if you could pay to _edit somebody else's post_.  It would just show you as a committer on the line's you changed.

Normies might get confused, but devs would feel right at home. 

Might be a fun "cake-day" like idea.  Once per year, every user gets one chance, on their birthday, to pay 10K sats to edit somebody else's post. hahaha.

It would show up as their edit transparently.

I'm promise I'm going to stop lobbing crazy ideas at your amazing site. lol.

**Comment by ekzyis** [comment]
Just want to mention that I see more people asking for this feature recently.

Examples:
- https://stacker.news/items/284941
- https://stacker.news/items/285263

Also, by tracking when people mention features (so in general, not only for this particular feature here), we could use them to ask for feedback when we've got a PR with screenshots or a staging environment where they can try it out.

**Comment by huumn** [comment]
It's not super difficult programming-wise to do this kind of edit history, but it has other implications.

e.g. I post a url that goes to the frontpage, then I swap it with my soundcloud url to my latest pop country single. 

This has implications for ranking.

**Comment by huumn** [comment]
comment pinning fixes this
