### ISSUE TITLE
Proactively notify user about not enough sats when attempting to Reply 

### ISSUE THREAD

**Issue by cointastical** [stackernews/stacker.news#122]
Allowing the user to compose a message that cannot be sent, due to no sats, can be frustrating. 

While right click permits the wallet to be opened in a new tab, most users won't think of doing that, and end up having to navigate away from the page where they had just composed their reply.

The top-level reply does not require an action, a person can just start typing.  So not sure what to do there other than perhaps detect typing in that textbox and notify if the user has insufficient balance in their wallet.   For any replies below the top level, that requires a click on Reply link. so that gives an opportunity to warn of No Sats at that point. 

Did I see somewhere that the SN app remembers the message composed but not sent?   If that is true, then simply the warning about not enough sats could be modified to simply add that the message will be there after topping up.   I'm not sure this is the behavior or if I am misremembering that being how it works.

**Comment by ekzyis** [comment]
> Did I see somewhere that the SN app remembers the message composed but not sent? If that is true, then simply the warning about not enough sats could be modified to simply add that the message will be there after topping up. I'm not sure this is the behavior or if I am misremembering that being how it works.

Yes, afaik it always saves them in local storage

**Comment by huumn** [comment]
JIT funding solves this afaict
