### ISSUE TITLE
Can't withdraw sats to Alby Extension

### ISSUE THREAD

**Issue by Gudnessuche** [stackernews/stacker.news#1222]
**Description**
Withdrawal difficulty to alby extension wallet

**Steps to Reproduce**
Try withdrawing sats to a connected alby extension

**Expected behavior**
The loader keeps buffering until the copy is clicked and then a message pops up with how much has been sent, but nothing's recieved on the alby end

**Screenshots**
![Screenshot 2024-06-04 192259](https://github.com/stackernews/stacker.news/assets/120573631/8632f3fa-0833-485c-abab-28ac481588fa)

**Environment:**
I used my PC for both SN and Alby extension
- Browser [Microsoft Edge]

**Additional context**
Help check if this is an alby problem, or if I must attach wallet first

**Comment by huumn** [comment]
If we say it's sent, then Alby has your money. This issue is on Alby's end. We don't control their wallet.

**Comment by Gudnessuche** [comment]
Thank you for that clarification
