### ISSUE TITLE
Addition of Naira(NGN) to fiat currencies

### ISSUE THREAD

**Issue by Gudnessuche** [stackernews/stacker.news#1226]
**Is your feature request related to a problem? Please describe.**
Not really a problem, more like a reference

**Describe the solution you'd like**
Addition of the Naira(NGN) as part of the currencies as they're more African users from that location

**Describe alternatives you've considered**
![Screenshot 2024-06-05 140430](https://github.com/stackernews/stacker.news/assets/120573631/18a526b9-ac98-4a4f-a64d-cfe0e1bc7a39)

**Additional context**
1ngn == 1sat, so this shouldn't be so hard to implement

**Comment by huumn** [comment]
@Gudnessuche do you have a lightning address I can send sats to?

**Comment by Gudnessuche** [comment]
yh, 

everythingsatoshi@getalby.com

**Comment by Gudnessuche** [comment]
EverythingSatsoshi@stacker.news

This is also my stackerNews ln address
