### ISSUE TITLE
Allow for multiple login methods on same account

### ISSUE THREAD

**Issue by secondl1ght** [stackernews/stacker.news#124]
Would it be possible to allow multiple logins methods to be linked to the same account? For example Twitter, a node, GitHub etc.

Use case for this is that I originally used Twitter auth to create my stacker.news account. After thinking about it I realized that if I get banned from Twitter I will lose access to my stacker.news account. Instead of creating a new account it would be good if I could link multiple login methods to the same account so that if I lose access to one, I can still login to my stacker.news.

Or is there already a way to recover your stacker.news account that I am not aware of?

Thanks

**Comment by huumn** [comment]
There isn't a way to do this yet. We have an issue for this open https://github.com/stackernews/stacker.news/issues/73 ... I'm currently blocked by the auth lib I'm using last I checked. Going to close this one because the other has a bit more context.
