### ISSUE TITLE
Territories have statistics for dates they didn't exist yet

### ISSUE THREAD

**Issue by ekzyis** [stackernews/stacker.news#1247]
**Description**

We launched territories six months ago but some territories have stats in 2021

**Steps to Reproduce**

Go to https://stacker.news/top/territories/custom?from=1624917600000&to=1625003999999

**Expected behavior**

We only show stats for territories that actually existed at that point.

**Screenshots**

_June 29th 2021, ~bitcoin_beginners was the top territory by stacked:_

![2024-06-29-162523_590x681_scrot](https://github.com/stackernews/stacker.news/assets/27162016/dc59fe56-b2ef-42f3-9004-4202f5bcf0a0)

_Territories that didn't exist yet are included in 2021:_

![2024-06-29-161909_590x681_scrot](https://github.com/stackernews/stacker.news/assets/27162016/e1501530-d2c7-426f-bde1-80f4c0db6901)

**Additional context**

https://stacker.news/items/590653

**Comment by huumn** [comment]
I would guess we don’t handle nulls properly or were misinterpreting create times.

**Comment by ekzyis** [comment]
Fixed in https://github.com/stackernews/stacker.news/pull/1195/commits/986f146386ac310861aad2578af200e9a24cccbe
