### ISSUE TITLE
Make dependence on web assembly optional

### ISSUE THREAD

**Issue by huumn** [stackernews/stacker.news#1252]
iOS in lockdown mode and graphene OS prevent wasm, so we shouldn't depend on loading it especially where not necessary.

https://stacker.news/items/595139/r/k00b?commentId=595602

**Comment by ekzyis** [comment]
Mhh, culprits that I can think of:

* [`lnc-web`](https://github.com/lightninglabs/lnc-web)
 
I think it's wasm only (not sure if that's even a thing) / has a hard dependency on it?

I couldn't even get to run `lnc-web` in #1243 again (it worked once but then it randomly broke afaik) so maybe we should just drop LNC?

* [`nostr-tools`](https://github.com/nbd-wtf/nostr-tools)
 
I think it _can_ use wasm but it's not a hard dependency. You mentioned in #1243 we should replace `nostr-tools` with simpler code.

WASM is kind of weird: When one installs a package, it seems to mean that one could now depend on wasm or not but it's not really transparent. Or I am misunderstanding something terribly.

**Comment by huumn** [comment]
We can keep lnc, but we need to not avoid loading it if wasm isn't permitted.

**Comment by huumn** [comment]
fixed in e0f91ace41bc2077761bd6708e46ea344ef023ac
