### ISSUE TITLE
Text Overflowing Out Of Bounds For "invoice canceled" Notification

### ISSUE THREAD

**Issue by takitakitanana** [stackernews/stacker.news#1257]
**Description**
When displaying a notification for a canceled invoice, the text overflows out of the bounds of the toast box, causing it to be partially hidden and unreadable.

**Steps to Reproduce**
Trigger a toast notification for a canceled invoice.

0. Be unauthenticated to force a payment.
1. Go to any post, write anything within the text area to leave a comment then press "reply" for 100 sats.
2. A window will pop up with the QR code/address to send the 100 sats, close this by pressing the "X" from the top-right side.
3. In the bottom-right side a notification will pop up with the message "invoice canceled" and a hash.
4. Observe:
    4.1 The hash string is overflowing out of bounds.
    4.2 There is no "X" top-right side of the red box notification to close it out.
    4.3 The notification will not go away after a few seconds, similar in the case of a green notification.
    4.4 As a result of 4.2 and 4.3, you can stack multiple notifications until you refresh the page.

**Expected behavior**
A) Text from the hash string is either cut to fit the notification box, or the notification box should be dynamic to fit the the text.
Other option as a quick fix can be so that the hash string can wrap on a 3rd line instead of overflowing or have it cut off.
B) User can manually close the notification.
C) Notification goes away by itself without the need for a page refresh.

**Screen
![Capture](https://github.com/stackernews/stacker.news/assets/112820741/8d2b3b00-3dba-46df-b07f-cf26b0aa73bd)shots**

**Environment:**
Same behavior on Win10 (Firefox & Chrome) and Debian (Firefox).

**Comment by takitakitanana** [comment]
Update:
![image](https://github.com/stackernews/stacker.news/assets/112820741/d3ec692a-1781-4b96-a04d-c23a980b8577)

Changing 

`@media screen and (min-width: 400px) {
  .toast {
    width: var(--bs-toast-max-width);
  }
}` 

to

`@media screen and (min-width: 400px) {
  .toast {
    width: auto;
  }
}`

in file "toast.module.css"

seems to fix the out of bounds text and make the "X" appear and resume user functionality to close notifications.

**Comment by ekzyis** [comment]
Thanks for this PR! I forgot to track this issue.

> Text from the hash string is either cut to fit the notification box

I think this is the way to go. Imo, the payment hash in the toast is not very useful.

**Comment by ekzyis** [comment]
Fixed by https://stacker.news/items/603906

**Comment by takitakitanana** [comment]
@huumn Will use my takitakitanana@stacker.news address.
Thank you
