### ISSUE TITLE
Pull down to refresh on iOS

### ISSUE THREAD

**Issue by ekzyis** [stackernews/stacker.news#1258]
**Is your feature request related to a problem? Please describe.**

This is a feature request that was requested [a long time ago](https://stacker.news/items/407120).

Pull down to refresh works on Android but not on iOS.

**Describe the solution you'd like**

Page refreshes on pull down.

**Describe alternatives you've considered**

n/a

**Additional context**

n/a

**Comment by Soxasora** [comment]
https://github.com/user-attachments/assets/33c51bee-35ec-4b0a-85b0-1d35e529c837

refreshing 🍾
i'm going to make it more graceful, any tips?

note: Android has native support for pull to refresh, this either has to be enabled just for iOS or site-wide disabling Android's one

**Comment by huumn** [comment]
You probably want this: https://www.apollographql.com/docs/react/data/refetching#clientrefetchqueries
