### ISSUE TITLE
Option to remove old post

### ISSUE THREAD

**Issue by hynek-jina** [stackernews/stacker.news#126]

**Comment by huumn** [comment]
Under what circumstances were you thinking? The issue we have is that we'd need a tombstone where the post was if there are comments.

**Comment by hynek-jina** [comment]
For example, Twitter doesn't allow you to edit posts, but you can delete them. Or on Slack, you can also delete a post, even if there is a discussion thread below it.

_And the reason may be, for example, a change of opinion. For example, you can promote an exchange and years later come to the conclusion that people shouldn't use exchanges at all. But you will still have an article on your profile recommending the exchange. Your subsequent explanation will be lost somewhere in the comments._

**Comment by notnout** [comment]
There could be extra charge 1000 sats for removing old post if there are comments ;)

**Comment by huumn** [comment]
Yeah this might be the move. Make nearly any behavior possible if you're willing to pay enough.

**Comment by ekzyis** [comment]
What about deleting without additional cost while one can still edit the post?

Example use-case: Replied to the wrong comment. I see no way currently to delete the comment afterwards.
