### ISSUE TITLE
Undefined comment root in profile items

### ISSUE THREAD

**Issue by ekzyis** [stackernews/stacker.news#1261]
**Description**

When you go to https://stacker.news/DeezSats/all, the site crashes with this error:

```
TypeError: Cannot read properties of null (reading 'user')
    at Comment (comment.js:131:19)
```

The error shows that `root` is undefined for some reason:

https://github.com/stackernews/stacker.news/blob/6cf16d3da7790e4d36fe42295242506e9a3cc9fd/components/comment.js#L131

This is weird since a comment should definitely have a root.

**Steps to Reproduce**

Go to https://stacker.news/DeezSats/all

**Expected behavior**

No error

**Additional context**

Reported by stacker here: https://stacker.news/items/603210?commentId=603906

**Comment by huumn** [comment]
The parent/root is a `status = 'STOPPED'` job.
