### ISSUE TITLE
Territory payment does not fallback to QR code

### ISSUE THREAD

**Issue by ekzyis** [stackernews/stacker.news#1266]
**Description**

I just tried to pay for a territory with a wallet attached and it went from "paying..." back to pay with no feedback. 

In the wallet logs, I saw that the payment failed due to insufficient funds. Makes sense, but I would have expected it to immediately show me a QR code or a notification that the payment failed. 

I then had to detach my wallet to get a QR code. 

I think that no QR code was shown is because we don't show QR codes if the payment took longer than a second for UX reasons. I don't know why no notification was shown. Isn't the payment marked as failed? Can't check the code right now.

**Steps to Reproduce**

1. Attach a wallet with insufficient balance for a territory payment
2. Try to pay for a territory where payment takes longer than a second

**Expected behavior**

Some user feedback and way to pay for my territory

**Comment by huumn** [comment]
It's a pessimistic payment. Pessimistic payments shouldn't have that 1 second limit. Nice catch.
