### ISSUE TITLE
Worker not started automatically for local development

### ISSUE THREAD

**Issue by vilm3r** [stackernews/stacker.news#128]
Spent a while debugging why the pgboss schemas weren't being created on a fresh install. I was able to remedy by manually starting the worker in the docker container.

I suggest either:

- Adding the worker start to the dev command
- Updating the README local development section to include a step to start the worker manually

**Comment by huumn** [comment]
Ah didn't realize I missed this, thanks!

**Comment by ezracarr** [comment]
@vilm3r perhaps a dumb question, but how exactly did you manually start the worker?

**Comment by ezracarr** [comment]
never mind, figured it out.  For any other n00bs like me:
take a look at the Procfile, copy the worker command `node --trace-warnings worker/index.js`, bump over to your docker dashboard, open up "stacker news" -> "app" , then open up a cli (button on top right) and run the command copied above
This should allow you to make posts and other database dependent actions

**Comment by huumn** [comment]
Fixed! https://github.com/stackernews/stacker.news/pull/203
