### ISSUE TITLE
Trying to setup login locally

### ISSUE THREAD

**Issue by secondl1ght** [stackernews/stacker.news#130]
I am trying to get login setup for my local dev environment, I copied the sample .env file and updated the Twitter credentials. Then I tried logging in using the Twitter button while running locally. But it is not working, am I missing a step?

**Comment by huumn** [comment]
You might be. What error/log messages do you get?

**Comment by secondl1ght** [comment]
There's this and this:
```
app    | [next-auth][error][signin_oauth_error] 
app    | https://next-auth.js.org/errors#signin_oauth_error {
app    |   statusCode: 401,
app    |   data: '{"errors":[{"code":32,"message":"Could not authenticate you."}]}'
```

```
app    | Could not find files for /login in .next/build-manifest.json
```

and then in the UI it shows this:

![image](https://user-images.githubusercontent.com/85003930/161317072-c055720f-ff24-4274-902b-f7953826b163.png)

**Comment by huumn** [comment]
Hmmmm ... It might not be configured right on Twitter's end assuming your credentials are correct ... you need to add the correct "Callback URI" to your twitter app settings, e.g. http://localhost:3000/api/auth/callback/twitter

**Comment by secondl1ght** [comment]
Hmm what do you mean 'twitter app settings'? Maybe the readme could be expanded on this topic? I would like to give issue #103 a try but I need to get login working locally before starting this. Im also available for a screenshare at some point too if you prefer to debug this that way.

**Comment by huumn** [comment]
You got your credentials for https://developer.twitter.com/ right? In the app settings that you create there, you need to specify the callback uri.

Agreed that this might not be obvious for newcomers to the project. Curse of Knowledge and all that.

**Comment by secondl1ght** [comment]
Ah ok, no I did not know that - I was using my real Twitter credentials. Will setup this dev option and try again, thanks!

**Comment by secondl1ght** [comment]
Are any of the other auth options easier to setup than the Twitter one? Just trying to get up and running locally as quick as possible.

**Comment by ezracarr** [comment]
hey @huumn I'm able to login and create posts locally but when I try to fund my wallet I am getting this error.

`   | [
app    |   503,
app    |   'AddInvoiceError',
app    |   {
app    |     err: Error: 14 UNAVAILABLE: No connection established
app    |         at Object.callErrorFromStatus (/app/node_modules/@grpc/grpc-js/build/src/call.js:31:26)
app    |         at Object.onReceiveStatus (/app/node_modules/@grpc/grpc-js/build/src/client.js:179:52)
app    |         at Object.onReceiveStatus (/app/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:336:141)
app    |         at Object.onReceiveStatus (/app/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:299:181)
app    |         at /app/node_modules/@grpc/grpc-js/build/src/call-stream.js:145:78
app    |         at processTicksAndRejections (internal/process/task_queues.js:77:11) {
app    |       code: 14,
app    |       details: 'No connection established',
app    |       metadata: [Metadata]
app    |     }
app    |   }
app    | ]`

I've added the cert, macaroon and socket from a node I have running locally on Polar into the .env.sample file.
Any ideas why it is not connecting?

**Comment by huumn** [comment]
This indicates you can't even connect, so we can rule out cert/macaroon issues. I'd guess the socket info is wrong somehow or something else is preventing the connection.

**Comment by ezracarr** [comment]
OK thanks.  I took the socket info directly from the node I have running on polar (127.0.0.1:10001). I'll keep messing with it

**Comment by huumn** [comment]
AFAIK this is simply tricky to config but not to be fixed so closing.
