### ISSUE TITLE
Encrypted wallet credentials device sync

### ISSUE THREAD

**Issue by ekzyis** [stackernews/stacker.news#1304]
**Is your feature request related to a problem? Please describe.**

Spending wallets are currently stored unencrypted on client devices as this disclaimer shows:

![2024-08-15-174318_685x177_scrot](https://github.com/user-attachments/assets/38916082-d9c6-423a-b43c-3c2bcc03c64c)

We don't store them on the server because we don't want to be able to spend users' funds.

As the disclaimer mentions, a user has to reenter their credentials on other devices. This is bad UX. 

**Describe the solution you'd like**

Users can enable device sync with a checkbox, for example on /settings/wallets.

When this checkbox is enabled, we will ask them for a password or generate cryptographically secure mnemonics for them. A key pair will be derived from this secret using [`window.crypto.subtle.deriveKey()`](https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto/deriveKey). The secret is stored on the device (and only on the device) so it can be looked up again by the user; for example to enter it into a different device to generate the same key pair. This exchange could be done manually or with the help of QR codes.

If a client device with a key pair saves a wallet, it will encrypt with AES-GCM and attempt to save the credentials on the server. The save will fail if there are existing encrypted credentials for this wallet on the server to prevent overwrites. In this case, the credentials are only saved locally. If the save is successful, existing local (unencrypted) credentials are deleted.

If a client device with a key pair fetches a wallet, it will also fetch any existing encrypted credentials for this wallet from the server and try to decrypt them. Since AES-GCM uses authenticated encryption, decryption will graciously fail if the configuration was not encrypted with our public key. If decryption succeeds, it will use these instead of any existing local unencrypted wallet credentials. They are deleted instead.

If a client device with a key pair deletes a wallet, it will also submit the encrypted credentials (or a hash of them) to be deleted. This is done so we can compare them with existing encrypted wallet credentials on the server. If they match, they are also deleted on the server, not only the configuration for receiving.

So essentially, each wallet on the server will additionally have a single column to share encrypted data between devices with keys shared out-of-band.

This scheme not only enhances UX but also security since credentials are no longer stored unencrypted on client devices. They still store a key which could be accessed with a XSS vuln for example[^1] but an attacker would also need access to the encrypted credentials by taking over a user session (more severe than XSS) or getting access to the data on the server (also more severe than XSS).

[^1]: We could also only store the key "locked" (encrypted) and "unlocking" (decrypting) and loading it into memory requires a PIN.

**Describe alternatives you've considered**

n/a

**Additional context**

* the device secret could also be used for E2EE of other data like #56

**Comment by riccardobl** [comment]
would it make sense to have this as a general purpose synched storage with localStorage-like apis?

**Comment by riccardobl** [comment]
I've been working on implementing this feature and i have a few design changes to propose:

### 1. Make it an account-wide service (e.g., vault)
This service should have its own table as it can be used to store other items, such as the NIP-46 connection token.

### 2. Use a public-private key pair and save the public key on the server
This allows the system to detect if the user inputs the wrong mnemonic on another device. The goal is to prevent the user from ending up with multiple wallets encrypted with different keys, which could happen due to a typo on the second device.

### 3. Add an option for the user to clear everything
This feature would delete all the encrypted rows associated with the user's profile. This would also drop the stored pubkey and allow the user to change the mnemonic

### 4. make it configurable in `/settings`
The user setting page could say something like:
```
# Device Sync
Certain sensitive information is stored on your device 
and is never transmitted to our server. To simplify configuration 
across all your devices, you can enable "Device Sync." 
This allows you to use a mnemonic of your choice to encrypt 
information, which is then shared securely across all your devices.

[Enable/Disable(aka Clear) Device Sync]

```

When the user logs in with a new device, if device sync is enabled, it will show a skippable modal asking for a mnemonic.

**Comment by ekzyis** [comment]
I agree with all points except the first because I don't know why we would want to store the connection token. Isn't it only needed for authentication? And since you need to have been already authenticated to access any encrypted data, it would be moot?

I would try to keep this as simple as possible. We probably will want to use whatever we implement for E2EE DMs but if it only works for the wallets now and will require additional work for DMs that's fine imo.

**Comment by riccardobl** [comment]
> I agree with all points except the first because I don't know why we would want to store the connection token. Isn't it only needed for authentication? And since you need to have been already authenticated to access any encrypted data, it would be moot?

Sorry i misspoke, i meant the connection state. To do crossposting with a nip46 signer we need to save the random app privkey and the signer pubkey+relay from the bunker token. They are required to "revive" the session for the sign_event rpcs.

**Comment by riccardobl** [comment]
Solved by https://github.com/stackernews/stacker.news/pull/1507
