### ISSUE TITLE
Searching a Hashtag fails with a 404

### ISSUE THREAD

**Issue by cointastical** [stackernews/stacker.news#133]
The following will result in a 404 - Page not found error message, with the "Alice in wonderland maze" image.
https://stacker.news/search?q=#bitcoin

I would think words for that string without the "#" hashtag prefix would be included in the search results, but probably exact matches including that "#" prefix should get ranked higher in the search results.

There are some instances, such as ```Episode #123```, where the matches without the "#" prefix are probably nearly as close (e.g., "Episode 123".  There are probably other quirks with hashtags, I can imagine.

**Comment by cointastical** [comment]
I see there was discussion about using hashtags to identify a sub as well, so wanted to share that here as well;
https://stacker.news/items/7767

**Comment by nickkrauts** [comment]
One possible solution: when a user searches using a hashtag, for example "#Bitcoin", we can convert to URL encoded parameters and send "%23Bitcoin" to the browser instead. This would at least squash the bug. I'm thumbing through the code now to see where one could enter this functionality - perhaps in search.js

**Comment by huumn** [comment]
@nickkrauts that's what I did and it was in fact in `components/search.js`

Fixed locally.
