### ISSUE TITLE
Privacy-preserving settings for auto-loading twitter and youtube embedded media

### ISSUE THREAD

**Issue by SatsAllDay** [stackernews/stacker.news#1331]
**Is your feature request related to a problem? Please describe.**
I described the idea for this feature on SN [here](https://stacker.news/items/611650/r/WeAreAllSatoshi), largely to gauge interest. I wouldn't say there was much interest, but I figured I'd log the issue here anyway, in case the SN team agrees it's a valuable addition, and someone wants to implement it.

Basically, I think it would be nice to have a user setting that would allow you to disable making network requests to twitter, youtube, etc. by showing the embedded preview on posts that link to twitter, youtube, etc.

Similar to how SN moved the call to coinbase that populates the price ticker in the page header to server-side so as to not leak user's IPs to coinbase, this would give stackers a built-in mechanism to avoid loading resources from these other platforms by default.

**Describe the solution you'd like**
A user setting, enabled by default for all users, that controls whether the embedded previews for Twitter/X/YouTube links are rendered when viewing an SN item. Controllable in user settings page.

**Describe alternatives you've considered**
In the discussion on the [SN post](https://stacker.news/items/611650/r/WeAreAllSatoshi) where I originally pitched this idea, there are alternatives described like browser extensions that can do this for you. It's also possible to do it via custom DNS like pi-hole and probably also VPNs. Despite all that, I think there's still value in having this supported within the SN platform itself. Perhaps I am alone in thinking this.

**Additional context**
N/A

**Comment by huumn** [comment]
Yep, I think it makes sense!
