### ISSUE TITLE
Search enhancements

### ISSUE THREAD

**Issue by huumn** [stackernews/stacker.news#135]
Currently our search is pretty much a sledge hammer and just kind of does one thing: finds a fire hose of things based on a query matching items. 

It'd be nice to make search more full featured. Cointastical, who is probably a representative power user of search, wrote up some issues/requests: https://stacker.news/items/19674

**Comment by cointastical** [comment]
Should this ticket be closed?
https://stacker.news/items/83923

**Comment by huumn** [comment]
Close thanks!
