### ISSUE TITLE
Pessimistic zaps via QR show `XXX sats received` then appears to "freeze" until settled

### ISSUE THREAD

**Issue by huumn** [stackernews/stacker.news#1361]
This is only noticeable when the outgoing payment is slow (receiver's wallet has tor channels). 

I'm unsure of what to do exactly, but showing another pending state would make this more transparent.

**Comment by ekzyis** [comment]
We could show "settling invoice ..." (or something that is less LN and more SN specific) if it takes longer than a few seconds. So not immediately show it but only show it to users who are waiting and might be confused.

We could also do something fun like other loading screens do. For example, games communicate they are loading different stuff at different stages. We aren't (not sure games are, either) but we could show increasing apologizing messages like "wow, this is taking long ..." the longer it takes.

**Comment by huumn** [comment]
I'm thinking ideally it'd be better to just close it, then toast if there's an error on settlement ... might require a special case for zaps though
