### ISSUE TITLE
Clarify error message when LN Invoice did not specify the amount

### ISSUE THREAD

**Issue by cointastical** [stackernews/stacker.news#140]
When withdrawing, if the LN Invoice provided does not have an amount, a flash error message is shown:
"Error: you must specify amount"

However, someone not all that familiar with how Lightning invoices work might think that the message is referring to the max fee field, which is the only "amount" field for the withdrawal form.  Or they may be confused as there is no amount field showing.

Of course, the message is referring to how the LN invoice pasted did not have the amount, and thus SN cannot pay the LN invoice.  

So this request is to clarify the error message to indicate explicitly that the LN Invoice did not specify an amount.

**Comment by huumn** [comment]
Done locally
