### ISSUE TITLE
Respond to /search with a search form when there was no q= query parameter 

### ISSUE THREAD

**Issue by cointastical** [stackernews/stacker.news#141]
The form is essentially nothing more than header, footer and search field.

One reason for this request is that this provides a URL for Search that can be bookmarked.

This was first described in SN [Item #21288](https://stacker.news/items/21288)

**Comment by lazaruslarue** [comment]
Just barely taking a look here. I guess it's [here? ](https://github.com/stackernews/stacker.news/blob/master/components/search.js#L26)

**Comment by huumn** [comment]
@lazaruslarue no it's [here](https://github.com/stackernews/stacker.news/blob/e2409efbaf4ea7fe03e9ba56b7f2f09023b7746d/pages/search.js#L8) ... It's a higher order function ... that last parameter `'q'` says if that isn't specified to 404.

**Comment by huumn** [comment]
Fixed locally.
