### ISSUE TITLE
Login with lightning -- requires doing lightning sig twice (phoenix on android)

### ISSUE THREAD

**Issue by tphyahoo** [stackernews/stacker.news#1415]
*Note: this template is meant to help you report the bug so that we can fix it faster, ie not all of these sections are required*

**Description**
Login with lightning works, but I have to repeat the lightning send twice. 

It only shows me logged in after I do it twice. 

**Steps to Reproduce**

I am logging in on phone, and I do it by copying the lightning url and pasting into "send" on phoenix. 

Verified this behavior several times. Can anyone else duplicate?

Also curious if same problem on desktop. 

**Expected behavior**
Should only need doing once. 

**Environment:**
If you only experience the issue on certain devices or browsers, provide that info.
 - Device: newish samsung android phone
 - OS: android
 - Browser chrome
 - lightning wallet: phoenix

**Comment by ekzyis** [comment]
That's weird, that's not the case for me. I can scan the QR code with Phoenix on iOS. When I confirm the login by pressing `Authenticate` in Phoenix, I am logged in and Phoenix shows `Authenticated`.

What does Phoenix show the first time in your case? Does that also happen with other wallets or browser extensions that support LNURL-auth like [Alby](https://chromewebstore.google.com/detail/alby-bitcoin-wallet-for-l/iokeahhehimjnekafflcihljlcjccdbe?pli=1)?

**Comment by riccardobl** [comment]
I've tried to reproduce the issue with no success. 

This is what i did step by step:
- open stacker.news on android with chrome and start the login action
- copy the invoice
- open phoenix wallet on the same device
- paste the invoice in `send` and click `Sign-in`
- wait for `authentication success`
- return to the chrome activity
- wait a couple of seconds (this is maybe slower than ideal)
- logged-in


Is this still happening to you? Are you doing something differently?

**Comment by tphyahoo** [comment]
Can't reproduce. 

I guess we should close it.
