### ISSUE TITLE
Dup prevention should not be case sensitive for Twitter accounts

### ISSUE THREAD

**Issue by cointastical** [stackernews/stacker.news#142]
The duplicate prevention check will see the following as being distinct / unique, and thus not show the DUP alert:

- https://Twitter.com/stacker_news
- https://Twitter.com/Stacker_News

I don't know what other URL types would also need to be made case insensitive as well.  I can imagine Github being one:

- https://github.com/stackernews
- https://github.com/StackerNews

**Comment by huumn** [comment]
👍 URLs are generally case insensitive

**Comment by cointastical** [comment]
> URLs in general are case-sensitive (with the exception of machine names). There may be URLs, or parts of URLs, where case doesn't matter, but identifying these may not be easy. Users should always consider that URLs are case-sensitive. /u

https://www.w3.org/TR/WD-html40-970708/htmlweb.html
https://stackoverflow.com/questions/7996919/should-url-be-case-sensitive/7996997#7996997

But I can't think of any time where I've seen two different URLs have only a difference in case, and them both being unique, and valid requests (e.g., not giving a 404, or something to that effect).   So for duplicate detection, ignoring case shouldn't cause any issue that I can tell.

**Comment by huumn** [comment]
Fixed locally.
