### ISSUE TITLE
Personalized invite links

### ISSUE THREAD

**Issue by Darth-Coin** [stackernews/stacker.news#1421]
**Is your feature request related to a problem? Please describe.**
Yes, sometimes user could have so many invite links and don't know anymore where were shared, to who etc.

**Describe the solution you'd like**
An additional way to create invite links: Stacker creating the invite links with personalized code like https://stacker.news/invites/deathstar or invites/telegram-group-x.

In this way I can track better and focus the invites only to specific groups.

The standard one with random codes is just fine, is good to be used too, if are individual invites.

I know I can use the general invite code https://stacker.news/r/DarthCoin but that is too general and I do not know if I share it to x or y platform or group of people.

**Comment by huumn** [comment]
Oh good point. Some kind of invite tracking would be cool.

**Comment by riccardobl** [comment]
@Darth-Coin  does this satisfy your use case: https://github.com/stackernews/stacker.news/pull/1649 ?
