### ISSUE TITLE
404 page should allow searching

### ISSUE THREAD

**Issue by notnout** [stackernews/stacker.news#143]
e.g. https://stacker.news/not-found

Current 404 page returns nice picture, but it would be useful to allow user to search for the thing they were trying to get. 
Either by just having the searchbox on the bottom or even by updating the not_found page messaging to suggest that user could search instead.

**Comment by cointastical** [comment]
Perhaps the response for a 404 is the /search page (with a flash message stating the 404 for the URL given?).   This /search does not yet exist but is a feature request in issue #141.

**Comment by huumn** [comment]
Fixed locally
