### ISSUE TITLE
Add MathJax support

### ISSUE THREAD

**Issue by SouthKoreaLN** [stackernews/stacker.news#1436]
**Is your feature request related to a problem? Please describe.**
Again, a bit of a niche request, but see [this post](https://stacker.news/items/700785). It'd be nice to be able to support latex (and other math syntax) through MatJax.

**Describe the solution you'd like**
MathJax is described here: https://www.mathjax.org/

**Describe alternatives you've considered**
I currently mostly generate the equation with an outside latex compiler and then copy the image directly into SN.

**Comment by huumn** [comment]
We definitely want this. Thanks for the issue!

**Comment by huumn** [comment]
We should be able to use this [rehype-mathjax](https://github.com/remarkjs/remark-math/tree/main/packages/rehype-mathjax).
