### ISSUE TITLE
Zapping parent comment while writing sibling comment can cause comment to not show on submit

### ISSUE THREAD

**Issue by huumn** [stackernews/stacker.news#1450]
Repro: 

1. open reply under comment
2. type comment
3. zap parent comment
4. hit submit

It might be specifically a non-custodial bug caused by rerendering.

**Comment by toyota-corolla0** [comment]
I am having trouble reproducing. I have tried with native wallet and WebLN wallet. Which wallet were you using?

**Comment by huumn** [comment]
I was using nwc. I saw this in production.

**Comment by riccardobl** [comment]
I can't reproduce this with the current master branch on local dev with NWC attached.
It might be some sort of edge case.

**Comment by huumn** [comment]
I think was fixed by modifying the paid action fragment in some recent pr.
