### ISSUE TITLE
Device sync does not maintain WebLN priority

### ISSUE THREAD

**Issue by huumn** [stackernews/stacker.news#1452]
Repro: attach/enable WebLN, attach/enable nwc, give WebLN higher priority, then refresh page.

**Comment by huumn** [comment]
Instead of not syncing WebLN at all, we probably want to sync it, then on each device test if it's available, then enabled disable on specific devices if it's present.

**Comment by huumn** [comment]
I'm not sure if it's possible yet, but it might be better to store `perDevice` wallets in localstorage, then merge with vault.

**Comment by ekzyis** [comment]
I removed `priority:high` and added `blocked` since device sync was reverted and thus this is no longer on `master` but waiting for #1447. Keeping this ticket open as a reminder to test #1447 for this.
