### ISSUE TITLE
Footnotes no longer use superscript

### ISSUE THREAD

**Issue by ekzyis** [stackernews/stacker.news#1472]
I have noticed that our footnotes no longer render like in Github using superscript[^1] but like this:

![2024-10-10-190829_223x131_scrot](https://github.com/user-attachments/assets/d7d6f7c6-3d39-4cd3-9e05-98d2675e2140)

I believe this is not intended.

[^1]: test footnote

**Comment by huumn** [comment]
It is intended to look more like hn's footnotes as we once discussed.
