### ISSUE TITLE
Unable to load page due to CORS errors

### ISSUE THREAD

**Issue by adevries17** [stackernews/stacker.news#1474]
**Description**
Whenever I attempt to load the page for stacker.news, I get a bunch of CORS errors. I am using Firefox v131.0.2 at time of writing. I attempted this in a private window so no cookies have been saved

**Steps to Reproduce**
Open Firefox to https://stacker.news/

**Expected behavior**
The page to load properly

**Screenshots**
![image](https://github.com/user-attachments/assets/aea1ddfc-3816-414e-bca8-bb005300c232)

**Logs**
Content-Security-Policy warnings 5
Content-Security-Policy: Ignoring “'self'” within script-src: ‘strict-dynamic’ specified [stacker.news](https://stacker.news/)
Content-Security-Policy: Ignoring “https://a.stacker.news/” within script-src: ‘strict-dynamic’ specified [stacker.news](https://stacker.news/)
Content-Security-Policy: Ignoring “'unsafe-inline'” within script-src: ‘strict-dynamic’ specified [stacker.news](https://stacker.news/)
Content-Security-Policy: Ignoring “https:” within script-src: ‘strict-dynamic’ specified [stacker.news](https://stacker.news/)
Content-Security-Policy: Ignoring “'unsafe-inline'” within script-src: nonce-source or hash-source specified [stacker.news](https://stacker.news/)
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://a.stacker.news/_next/static/css/f31815dc4d424621.css. (Reason: CORS request did not succeed). Status code: (null).

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://a.stacker.news/_next/static/chunks/webpack-3434540389b1c5f8.js. (Reason: CORS request did not succeed). Status code: (null).

<script> source URI is not allowed in this document: “https://a.stacker.news/_next/static/chunks/webpack-3434540389b1c5f8.js”. [stacker.news:39:847](https://stacker.news/)
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://a.stacker.news/_next/static/chunks/framework-b78bc773b89d3272.js. (Reason: CORS request did not succeed). Status code: (null).

<script> source URI is not allowed in this document: “https://a.stacker.news/_next/static/chunks/framework-b78bc773b89d3272.js”. [stacker.news:39:1033](https://stacker.news/)
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://a.stacker.news/_next/static/chunks/main-bdb81ad35ab984c5.js. (Reason: CORS request did not succeed). Status code: (null).

<script> source URI is not allowed in this document: “https://a.stacker.news/_next/static/chunks/main-bdb81ad35ab984c5.js”. [stacker.news:39:1214](https://stacker.news/)
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://a.stacker.news/_next/static/chunks/pages/_app-0b7a0b85a9f5e61b.js. (Reason: CORS request did not succeed). Status code: (null).

<script> source URI is not allowed in this document: “https://a.stacker.news/_next/static/chunks/pages/_app-0b7a0b85a9f5e61b.js”. [stacker.news:39:1401](https://stacker.news/)
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://a.stacker.news/_next/static/chunks/pages/~-b259445f4be25b69.js. (Reason: CORS request did not succeed). Status code: (null).

<script> source URI is not allowed in this document: “https://a.stacker.news/_next/static/chunks/pages/~-b259445f4be25b69.js”. [stacker.news:39:1585](https://stacker.news/)
Request for font "Nimbus Roman" blocked at visibility level 2 (requires 3)
[stacker.news](https://stacker.news/)
Request for font "URW Bookman" blocked at visibility level 2 (requires 3)
[stacker.news](https://stacker.news/)
Request for font "C059" blocked at visibility level 2 (requires 3)
[stacker.news](https://stacker.news/)
Request for font "P052" blocked at visibility level 2 (requires 3)
[stacker.news](https://stacker.news/)
Request for font "Standard Symbols PS" blocked at visibility level 2 (requires 3)
[stacker.news](https://stacker.news/)
Request for font "Caladea" blocked at visibility level 2 (requires 3)
[stacker.news](https://stacker.news/)
Request for font "Symbola" blocked at visibility level 2 (requires 3)
[stacker.news](https://stacker.news/)
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://a.stacker.news/_next/static/915fc8/_buildManifest.js. (Reason: CORS request did not succeed). Status code: (null).

<script> source URI is not allowed in this document: “https://a.stacker.news/_next/static/915fc8/_buildManifest.js”. [stacker.news:39:1759](https://stacker.news/)
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://a.stacker.news/_next/static/915fc8/_ssgManifest.js. (Reason: CORS request did not succeed). Status code: (null).

<script> source URI is not allowed in this document: “https://a.stacker.news/_next/static/915fc8/_ssgManifest.js”.

**Environment:**
If you only experience the issue on certain devices or browsers, provide that info.
 - Device: Desktop PC
 - OS: Linux
 - Browser Firefox
 - Version 131.0.2

**Additional context**

**Comment by huumn** [comment]
Firefox loads it fine on Mac OS. @ekzyis can you reproduce?

**Comment by huumn** [comment]
Testing CORs on one of the resources your browser denies using `curl` shows the appropriate `access-control-allow-origin`.

```bash
[keyan stackernews]🍏 curl --head -H "Origin: https://stacker.news" https://a.stacker.news/_next/static/css/f31815dc4d424621.css          
HTTP/2 200 
content-type: text/css; charset=UTF-8
content-length: 307477
date: Sat, 05 Oct 2024 22:00:33 GMT
server: nginx/1.22.1
cache-control: public, max-age=31536000, immutable
accept-ranges: bytes
last-modified: Sat, 05 Oct 2024 21:59:40 GMT
etag: W/"4b115-1925eb20f36"
onion-location: http://snsnsnya6h3ot563f3p566wuhfoklkg5f62hokdlaqzcaub3gf4xlxyd.onion/_next/static/css/f31815dc4d424621.css
vary: Accept-Encoding
x-cache: Hit from cloudfront
via: 1.1 5b37a5f495d4308c4ea7c4c34dd0dd94.cloudfront.net (CloudFront)
x-amz-cf-pop: DFW56-P2
x-amz-cf-id: L69RaBqcUggtpselk0G5-a3WIaVH2mlpLHegA7rTZ3nZHdNdJEvqww==
age: 590285
access-control-allow-origin: https://stacker.news
vary: Origin
```

**Comment by huumn** [comment]
Do you have [enhanced tracker prevention](https://support.mozilla.org/en-US/kb/firefox-protection-against-fingerprinting) enabled? Or any other non-default config?

It appears you're also blocking fonts which is weird on its own. I suspect your browser configuration might not be "stock."

```
Request for font "Nimbus Roman" blocked at visibility level 2 (requires 3)
```

**Comment by huumn** [comment]
There's a report on SO, https://stackoverflow.com/a/56970532, that suggests this might happen with the Privacy Badger extension.

**Comment by adevries17** [comment]
@huumn I disabled all of the extra privacy/security options for the site when I submitted this request. Im not sure whats going on but it loads normally now even with ublock origin and enhanced tracker prevention enabled. Might be some weird edge case when I was loading the page :shrug:

**Comment by huumn** [comment]
hmmm well I'm glad it's working again! I'm going to close.

Thanks for letting us know and please let us know if it happens again. Sometimes these things happen and folks don't report them.
