### ISSUE TITLE
Clarify that "n sats per min" in jobs board is NOT the wage / compensation being offered for the job

### ISSUE THREAD

**Issue by cointastical** [stackernews/stacker.news#149]
There's WAY too many people who are confusing the "n sats per min" in the jobs board as being the wage being offered for the job.

- Exhibit A: https://stacker.news/items/24097
- Exhibit B: https://t.me/TheSimplyBitcoinChannel/52231

Related discussion:

> Perhaps there needs to be a prefix (e.g., listing fee: n sats per min) or that being shown under column of its own -- with a title,  or perhaps some other way to explain to what that references.

https://stacker.news/items/24144

**Comment by cointastical** [comment]
Another example of this occurring:

*sats/min: Salary of the Future*
https://stacker.news/items/31831

**Comment by huumn** [comment]
I've seen it on twitter too. Yikes.

**Comment by ludo237** [comment]
I think that the `sats per minute` statistic can be removed entirely. From the end user perspective it doesn't add much to the information of the job and I can be misleading

**Comment by AryanJ-NYC** [comment]
Hey. Are y'all accepting PRs from outside of your organization? If so, I'm looking for a quick, easy issue that'll get me clicking throughout the codebase and this is a good candidate.

If you've decided on removing it, can I take this ticket?

**Comment by huumn** [comment]
> If you've decided on removing it, can I take this ticket?

PRs are always welcome. Note, this specific PR might not be merged until a larger set of job board enhancements are introduced.
