### ISSUE TITLE
Wallets that are failing can’t be disabled due to test invoice, validation 

### ISSUE THREAD

**Issue by huumn** [stackernews/stacker.news#1501]
As stated in #1500, my wallet which ordinarily works is failing in my current network context. I’d like to simply disable it temporarily to use qr but I can’t disable it because it can only be saved if the wallet works - which it doesn’t at the moment.

**Comment by riccardobl** [comment]
This should be fixed in: https://github.com/stackernews/stacker.news/pull/1460

https://github.com/stackernews/stacker.news/blob/ae2288fc0b4d4395f4a359291600fef5223b3aab/api/resolvers/wallet.js#L679

**Comment by ekzyis** [comment]
> This should be fixed in: #1460

I basically did your change in 5d0fc923, see #1511

**Comment by ekzyis** [comment]
#1511 was superseded by #1507 which fixed this
