### ISSUE TITLE
Youtube dup detection does not also check for either m. subdomain (mobile) or /embed

### ISSUE THREAD

**Issue by cointastical** [stackernews/stacker.news#151]
The following URLs are all for the same video.

1. https://www.youtube.com/watch?v=dQw4w9WgXcQ
2. https://m.youtube.com/watch?v=dQw4w9WgXcQ
3. https://www.youtube.com/embed/dQw4w9WgXcQ

SN's dup detection doesn't see either number 2 (m. subdomain (mobile)) or number 3 (/embed) as being a duplicate of number 1 ...  and vice-versa.

I see there are other formats:
https://gist.github.com/rodrigoborgesdeoliveira/987683cfbfcc8d800192da1e73adc486

/v: https://www.youtube.com/v/dQw4w9WgXcQ <--SN dup detection does correctly see this as a duplicate
/e: https://www.youtube.com/e/dQw4w9WgXcQ <--SN dup detction does NOT see this  (no idea what /e means though, ... also embed? Never have seen it in the wild.)

I didn't look at every entry in that list, there might be other formats that I didn't notice.  If there are more, they definitely aren't commonly used -- at least that I've ever seen.

Also, I didn't consider any that might be for the shortened URL format, as (closed) issue #95 addressed.

**Comment by huumn** [comment]
I don't want to over-index on rarely used paths (like embeds) on a specific domain. I've added support for /v/ though and m locally.
