### ISSUE TITLE
Dup detection ignores URLs that have # (fragment)

### ISSUE THREAD

**Issue by cointastical** [stackernews/stacker.news#152]
A request for each of the following two URLs will get an identical response. The existence of the URL fragment (#Test) will somehow evade SN's current dup detection.
   
1. [https://www.learn-html.org/en/Hello,_World!](https://www.learn-html.org/en/Hello,_World!)
2. [https://www.learn-html.org/en/Hello,_World!#Test](https://www.learn-html.org/en/Hello,_World!#Test)

When trying to create a Link Post using number 1, when a post already exist using number 2, there will be no warning ("dupes") shown.

However, going the other way ... trying to create a post using number 2, when a post already exists using number 1, SN will correctly detect that there is a duplicate.

**Comment by huumn** [comment]
Done locally.
