### ISSUE TITLE
images in drafts are deleted when navigating to a link in preview 

### ISSUE THREAD

**Issue by sig47** [stackernews/stacker.news#1522]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

If inserting an image when drafting a post, the image is deleted if you move to preview mode and then click a link to another page.  

### Steps To Reproduce

1. click "post", then choose discussion post.
2. Go to text box "write mode and insert a photo
3. enter the url to an external page in the body of the draft text.
4. Switch to "preview", then click the link to the external page
5. The code for the inserted image has been deleted when you return to the "write" menu.

### Expected behavior

I expected the image to remain in the draft while checking external links before posting.

### Device information

OS Ubuntu Linux
Browser Firefox

**Comment by ekzyis** [comment]
I see the problem:

https://github.com/user-attachments/assets/bacf9000-3f3b-4bf2-9077-fbbf67f0416d

It's unrelated to preview. It happens because we don't save the draft after upload, only when something was typed.

Fix would be to trigger the event that triggers saving the draft.

**Comment by sig47** [comment]
No big deal. Thanks for letting me know.

Sent from Proton Mail Android

-------- Original Message --------
