### ISSUE TITLE
Feature request: Show "dupes: none" after dup search has completed and no duplicates found

### ISSUE THREAD

**Issue by cointastical** [stackernews/stacker.news#153]
Creating a link Post on SN can be completed very quickly -- so quickly that one might click the "post" button not realizing that SN was still searching for possible dupes.

This request is to simply have some indicator appear when no dupes are found ... like a green "dupes: none".  For when duplicates are found, no change is needed.

Alternatively, SN could disable the Post button until the search for dupes has completed (and dupes flag rendered, if any dupes existed) -- but doing that seems like it could introduce confusion.

**Comment by huumn** [comment]
I only really only want a user to have to think about dupes if there is one

**Comment by ekzyis** [comment]
> Alternatively, SN could disable the Post button until the search for dupes has completed (and dupes flag rendered, if any dupes existed) -- but doing that seems like it could introduce confusion.

This is done in #255

**Comment by cointastical** [comment]
Resolved with Pull #255.
