### ISSUE TITLE
New wallet validation code has cyclic dependency 

### ISSUE THREAD

**Issue by riccardobl** [stackernews/stacker.news#1538]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Needs https://github.com/stackernews/stacker.news/pull/1537 or it won't reach the code that causes the issue.
Typing anything into the blink attachment will cause a cyclic dependency exception in the yup schema:

```
Unhandled Runtime Error
Error: Cyclic dependency, node was:"apiKeyRecv"

Source
wallets/validate.js (104:39) @ shape

  102 |   // we use Object.keys(schemaShape).reverse() to avoid cyclic dependencies in Yup schema
  103 |   // see https://github.com/jquense/yup/issues/176#issuecomment-367352042
> 104 |   const composedSchema = Yup.object().shape(schemaShape, Object.keys(schemaShape).reverse()).concat(Yup.object({
      |                                       ^
  105 |     enabled: Yup.boolean(),
  106 |     priority: Yup.number().min(0, 'must be at least 0').max(100, 'must be at most 100')
  107 |   }))
```

### Screenshots

![image](https://github.com/user-attachments/assets/d4c6b6c7-a58a-42e5-92b2-fc9ec7c6bbed)
### Steps To Reproduce

1. open blink wallet attachment with the current master
2. type anything in the first field

### Expected behavior

should not throw an exception

**Comment by huumn** [comment]
My bad on this. I should've tested blink after my rebase and mods. I only made sure the form was displaying correctly.

Looking into it now.
