### ISSUE TITLE
New local sending wallets aren't seen by other tabs until reload

### ISSUE THREAD

**Issue by ekzyis** [stackernews/stacker.news#1550]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

If I configure a new sending wallet, it is not used until I refresh the page.

### Screenshots

https://github.com/user-attachments/assets/2a11a836-f355-4307-8527-fb73d8b9cb96

### Steps To Reproduce

1. Configure sending wallet in one tab
2. Try to zap in other tab
3. You get a QR code

### Expected behavior

The wallet I just configured is automatically used.

### Additional context

~This is most likely caused by saves not triggering `useWallet` to return the updated wallet.~ It is not, it's caused by different tabs.

**Comment by huumn** [comment]
is this with or without device sync?

**Comment by ekzyis** [comment]
without

**Comment by huumn** [comment]
I'm unable to reproduce and your video is 404ing for some reason.

**Comment by ekzyis** [comment]
Ohhh, didn't notice that. Makes sense!
