### ISSUE TITLE
Timeout wallet payments

### ISSUE THREAD

**Issue by huumn** [stackernews/stacker.news#1558]
Wallet payments can fail silently, e.g. the NWC consumer doesn't respond to a payment request, in which case we will wait until the invoice expires (10 minutes in most cases) - which is way too long. Stackers will assume we're unresponsive.

It's not as simple as timing out and displaying a QR code for the same invoice however. It's possible the QR code is paid and then the NWC consumer comes online and attempts to pay the same invoice. This is dangerous because once the QR code is paid, the preimage for the payment has been revealed, and the sats in the second payment can be stolen by nodes along the route that know the preimage.

To timeout safely, we'll want to cancel the original invoice, then generate a new invoice to display in the QR.

**Comment by riccardobl** [comment]
this is solved by https://github.com/stackernews/stacker.news/pull/1523

**Comment by ekzyis** [comment]
Can you extract the commit from #1523 in a separate PR? #1523 already has a lot of changes and we can merge a smaller PR faster.

**Comment by riccardobl** [comment]
> Can you extract the commit from #1523 for this into a separate PR if it doesn't mess/isn't related too much with the other code in it? #1523 already has a lot of changes and we can merge and review a smaller PR faster.

I'll see what i can do, but the fix is a side effect of the different retrying mechanism. Anyway i am cleaning up the pr, so maybe we'll end up with fewer changes

**Comment by riccardobl** [comment]
correction: my PR fixes only this part
> This is dangerous because once the QR code is paid, the preimage for the payment has been revealed, and the sats in the second payment can be stolen by nodes along the route that know the preimage.

the use-paid-mutation calls retryPaidAction that, with the changes in the PR, cancels the previous invoice and returns a new one for the QR code.

However it doesn't change the long timeout

**Comment by ekzyis** [comment]
> Wallet payments can fail silently, e.g. the NWC consumer doesn't respond to a payment request, in which case we will wait until the invoice expires (10 minutes in most cases) - which is way too long. Stackers will assume we're unresponsive.

Since this ticket was created because of an unresponsive territory payment, can't we control the timeout simply via low invoice expiration for invoices that pay SN?

We can't do this for p2p payments because we don't control the outgoing invoice and expiry of incoming invoice must be higher and have a buffer. But stackers don't wait for these payments since they are handled in the background so I think failing fast is less important.

**Comment by huumn** [comment]
We can. This issue is mostly about falling back to QR after a reasonable amount of time, so I'm not sure how that fits into what you're saying.

For this case, we probably want to throw a `TimeoutError`, cancel the original invoice, and popup a QR with a fresh invoice.

**Comment by ekzyis** [comment]
> This issue is mostly about falling back to QR after a reasonable amount of time, so I'm not sure how that fits into what you're saying.

the payment should fail automatically if the invoice expires because we're polling for the payment next to it
