### ISSUE TITLE
Boost icon can get stuck in hover style

### ISSUE THREAD

**Issue by ekzyis** [stackernews/stacker.news#1566]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

If you move your cursor fast enough over the boost icon, it can get stuck in the hover style until you hover over it again.

This has been annoying me for a while but now I found out how to reproduce it.

### Video

https://github.com/user-attachments/assets/c14e8190-0c18-4bd0-812e-aae3d204c03c

### Steps To Reproduce

See video. The right speed is key.

### Expected behavior

Boost icon can not get stuck in hover style

**Comment by AndreaDiazCorreia** [comment]
Can I took this?

**Comment by huumn** [comment]
Yep

**Comment by ekzyis** [comment]
Interestingly, this doesn't happen with the zap icon.

**Comment by AndreaDiazCorreia** [comment]
I think I solved the issue; here is the PR for you to review and test. [fix: hover on boost button (Issue 1566)](https://github.com/stackernews/stacker.news/pull/1605)
