### ISSUE TITLE
Uploaded videos don't load on Safari iOS

### ISSUE THREAD

**Issue by ekzyis** [stackernews/stacker.news#1569]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

See title

### Screenshots

Safari PWA on iOS:

![signal-2024-11-10-162050](https://github.com/user-attachments/assets/a1ab6793-d32b-47a4-b42c-64001241e537)

Brave on Desktop:

![2024-11-10-162006_1920x1080_scrot](https://github.com/user-attachments/assets/711816cf-a867-474c-8cf5-7d646b51c084)

### Steps To Reproduce

1. Upload video from other device because of #1568
2. View item on Safari iOS

(not confirmed)

### Expected behavior

Video is visible on Safari iOS

**Comment by huumn** [comment]
It's likely a CSS issue. Safari is uniquely glitchy when it comes to video.

**Comment by Soxasora** [comment]
> It's likely a CSS issue. Safari is uniquely glitchy when it comes to video.

I'm exploring also this issue, **you're right it is indeed a CSS issue**, specifically `text.module.css` at line 187
```
.p:has(> .mediaContainer) .mediaContainer
{
    display: flex;
    width: min-content; /* Safari doesn't like this */
    max-width: 100%;
}
```

This actually works on Safari for Mac
![Safari loading the video](https://github.com/user-attachments/assets/b325f53f-bb7e-4075-9dbb-c3e45e108384)


But on Safari for iOS (or PWA) the story is much different, it tries to render all the possible resolutions of the image that actually is a video, in fact `media-or-link.js` tries to load the video as img before creating a video element that only then will be populated with the video data.
I'm still investigating, for now I'm battling hydration errors as testing PWAs is its own hell
