### ISSUE TITLE
[BUG] NWC attached wallet is not working on mobile

### ISSUE THREAD

**Issue by ch0k1** [stackernews/stacker.news#1578]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I am primarily using SN as installed PWA on my mobile device and I noticed a strange issue reproducible only on mobile (the same scenario works fine on desktop). 

**Reproducibility rate:** Persistent

**Prerequisites:** (The prerequisites described  below should be met for both zap and create post cases provided below)

1. NWC wallet should be attached for the testing account with the following configuration:
    - Desired balance - 0;
    - Max fee rate - 1%;
    - Max fee total - 0;
2. Your account balance should be less than the default zap amount configured in account's [settings](https://stacker.news/settings) or post amount if you decide to reproduce the issue via creating a new post.

### Screenshots

On mobile:

https://github.com/user-attachments/assets/fe4ea6e7-893e-401a-ae96-b4d3fb300f58

On desktop:

https://github.com/user-attachments/assets/a3b775a1-7808-4cd9-8745-6f4d97d2ba7d

### Steps To Reproduce

Zapping case:

You start on SN home page

1. Zap any post you choose

Create post case:

You start on SN home page

1. Click Post button to create a new post;
2. Pick any territory;
3. Pick any post type;
4. Fill in the required post fields (title, url, text)
5. Click post button

### Expected behavior

Zapping case:

Zap post by paying it using the attached NWC wallet's balance.

Create post case:

Create a new SN post in the selected territory by paying its fee using the attached NWC wallet's balance.

### Logs

Log 1

<img width="556" alt="Screenshot 2024-11-11 at 20 19 58" src="https://github.com/user-attachments/assets/b7200625-80c6-4d15-877e-e8b69ae1943d">

Log 2

<img width="639" alt="Screenshot 2024-11-11 at 20 20 25" src="https://github.com/user-attachments/assets/92d86957-8a9e-45f6-8d7c-53564148d7ed">

Log 3

<img width="773" alt="Screenshot 2024-11-11 at 20 20 52" src="https://github.com/user-attachments/assets/c5ab71da-144d-448c-a87e-99b175f418c6">

### Device information

**Device:** Google Pixel 6 Pro
**OS:** Android 15 (5th November 2024)
**Browser:** Firefox for Android (org.mozilla.firefox) v.132.0
**SN version:** PWA based on [c31cf97](https://github.com/stackernews/stacker.news/commit/c31cf9)

**Comment by huumn** [comment]
When you go to `nwc` on mobile does it have anything set for `connection`?

**Comment by ch0k1** [comment]
I don't know what and how it happened but you are 100% right - for some reason the NWC sending `connection` secret was missing on mobile (and present in desktop) which obviously was the problem. My bad, so sorry for the false positive! 

**P.S.:** Maybe this misunderstanding could be a motivation for an easy to implement feature request which would be when saving settings on one device the result to be synced between different devices.

**Comment by ekzyis** [comment]
We have this, we call it [device sync in your settings](https://stacker.news/settings/passphrase) and it is mentioned on the wallet page if you enter sending credentials:

![2024-11-11-231302_1920x1080_scrot](https://github.com/user-attachments/assets/3354562f-1a3c-4be7-9d24-d04caab8717d)
