### ISSUE TITLE
Wallet log cursor exhibits weird behavior

### ISSUE THREAD

**Issue by huumn** [stackernews/stacker.news#1579]
These aren't in the right order:

<img width="869" alt="Screenshot 2024-11-11 at 4 31 29 PM" src="https://github.com/user-attachments/assets/3d57cc5b-d94b-429d-a2e2-f7acbd6662e0">

Also, there should be several 70 sat receives before from `nwc` that aren't appearing (you can tell because `waiting for invoice` is only logged *after* other things are logged. I suspect the dual-cursor logic is faulty and skipping pages/merging pages poorly.

@ekzyis

**Comment by ekzyis** [comment]
Oh that was definitely something I didn't fully test since it looked right but I forgot to make sure at the end / flag it during review.
