### ISSUE TITLE
Add footer menu and search for:  /wallet, /settings, /post 

### ISSUE THREAD

**Issue by cointastical** [stackernews/stacker.news#158]
This capability was added for the 404 page (Issue #143), but there are these three additional pages that also do not have the footer menu and below that, search.

**Comment by ekzyis** [comment]
Search button was moved into header. It's now always there. Closing.

**Comment by cointastical** [comment]
Except Search was only part of the footer that was missing.   

Why would the following not have the same footer as all the other pages?

```
rewards
analytics \ chat \ socials \ rss
faq \ guide \ story \ changes \ privacy

```
https://stacker.news/wallet
https://stacker.news/settings
https://stacker.news/post

**Comment by ekzyis** [comment]
You are right! Reopening and waiting for @huumn opinion

**Comment by huumn** [comment]
We can add them to those pages. I only kept them off those pages because it's kind of A LOT to look at when there's otherwise so little on the page. I'm happy to overruled though.

**Comment by ekzyis** [comment]
I think your explanation makes sense and I don't think that it's very useful to have the footer on these pages.

So I would say thanks to @cointastical for bringing this up, but:

**Comment by ekzyis** [comment]
Ok maybe I should wait for @cointastical opinion again before closing. May come of as rude, lol

**Comment by cointastical** [comment]
That's fine.  It was mostly search that was omitted and now that it is in the header it is no longer omitted.

I was assuming it was simply an oversight, and being AR, was a bit triggered about it not being consistent with the other pages.

All good.  I'll close it.
