### ISSUE TITLE
Filter out paid bounties

### ISSUE THREAD

**Issue by aegroto** [stackernews/stacker.news#1586]
### Describe the problem you're trying to solve

The recent/bounties endpoint does not let remove paid bounties. It could be beneficial to list only bounties that are still open.

### Describe the solution you'd like

Add an additional filtering option to show only unpaid bounties.

**Comment by tsmith123** [comment]
@huumn Managed to do majority of this one but could you decide whether you like the approach in terms of the UI?

Just need to sort the final SQL queries out to know whether a bounty has been paid or not but not quite sure - see PR 🙏
