### ISSUE TITLE
send paid action

### ISSUE THREAD

**Issue by huumn** [stackernews/stacker.news#1591]
Send paid action's (eg account withdrawal) are unique in that no invoice paid to SN's node is generated. Because of this, we can't use the paid action state machine as-is (which transitions invoices and foreign key constrained related records).

To implement paid action's that don't involve an invoice paid to SN, we'll probably want to create another state machine that transitions purely based on `Withdrawl` records (as opposed to `Invoice` records). 

Other than withdrawals, this is need for:
- using SN's UI to pay for non-SN things directly from attached wallets
- recording P2P receives that are NOT proxied

**Comment by huumn** [comment]
Problems:
- (a) We can't determine if non-custodial receives (lnulp) that aren't proxied have been paid. We know the bolt11, but we have no idea whether it's been paid. This means we can't allow notifications and comments for these lnurlp initiated receives we don't know if money actually moved.
- (b) If we allow someone to use their attached wallets to pay for non-SN things using our UI, we have a related problem. We can give the bolt11 to their wallet, but we don't know if the wallet succeeded in paying it UNLESS they return a preimage as part of the payment process (which most of them don't do).

(Withdrawals on the are pretty straightforward on a relative basis.)

--------------

Options:
1. don't support these things
2. support them but don't show if they're paid or not (and put up a disclaimer about it on every such send)
3. support them and proxy these payments anyway
    - for lnurlp (a), the stacker would choose between receiving fee credits OR sats with a 10% proxy fee
    - when a stacker is sending (b), the stacker would pay the outgoing fee upfront

I suspect (3) will be unpopular even if we drop the proxy fee to closely match the network fee, ie 3%. I suspect (2) will be confusing (... and lnurlp shouldn't be shown as a notification).

**Comment by ekzyis** [comment]
> We can't determine if non-custodial receives (lnulp) that aren't proxied have been paid. We know the bolt11, but we have no idea whether it's been paid.

Why not? Most wallets support a method to lookup if an invoice has been paid, examples:

- NWC: [`lookup_invoice`](https://github.com/nostr-protocol/nips/blob/master/47.md#lookup_invoice)
- LNbits: GET /api/v1/payments/\<payment_hash\>
- phoenixd: GET /payments/outgoing/\<id\>

etc.

isn't this what we need here?

same applies to (b)

**Comment by huumn** [comment]
For lnurlp we don't know who paid or with what wallet and don't have creds to make api calls.
