### ISSUE TITLE
Feature request: Show sats earned in all comments for a Post

### ISSUE THREAD

**Issue by cointastical** [stackernews/stacker.news#165]
The purpose would be to help those who are looking to earn from sharing their knowledge to more easily find which posts are worth visiting, and possibly contributing to.

This might be presented as:

_1234 sats \ 12 comments (234 sats) \ @nym 56m_

Discussed on SN here:
https://stacker.news/items/36410

**Comment by ekzyis** [comment]
Has this been done? I don't think I see on SN what has been requested here:

![2023-03-09-184648_606x46_scrot](https://user-images.githubusercontent.com/27162016/224112090-d69d7763-7208-494d-b67d-16ecea15a0c9.png)

The amount of sats all comments received isn't shown.

**Comment by ekzyis** [comment]
Or was this done by adding the amount of sats all comments received inside the post?

![2023-03-09-184857_914x587_scrot](https://user-images.githubusercontent.com/27162016/224112819-cd3f7be6-7265-4a3c-ace1-c6fd700bda0d.png)

**Comment by huumn** [comment]
It was done inside the post. Seemed good enough. You can also hover on the 'X comments' below a post title and it will show the number of sats the comments have earned.

**Comment by ekzyis** [comment]
> You can also hover on the 'X comments' below a post title and it will show the number of sats the comments have earned.

Ahh, totally forgot about that, haha
