### ISSUE TITLE
Cannot Add Image Above Text When Drafting Posts

### ISSUE THREAD

**Issue by sig47** [stackernews/stacker.news#1657]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When attempting to insert an image above text in a post draft, the image is moved below the text. So far as I can tell, the only way to place image above the text is to copy and paste the moved image. 

### Steps To Reproduce

1. Click post, then click discussion
2. enter your post text
3. Select an image and insert it above the post text
4. Click preview
5. Image has now moved to the bottom of the post, below the text.

### Expected behavior

I expected the image to remain at the top of the post draft.

### Device information

OS: Both ubuntu linux desktop and Graphene OS mobile
Browser: Firefox, Vanadium

**Comment by Soxasora** [comment]
https://github.com/user-attachments/assets/19855602-352b-4cd0-b192-d5ea0a9491dc

I can confirm this happens and it only happens when there's no characters behind the cursor, now if you were to put a whitespace before, this doesn't happen. I'll PR a fix
