### ISSUE TITLE
Improvement request: UI for Withdraw to more clearly show distinct choices  

### ISSUE THREAD

**Issue by cointastical** [stackernews/stacker.news#167]
Currently the Withdraw page has the LNUrl withdraw and Lightning Address methods below the Withdraw button. It's easy for someone who doesn't know those exist to overlook those.  I myself had not known Lightning Address withdraw was possible until very recently (and I withdraw frequently).  This undoubtedly happens to others, as evidenced by this post, today:

*[Add withdrawals from stacker.news via Lightning Addresses*
https://stacker.news/items/37290

So this improvement request is to re-orient the options so that it is more clear that there are three wtihdrawal methods supported:

For example, using radio-button select options:

Select withdrawal method:

* Invoice
* Lightning address
* QR Code

(and Invoice can remain default)

Then below that are the fields and button (or whatever is needed) specific to that withdrawal method.

**Comment by versieboer** [comment]
I see it now.  The box asking for an Invoice appears first.  As soon as I saw that, I stopped reading there, knowing that a Lightning Address was not an invoice.

What would help would be a radio button at the top, pre-selected to withdraw via Invoice.  Other radio button options would be "QR code" and "Lightning Address".  When selected, the current "Invoice" field should change accordingly.

**Comment by huumn** [comment]
I guess what we are solving for here is the visibility of withdrawal options. Radio buttons could do it but it's kind of a sucky UI.

**Comment by ekzyis** [comment]
What about simple input with "Enter invoice or LN address ..." as placeholder + QR code next to it?
It should be easy to detect if the user entered an invoice (starts with "lnbc1..." [0]) or LN address

[0] https://github.com/lightning/bolts/blob/master/11-payment-encoding.md#human-readable-part
