### ISSUE TITLE
invite links don't work with pubkey auth?

### ISSUE THREAD

**Issue by huumn** [stackernews/stacker.news#1670]
https://github.com/stackernews/stacker.news/pull/1649#pullrequestreview-2470642114

**Comment by ekzyis** [comment]
I will try to reproduce to make sure it's a bug and wasn't just an error on my side.

**Comment by ekzyis** [comment]
Couldn't reproduce. I think it was related to me using an invite link with a local IP address instead of `localhost` since cookies are only sent when the origin matches.
