### ISSUE TITLE
Consider increasing pathfinding timeout + time_pref when making payments

### ISSUE THREAD

**Issue by huumn** [stackernews/stacker.news#1711]
Someone reached out saying they couldn't receive a large withdrawal. 

I tried manually probing to pay it and it took 24 minutes to find the cheapest route.

Currently we use the default `time_pref = 0` which optimizes for both low fees and reliability. To increase reliability and not timeout during pathfinding, it might be worth setting `time_pref > 0` and/or increasing the pathfinding timeout.

**Comment by ekzyis** [comment]
I think you already did this in 98fae6c9aeafd650996b911dd9d7598e6d8433c9

**Comment by huumn** [comment]
Yep thanks
