### ISSUE TITLE
Disconnecting from device sync in different tab does not unsync local wallets

### ISSUE THREAD

**Issue by ekzyis** [stackernews/stacker.news#1743]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

If I have only a NWC send-only config and disconnect from device sync in a different tab[^1], `unsyncLocalWallets` is called with a stale value that does not contain the config for the NWC wallet so it doesn't unsync them.

[^1]: or maybe I just need to reload the page while I am on /settings/passphrase, not sure

### Screenshots

https://github.com/user-attachments/assets/7d827680-2449-4b9c-870f-0fceb7738bae

<details>
<summary>console.log diff that I used while recording video</summary>

```diff
diff --git a/components/vault/use-vault-configurator.js b/components/vault/use-vault-configurator.js
index 7f087a1c..7853d913 100644
--- a/components/vault/use-vault-configurator.js
+++ b/components/vault/use-vault-configurator.js
@@ -37,7 +37,11 @@ export function useVaultConfigurator ({ onVaultKeySet, beforeDisconnectVault } =
     beforeDisconnectVault?.()
     await remove('key')
     keyReactiveVar(null)
-  }, [remove, keyReactiveVar])
+  }, [beforeDisconnectVault, remove, keyReactiveVar])
+
+  useEffect(() => {
+    console.log('useVaultConfigurator::useEffect::disconnectVault')
+  }, [disconnectVault])
 
   useEffect(() => {
     if (!me) return
diff --git a/pages/settings/passphrase/index.js b/pages/settings/passphrase/index.js
index 79cedac8..4c06098c 100644
--- a/pages/settings/passphrase/index.js
+++ b/pages/settings/passphrase/index.js
@@ -16,11 +16,19 @@ export const getServerSideProps = getGetServerSideProps({ authRequired: true })
 
 export default function DeviceSync ({ ssrData }) {
   const { me } = useMe()
-  const { onVaultKeySet, beforeDisconnectVault } = useWallets()
+  const { wallets, onVaultKeySet, beforeDisconnectVault } = useWallets()
   const { key, setVaultKey, clearVault, disconnectVault } =
     useVaultConfigurator({ onVaultKeySet, beforeDisconnectVault })
   const [passphrase, setPassphrase] = useState()
 
+  useEffect(() => {
+    console.log('DeviceSync::useEffect::beforeDisconnectVault', wallets.find(w => w.def.name === 'nwc').config?.nwcUrl)
+  }, [beforeDisconnectVault])
+
+  useEffect(() => {
+    console.log('DeviceSync::useEffect::disconnectVault', wallets.find(w => w.def.name === 'nwc').config?.nwcUrl)
+  }, [disconnectVault])
+
   const setSeedPassphrase = useCallback(async (passphrase) => {
     await setVaultKey(passphrase)
     setPassphrase(passphrase)
diff --git a/wallets/index.js b/wallets/index.js
index bdf00083..5adc5195 100644
--- a/wallets/index.js
+++ b/wallets/index.js
@@ -160,6 +160,7 @@ export function WalletsProvider ({ children }) {
   }, [wallets, localWallets, removeLocalWallets, settings])
 
   const unsyncLocalWallets = useCallback(() => {
+    console.trace('unsyncLocalWallets::', wallets.find(w => w.def.name === 'nwc').config?.nwcUrl)
     for (const wallet of wallets) {
       const { clientWithShared } = siftConfig(wallet.def.fields, wallet.config)
       if (canSend({ def: wallet.def, config: clientWithShared })) {
@@ -191,6 +192,8 @@ export function WalletsProvider ({ children }) {
     }
   }, [setWalletPriority, me?.id, reloadLocalWallets])
 
+  console.log('WalletsContext.Provider::wallets', wallets.find(w => w.def.name === 'nwc').config?.nwcUrl)
+
   // provides priority sorted wallets to children, a function to reload local wallets,
   // and a function to set priorities
   return (
```

</details>

### Steps To Reproduce

1. Attach NWC send-only in tab 1
2. Enable device sync in tab 2
3. Disable device sync in tab 2
4. You now have an empty enabled NWC wallet

### Expected behavior

NWC wallet still contains send-only config but stored locally again (as it was before device sync was enabled)

### Additional context

I believe it is related to `beforeDisconnectVault` missing as a effect dependency here:

https://github.com/stackernews/stacker.news/blob/e4ca2d6e07c8f1ccf89ef352f66d214e465f3294/components/vault/use-vault-configurator.js#L35-L40

but when I add it, I get

> vault key hash mismatch, clearing local key f5df622c85a4c3043e3d8bd46fcc890195ef198bdd1069ffb76d6e60211ce632 !=

when I try to enable device sync and am immediately disconnected because it seems like this means this effect is run immediately on enable:

https://github.com/stackernews/stacker.news/blob/6ad7a3cf608699941313ee5def27af715b04ecd5/components/vault/use-vault-configurator.js#L42-L62

before the vault key is updated

**Comment by huumn** [comment]
Hmmm yeah that dependency relationship needs to be refactored

**Comment by huumn** [comment]
Oh I think the solution is updating the apollo cache such that `me.privates.vaultKeyHash` is set when we `set('key', vaultKey)` in `setVaultKey`.
