### ISSUE TITLE
new comment indicator shows after I leave a new comment

### ISSUE THREAD

**Issue by huumn** [stackernews/stacker.news#1754]
I thought we previously had an issue for this, but maybe not. Regardless, this is still an issue. I think `useItemSubmit` forgot to update the time.

**Comment by Soxasora** [comment]
I was commenting around SN to test this, it seems that it happens **only** in prod.
I followed cache updating via Apollo devtools and lastCommentAt gets updated correctly when I create a new comment

**Comment by huumn** [comment]
Ah this is happens only for non-custodial comments afaict, because `lastCommentAt` is set to `now()` in `onPaid` which runs asynchronously in another tx after the item is created in `perform`. 

The solution would probably be to set `lastCommentAt = GREATEST(lastCommentAt, comment.created_at)`.
