### ISSUE TITLE
Request: Perform decode on certain Link shortener services, such as Twitter's T.co 

### ISSUE THREAD

**Issue by cointastical** [stackernews/stacker.news#179]
I commonly see Link posts that are for the T.co URL that Twitter generates when there is a URL in the text of a Tweet.   This has two issues, ... firstly, SN's dup detection doesn't know about the underlying URL for prior Link posts that had the T.co, and thus won't produce a Dup warning.   And secondly, there is value when browsing SN posts provide by seeing the domain of the for a Link post -- such that I might decide to click (or to not click) based on that domain.

So the resolution could be as simple as having the javascript in /post replace the T.co link with the underlying URL, and display a flash message saying that the T.co was replaced.

But I could see some instances where the T.co is simply more appropriate.  Like if it is to a URL for a Google Translate link, for example, which is like two hundred characters in length.  So I don't know if disallowing T.co and replacing it is the right solution.

There are other link shortener services as well ... e.g., LinkedIn has them (which do not necessarily go to a Linked In page), Bitly, TinyURL, etc.    So I don't know whether any of these also should get decoded.   I don't see them often on SN, but I am seeing T.co somewhat frequently (e.g., appearing daily, nowadays).

**Comment by huumn** [comment]
Fixed locally.
