### ISSUE TITLE
The optional toogle to disable lightning animation.

### ISSUE THREAD

**Issue by DMantis** [stackernews/stacker.news#182]
For me continuous lightning strikes animation causes a bit of a headache and stops from staying on website. I believe I'm not the only person with such perception of animations.

Would be nice to have an option toggle like with dark/bright modes to disable/enable it to improve accessibility.

**Comment by jnmclarty** [comment]
Should this option be only toggleable for signed in users?  

Or would it be available to the unauthenticated lurkers too?  

I can see pros and cons to both.  

Follow up, has anybody started work on this yet?

**Comment by ekzyis** [comment]
Looking at the PRs, I don't see that anyone has started working on this yet.

I think yes, this can be available for unauthenticated lurkers to. Just set it in local storage. I don't see security implications. So no reason why not

**Comment by huumn** [comment]
The lightning strikes happen randomly for logged out users. For logged in users it's only when tipping.

**Comment by huumn** [comment]
Used localstorage. Can be toggled at bottom of page
