### ISSUE TITLE
Wrong amount for earnings in profile and 404 when clicking on row

### ISSUE THREAD

**Issue by ekzyis** [stackernews/stacker.news#186]
I noticed the following bug:

On the profile page, the stacked amount for earnings is displayed wrong:

![2022-08-15-210239_1920x1080_scrot](https://user-images.githubusercontent.com/27162016/184700614-fa04a42e-66d1-4764-9a4e-799d5a4267c1.png)

I did not receive so many sats. I think this is the total amount of sats that was earned by everyone in this round.

Also, when clicking on that row, it leads to a 404 page at https://stacker.news/items/76326:

![2022-08-15-210312_1920x1080_scrot](https://user-images.githubusercontent.com/27162016/184700795-fd9a7dc1-212b-45c8-b631-c7f22899a77a.png)

Not sure where it should lead to, but I think a 404 is not intended :smile:

**Comment by ekzyis** [comment]
I would be willing to look into this if you can confirm these are bugs and not intended :smile:

**Comment by huumn** [comment]
Those are decimals not commas! You stacked ~1 sat, then 2, then 3. The 404 page is definitely an error though.

**Comment by ekzyis** [comment]
Ah ohh, right, Lightning support sub satoshi amounts, forgot about that :smile:

**Comment by ekzyis** [comment]
Closing this since you already removed the 404 link in https://github.com/stackernews/stacker.news/commit/03723bd5ee71438b2aab18811256cfa1de2de127
