### ISSUE TITLE
Image IDs should be hashes.

### ISSUE THREAD

**Issue by davisv7** [stackernews/stacker.news#187]
When uploading profile pictures, the image IDs should be hashes to prevent easy enumeration. Currently, the website can be spammed with expensive requests for these images a la:

    import random
    import requests

    while True:
        requests.get(f"https://snuploads.s3.amazonaws.com/{random.randint(0, 586)}")

**Comment by huumn** [comment]
Why do we need to prevent enumeration?

**Comment by huumn** [comment]
Closing. Not going to do this without good reason - images are public.

Even if we did have private images, we'd use authentication - security through obscurity is bunk.
