### ISSUE TITLE
Feature request: Strip tracking info from links such as Tweets

### ISSUE THREAD

**Issue by cointastical** [stackernews/stacker.news#190]
As described in the SN post [a privacy tip](https://stacker.news/items/61466), and [elsewhere](https://stacker.news/items/43142), Twitter has added tracking info by default to Tweets.

This lets Twitter (and authorities that have access to Twitter data) tie an SN account to a Twitter account owner. 

My feature request is for Link posts that are for a Tweet to strip out anything trailing the status id.

e.g., 

`https://twitter.com/[twitter screen name]/status/1539956448893059073?[STRIP ALL THIS]`

would be stripped to just:

`https://twitter.com/[twitter screen name]/status/1539956448893059073`

This privacy-enhancing feature of stripping the link might also apply considered for Tweets in Description posts, as well as in Tweets in Comment replies.

Additionally, there would be links to content on other platforms (e.g., Facebook, with ?fbclid=, or links with UTM tracking) that have the same privacy issue.  I don't see FB links much on SN, but Link posts with the UTM tracking info is common.   This privacy enhancement of links is an area I've not researched much at all but there appears to be a decent attempt at it  with this docs.clearurls.xyz project.

I estimate from general observation that removing the tracking info on Tweets alone would cut at least half the instances of tracking data shared on SN.

**Comment by huumn** [comment]
Most sites do this unfortunately and users who post don't seem to notice/care. I would like to just remove all query parameters from urls but some sites rely on them (hacker news and bitcointalk memorably ... but there are probably others).

I guess I could make an exception for twitter and known 'trackers.'
