### ISSUE TITLE
SN experience can be improved with Alby

### ISSUE THREAD

**Issue by bitcoinuser** [stackernews/stacker.news#191]
Hi,

Please see this issue and comment: https://github.com/getAlby/lightning-browser-extension/issues/1361#issuecomment-1237782703

**Comment by huumn** [comment]
Fixed locally to specify max amount. I'll push in the next few days.

You do have to pay routing fees when withdrawing from SN though. Alby doesn't allow you to specify how much you wish to pay in fees so we default to 10 sats. So you'll be able to withdraw most of your balance but not all.
