### ISSUE TITLE
'docker-compose up --build' ends in error

### ISSUE THREAD

**Issue by liviu-ln** [stackernews/stacker.news#193]
The displayed error is:

app    | prisma:error 
app    | error: Error validating datasource `db`: the URL must start with the protocol `postgresql://` or `postgres://`.
app    |   -->  schema.prisma:6
app    |    | 
app    |  5 |   provider = "postgresql"
app    |  6 |   url      = env("DATABASE_URL")
app    |    | 
app    | 
app    | Validation Error Count: 1
app    | event - build page: /500
app    | wait  - compiling...
app    | event - compiled successfully
app    | error - ApolloError: 
app    | Invalid `prisma.queryRaw()` invocation:
app    | 
app    | 
app    |   error: Error validating datasource `db`: the URL must start with the protocol `postgresql://` or `postgres://`.
app    |   -->  schema.prisma:6
app    |    | 
app    |  5 |   provider = "postgresql"
app    |  6 |   url      = env("DATABASE_URL")
app    |    | 
app    | 
app    | Validation Error Count: 1
app    |     at new ApolloError (/app/node_modules/@apollo/client/errors/errors.cjs.js:34:28)
app    |     at /app/node_modules/@apollo/client/core/core.cjs.js:1575:47
app    |     at both (/app/node_modules/@apollo/client/utilities/utilities.cjs.js:981:53)
app    |     at /app/node_modules/@apollo/client/utilities/utilities.cjs.js:974:72
app    |     at new Promise (<anonymous>)
app    |     at Object.then (/app/node_modules/@apollo/client/utilities/utilities.cjs.js:974:24)
app    |     at Object.next (/app/node_modules/@apollo/client/utilities/utilities.cjs.js:982:49)
app    |     at notifySubscription (/app/node_modules/zen-observable/lib/Observable.js:135:18)
app    |     at onNotify (/app/node_modules/zen-observable/lib/Observable.js:179:3)
app    |     at SubscriptionObserver.next (/app/node_modules/zen-observable/lib/Observable.js:235:7) {
app    |   graphQLErrors: [
app    |     Error: 
app    |     Invalid `prisma.queryRaw()` invocation:
app    |     
app    |     
app    |       error: Error validating datasource `db`: the URL must start with the protocol `postgresql://` or `postgres://`.
app    |       -->  schema.prisma:6
app    |        | 
app    |      5 |   provider = "postgresql"
app    |      6 |   url      = env("DATABASE_URL")
app    |        | 
app    |     
app    |     Validation Error Count: 1
app    |         at cb (/app/node_modules/@prisma/client/runtime/index.js:33822:17)
app    |         at runMicrotasks (<anonymous>)
app    |         at processTicksAndRejections (internal/process/task_queues.js:95:5)
app    |         at async items (webpack-internal:///./api/resolvers/item.js:253:25)
app    |         at async Promise.all (index 0) {
app    |       locations: [],
app    |       path: [Array]
app    |     }
app    |   ],
app    |   clientErrors: [],
app    |   networkError: null,
app    |   extraInfo: undefined,
app    |   page: '/'
app    | }

**Comment by liviu-ln** [comment]
Looks to be an issue with older versions of docker-compose.
[https://stackoverflow.com/questions/71736148/prisma-error-validating-datasource-db-the-url-must-start-with-the-protocol](https://stackoverflow.com/questions/71736148/prisma-error-validating-datasource-db-the-url-must-start-with-the-protocol)

My version is 1.25.0 and as recommended by the StackOverflow article, just removing the quotes made it work:

`# prisma db url
-DATABASE_URL="postgresql://sn:password@db:5432/stackernews?schema=public"
+DATABASE_URL=postgresql://sn:password@db:5432/stackernews?schema=public
`

**Comment by huumn** [comment]
Thanks! I need to update the docker environment
