### ISSUE TITLE
Feature request: Add Boost capability to comment replies

### ISSUE THREAD

**Issue by cointastical** [stackernews/stacker.news#194]
This request is to permit a person to "boost" their own comment reply (similar to how a person can boost their own Post).

Discussed in an SN Daily post [here](https://stacker.news/items/70570).

**Comment by ekzyis** [comment]
Example use case:

I would have loved to boost [this comment](https://stacker.news/items/188093) such that more users see it.
But afaik, this feature is more meant as a boost within the post. But I wanted every user on SN to see that comment.

I posted a link to the comment instead: https://stacker.news/items/188097

**Comment by huumn** [comment]
That comment is an interesting use case because it's not top level. 

If you boosted that comment, should it boost the whole comment tree that it's a part of?
