### ISSUE TITLE
Add 'delete' next to 'edit' while comment is new

### ISSUE THREAD

**Issue by ekzyis** [stackernews/stacker.news#195]
Currently, if a user replies to the wrong comment, he is not able to delete the comment afterwards in any way.

I think adding a 'delete' button next to the 'edit' with its countdown after which 'edit' is removed would solve this problem. The countdown should also apply to the 'delete' button.

**Comment by ekzyis** [comment]
I would be happy to work on this. I think I already have a general idea how this could work. Just need to see how 'edit' is implemented.

**Comment by ekzyis** [comment]
Noticed another use case: I accidentally replied to my own comment instead of using the still available edit button here: https://stacker.news/items/70923

**Comment by huumn** [comment]
Delete is a bit tricky. For instance, should you be able to delete a post/comment that someone has tipped you on? Perhaps if you refund them? How about if someone has commented on it?

**Comment by ekzyis** [comment]
Ah, I see.

But doesn't the same apply to "edits"? You could edit a comment and just completely change your opinion. Then it also wouldn't make sense to keep the tips or if someone replied to you, would it?

But yeah, good point. I didn't think about this before.

Refunding seems to make sense. This should be a edge case anyway that someone already tips you while you can still edit/delete a comment. Or at least not the majority of times.

However, if someone replied to you, I think deleting a post is a bit more "critical". I could see the possibility of people deleting their comments (while they are still able to) if someone else "successfully" called them out on something / invalidated their opinion and they want to save face by deleting the comment.

This seems - at least to me - a bit more "unethical" than simply editing a comment after someone replied to you.

Maybe it should always be possible for a reply to point to the actual comment it replied to? However, I image this would be vastly more difficult to implement and storage would double for every reply (as far as I can see now).

**Comment by huumn** [comment]
I definitely think we eventually want deletes. Just need to figure out all the corners.

**Comment by ekzyis** [comment]
Another idea would be to mark comments as "unconfirmed" until they are no longer to able to be deleted. Then users who reply know that the comment may get deleted and they will be refunded if the comment gets deleted (potential tip + 1 sat cost for the reply). This could be visualized by making the comment more transparent or just exposing the timer to all users for example.

This is inspired by unconfirmed transactions in bitcoin.

**Comment by ekzyis** [comment]
I think this can be closed since there are now deletes

**Comment by huumn** [comment]
YEP!
