### ISSUE TITLE
Provide option to clear withdrawal invoices

### ISSUE THREAD

**Issue by huumn** [stackernews/stacker.news#201]
https://stacker.news/items/75823

**Comment by huumn** [comment]
I think the ultimate solution is

1. an option to automatically delete withdrawal invoices after X amount of days
2. an option to delete each invoice on a case by case basis 

We can keep the amount, etc, but should delete the bolt11 so the receiver's privacy is maintained

**Comment by rleed** [comment]
I'd like to implement this in the following suggested way, subject to y'alls input:
- [ ] add a checkbox option to the user settings to "auto forget withdrawal invoices after 7 days" (pic below)
- [ ] add a daily job in the worker thread to perform the selected deletions
- [ ] on the invoice detail page for withdrawal invoices, add a link to forget the invoice (pic below)
- [ ] when manually deleting the invoice, pop up a warning similar to existing warnings (pic below)

![image](https://github.com/stackernews/stacker.news/assets/101502594/57950ee6-9e8d-401a-b169-4652237f8792)

Is 7 days the right optimum? (I just guessed at a reasonable number.) Alternatively, we could put a drop-down option list with several options. But do you think it is necessary?

![image](https://github.com/stackernews/stacker.news/assets/101502594/adf089cf-b7f3-4e47-b3a6-a85cf2deef3f)

First I thought about putting a trash button directly on the wallet history page, but maybe it is better to have this link here? What do you think?

![image](https://github.com/stackernews/stacker.news/assets/101502594/3247049a-e95e-4afb-89b9-f4fc3935fc79)

This is an existing warning...the wording could be adapted slightly if desired, but I guess it fits already.

**Comment by huumn** [comment]
I think everything in your approach is good. 

7 days seems like the right length of time too
