### ISSUE TITLE
Weird hitbox to open notifications in new tab

### ISSUE THREAD

**Issue by ekzyis** [stackernews/stacker.news#202]
Hey, I noticed that I can only open notifications in a new tab if I click directly on the title. See screenshots.

Only when the title is selected, the context menu provides an option to "open in new tab".

This means that CTRL+MouseLeft also does only work when clicking on titles, not on the whole row as one may expect.

![2022-10-04-183956_1920x1080_scrot](https://user-images.githubusercontent.com/27162016/193878018-389bffbf-d789-4e15-a5f9-38d9f4db2106.png)
![2022-10-04-183950_1920x1080_scrot](https://user-images.githubusercontent.com/27162016/193878027-2687face-d236-4cd6-a903-2e9abd4d2364.png)

**Comment by huumn** [comment]
The main blocker to this right now is we're not allowed `a` tags inside of `a` tags.

**Comment by benalleng** [comment]
Changing element positioning like playing with `a` tags and negative margin magic could overlay a 'right-clickable' notifcation this would only solve this problem for posts but not replies or any other notification where the title is not a link. what if instead we added a `ctrl + click` event listener to handle new tab functionality?

definitely a more elegant way to solve this but here is what i mashed up
```
        if (e.ctrlKey) {
          e.preventDefault()
          // Your code here for when shift + click occurs
          console.log('Ctrl + Click detected!', as + "?commentId=" + nid.substring(5, 11));
          const anchor = document.createElement('a');
          // hard coded comment Id but I just wanted to see that it was possible to do the comment highlighting like mentioned above
          anchor.href = as + "?commentId=" + nid.substring(5, 11)
          anchor.target = '_blank';
          anchor.click();
        } else {
        router.push(href, as)
```

**Comment by huumn** [comment]
That's a clever solution and is way better than nothing

**Comment by benalleng** [comment]
Circling back to the issue, I am planning on closing my PR as it stands. It works well but I'm not sure it passes muster with usefulness. Seeing as it is still not a link I just don't think the addition of a pop-up blocked warning + no indication that a `ctrl + click` actually should do anything is useful. 
I do think this is a nice feature but I think we should attempt to use links instead.
doing a little exploring on the site which shall not be named (reddit) as their hompage uses links within links on these cards

The whole card is a link and the subreddit  r/whatever in the top left is also a link
![image](https://github.com/stackernews/stacker.news/assets/108441023/3bcfafbb-8a9d-4792-89bd-80a1427bd9bc)

**Comment by huumn** [comment]
Sounds good. Other than conditionally using the `a` tag on item links, the next best thing might be some `position: absolute` hack: https://bdwm.be/html5-alternative-nested-anchor-tags/
