### ISSUE TITLE
Dup detection to find mobile.twitter.com   

### ISSUE THREAD

**Issue by cointastical** [stackernews/stacker.news#208]
Currently SN's dup detection doesn't prevent duplicates when one Link Post is using the link for "mobile" and the other Link Post does not.
 
Twitter users sharing a link for a Tweet from a mobile will generally have a link with the "mobile" subdomain:
https://mobile.twitter.com/handle/status/1234567890123456789

Whereas from the browser without mobile, the link for the Tweet will be without that subdomain:
https://twitter.com/handle/status/1234567890123456789

Today's example of that occurring on SN are with Link Post item [87683](https://stacker.news/items/87683) which was later posted again (i.e., a duplicate) with Link Post item [87718](https://stacker.news/items/87718).

This request is to make it so that when creating a Link Post, SN will detect a duplicate regardless of whether or not the mobile subdomain exists in the Link for the earlier Post or in the Link for the Post being attempted.  Or, I think ... preferably, SN simply strips off the mobile subdomain before saving the Link Post, so that any Tweets shared as Link Posts on SN (going forward) would never have the mobile prefix.   Doing this would also fix another (unreported) issue in that Twitter embed does not occur when the Link for the Tweet has the mobile subdomain.

But if not, ... then even just simply looking for both (with, and without, the mobile subdomain) when doing the dup detection would be a suitable solution.

**Comment by ekzyis** [comment]
I think this is similar to #169 and thus would be fixed by #215

**Comment by huumn** [comment]
Yep fixed for all subdomains locally.
