### ISSUE TITLE
Dup detection not working for link which includes "+" (for a space)

### ISSUE THREAD

**Issue by cointastical** [stackernews/stacker.news#209]
When a Link Post is for a URL in which the "+" (plus) character is used (as an encoding for " " / space character), SN's dup detection will not properly detect if a Link Post for that URL already exists.

Example: https://Test.link/has+space

This generally is seen with CMS / fileshare systems (e.g., Google Drive, or DropBox) where the filename has a space in it, and thus the webserver will encode that with either a "%20" (percent encoding) or a "+" as a substitute for the space.

SN's dup detection does properly detect the case where the "%20" (space) encoding is used:  
https://Test.link/has%20space

So the request is to have SN's dup detection recognize when a prior Link Post exists for this case where there is a "+" in the link.  

I suppose there could be the situation where one user posts a link with the "%20" encoding, and another posts a link that retrieves the same content, but is using the "+" encoding, but I would assume that would be so rare that SN wouldn't need to try to treat them both as being identical.  But I just wanted to point out a second potential use case that SN's dup detection could address. Also, there's the situation where a "+" is used in a query string (e.g., ?search=has+space), which could complicate the approach of equating "+" with "%20" for dup detection, but I haven't thought that through, so maybe it would not.

**Comment by huumn** [comment]
Have we seen this in practice much?

**Comment by cointastical** [comment]
Nearly every PDF shared from a company that uses Squarespace (Blockware Intelligence, Arcane Research, Reflexivity Research, and numerous others) has the "+" in the URL.

https://stacker.news/search?q=url%3Asquarespace.com

Same thing with Bynder (used by Coinbase) and AmazonAWS but so far I see only a single document shared on SN for each of those, so far.

So while a document shared where the URL has a space character is something very common on SN, most CDN services encode that with "%20" which SN properly accommodates, but less frequently used is a "+" to encode a space.   But of those using "+", SN will not detect any as being a duplicate.

As far as the frequency of a document with a "+" encoding for space, SN sees that at a rate of about one time per week (at current usage levels).

So this is not a priority issue, for sure.

**Comment by huumn** [comment]
Okay, we'll just keep it open in the meantime.

**Comment by rleed** [comment]
(I'll take a look at this)
