### ISSUE TITLE
When Search criteria is a link, results do not include Link Posts for that link 

### ISSUE THREAD

**Issue by cointastical** [stackernews/stacker.news#212]
This is a request to make it so when searching for a link, that any Link Posts that have that link are included in the search results.

Providing this will help to lessen the number of duplicates, as currently the only way to know if a link already has been posted is to attempt to create a Link Post (and look for the "dup" response).

This might even gain functionality if the search criteria does not need to be an exact match to find results.  For instance, if I were to search https://bitcoin.org it would be nice if the search results included all Link posts that included https://bitcoin.org.   Probably wouldn't hurt to strip the scheme (https:// and http:// ) from the user input when performing the search to avoid the case where the Link post was for one scheme and the user is searching the other scheme.    Similarly, the search for a link should not be case sensitive, otherwise matches will be missed (similar to what was described with Issue #142).

**Comment by huumn** [comment]
You can search for urls in link posts with `url:bitcoin.org` and for post from nyms with `nym:cointastical`

In the future perhaps I'll make this better and less "hidden," like automatically detecting urls rather than requiring markup. But this was easiest to do for now.
