### ISSUE TITLE
Feature request: Add the Related drop-down for New Posts (before submitting)

### ISSUE THREAD

**Issue by cointastical** [stackernews/stacker.news#218]
When posting, SN will warn if the Link for a Link Post has already been submitted, however that is for a specific article or media item.  If I wish to avoid posting an article for a topic where another article has already been posted, I'ld like to know that before submitting my article.  For instance, if I am to post a CoinDesk article, but an article from BItcoin Magazine for the same topic had already been posted on SN, I'ld like to somehow see that the Bitcoin Magazine article was already shared.

I find that if, after I post, I then use the Related drop-down for my post that the drop-down does an excellent job.  My request here is that I be able to see what the "Related" would show even before submitting my Post (whether it be a Link Post or a Discussion Post).

Using my CoinDesk article scenario above, after clicking the Related and seeing the Bitcoin Magazine article, I would then be more likely to abstain from posting the CoinDesk article and instead be upvoting (and/or commenting on) the existing Bitcoin Magazine article.

So effectively, this would fall under dup detection, but for topic dups, and not just link dups.

**Comment by huumn** [comment]
Fixed locally.
