### ISSUE TITLE
Youtube dup detection finding random matches with other Youtube links

### ISSUE THREAD

**Issue by cointastical** [stackernews/stacker.news#222]
An attempt to post the following link:
https://youtube.com/watch?v=e9XqnDDl14Q

results in the following to be shown as dupes:
https://youtube.com/watch?v=CX1F4BHhkQs
https://youtube.com/watch?v=WqDvsbElFXg
https://youtube.com/watch?v=wTC31ZI6QM4

I can't account for why this would occur.   Incidentally, this issue does not persist when the link has the www. subdomain.

**Comment by huumn** [comment]
It's probably the regex for youtube links. Looks like I don't check for youtube.com as a youtube domain: https://github.com/stackernews/stacker.news/blob/a92172ab9b32cabbc63335b8d4b5ab2f81a46df2/api/resolvers/item.js#L475

**Comment by huumn** [comment]
Fixed this locally
