### ISSUE TITLE
Improve privacy by not accessing Coinbase API directly

### ISSUE THREAD

**Issue by cointastical** [stackernews/stacker.news#223]
It appears Coinbase is getting my IP address every time I access Stacker News.

Specifically a GET request is occurring for the "spot" price:
https://api.coinbase.com/v2/prices/BTC-USD/spot

I think this could be handled by proxy where the API request from the browser goes to a Stacker.News endpoint, and then Stacker.News sends an API request to Coinbase.

**Comment by huumn** [comment]
True. 

I think Coinbase has API rate limits by IP.  If we want to proxy them, we'll need to cache the price on our servers to not go over their limits.

**Comment by ekzyis** [comment]
Another post related to this: https://stacker.news/items/119700

Following ideas were mentioned:
1. only fetch price when required (the user is not using moscow time)
2. add "disabled" to fiat currency dropdown in settings which makes only moscow time available

This is unrelated to using a proxy. Using a proxy would still be useful, I think.

**Comment by huumn** [comment]
Proxying is my preferred approach. This prevents IPs leaking for people who also want the price. It's more work though. 

For doing satistics exports for tax purposes, we also need a minute to minute price, so storing prices is something we need to do for that anyway.

I think the way this should work, is we setup a job in the job queue that runs every minute and records the price in a DB table. 

Then on the client for the price widget, we just poll the backend which retrieves the latest price from this DB table.

Given we support multiple currency pairs, we probably want to figure out how to grab all BTC-fiat pairs in a single query and store them all every minute.

**Comment by huumn** [comment]
I think this query basically gives us all their exchange rates `https://api.coinbase.com/v2/exchange-rates?currency=BTC` but it includes shitcoins and not just fiat.
