### ISSUE TITLE
Allow subsatoshi tips

### ISSUE THREAD

**Issue by kristapsk** [stackernews/stacker.news#225]
I see no reason for Stacker News not to allow subsatoshi tip amounts, down to 1 millisatoshi.

![image](https://user-images.githubusercontent.com/4500994/211187403-f4364d3d-2032-417b-b07f-ab3144d2360e.png)

**Comment by huumn** [comment]
Just because we could do something doesn't mean we should.

Why do you want to tip subsatoshis?

**Comment by kristapsk** [comment]
I could use nice amounts for fun, like 10.5 (half of 21), 6.25 (current block subsidy), etc. :) Ofc, not a big deal. But in LN you can pay subsatoshi amounts.

**Comment by huumn** [comment]
I see. We have a lot to work on, and while I agree we *can* do it, I don't think this is a priority. Do you?

**Comment by kristapsk** [comment]
No, definitely not a priority.

**Comment by huumn** [comment]
Cool, thanks for suggesting it regardless!

Going to close it. But we'll reopen it when there's stronger motivation/need for it.
