### ISSUE TITLE
[RSS] `link` should link to linked article, not `guid`

### ISSUE THREAD

**Issue by abetusk** [stackernews/stacker.news#23]
When pulling from the RSS feed, the format for an item is as follows:

```
...
    <item>
      <guid>https://stacker.news/items/1098</guid>
      <title>Lightning Voucher ATM Coming Soon ⚡️🏧</title>
      <link>https://stacker.news/items/1098</link>
      <pubDate>Sun, 15 Aug 2021 20:32:02 GMT</pubDate>
    </item>
...
```

For folks subscribing to the RSS feed:

* The `link` doesn't go to the article but rather the entry on `stacker.news` which seems surprising to me
* There is no way to get the address of the linked article but to do another query to `stacker.news`

It would be much nicer, in my opinion, if the `link` field had the address of the linked article (in the above example `https://twitter.com/ltngstore/status/1426950427346542594?s=20`).
At the very least, adding another field that has the proper link would be nice.

Obviously this can't happen for all items, as some the main link is the `guid`, but where appropriate it would be good to provide the link.

**Comment by huumn** [comment]
Ah, yep that's a bug. I think HN puts a link to the comments in the description tag. I'll do that.

**Comment by huumn** [comment]
Shipped! Thanks for reporting
