### ISSUE TITLE
New users can't see their own posts

### ISSUE THREAD

**Issue by ekzyis** [stackernews/stacker.news#233]
New user sees by default not his own post in the top 21:
![2023-02-08-062746_902x379_scrot](https://user-images.githubusercontent.com/27162016/217442602-54d28199-c3ad-470a-a055-2027a23dcfef.png)

After enabling wild west mode:
![2023-02-08-062806_895x378_scrot](https://user-images.githubusercontent.com/27162016/217442727-c63b2a65-152f-4c48-9402-5b9a3383bfb8.png)

I mean, this makes sense that wild west mode is not enabled by default but maybe it would make sense that every user can see his own posts all the time?

**Comment by huumn** [comment]
Nice catch! 

This is a bug. It should be visible.

**Comment by huumn** [comment]
This post actually got a lot of downvotes and AFAICT should be visible on homepage ranking, but is just lower in the fold. In WWM right now it's at position 33 but 46 in tenderfoot mode.

Going to close. Will reopen if there's confirmation that it's hidden and not just downranked.

**Comment by ekzyis** [comment]
Mhh, yes, interesting. Just testing locally and own posts show up without wild west mode as a new user.
