### ISSUE TITLE
SN bounty: display image when provided an image link

### ISSUE THREAD

**Issue by jowo-io** [stackernews/stacker.news#239]
This issue is to begin the feedback process for the bounty:
```markdown
Currently to show an image on SN you have to specify the correct markdown. It'd be nice to just display the image when provided an image link without requiring markdown.

e.g. when a stacker puts this image link in a comment or discussion post https://imgproxy.snort.social/h_yDski4D7T74dzC6fwcBqwBoMOw3og33BmkNewTMjA/rs:fit:586:586/dpr:2/aHR0cHM6Ly9tZWRpYS50ZW5vci5jb20vVzY0SVhKQmZGcFlBQUFBQy9maXJpbmctZ3VuLWplbm5pZmVyLWNvb2xpZGdlLmdpZg

It renders this without requiring markdown 

I'll pay double the bounty if it's well implemented with minimal need for changes. I'll pay triple the bounty if you also make it work for link posts where the link is an image.
```
> original post can be found here: https://stacker.news/items/138566

I've made a start on this bounty and am looking for feedback. See the video demo here:

https://www.loom.com/share/028b0dfd00da4aa49827d285c2320209

any feedback from stackers here would be appreciated, and of course from the guys at SN HQ. thanks

**Comment by ekzyis** [comment]
The shown approach of formatting image links as markdown would still make it possible to just display the url of an image as a fellow stacker asked about:

> What if, for some reason, you just want to display the url of an image?

-- https://stacker.news/items/138604

This approach is also consistent with markdown: during text render, plain markdown (afaik) is rendered.
No additional steps required like formatting the image URLs to markdown just before rendering or something.
So I think this fellow stacker would also be happy as it is:

> We'll still be able to use markdown right?

-- https://stacker.news/items/138590

However, I don't like the asynchronous formatting inside the text editor.
I see that it is a obvious solution but depending on how this is implemented, this could be weird.
I don't expect my text editor to make HTTP requests. Maybe that's just me.

Also, this depends that the async formatting will work in any context.
For example, posts created with the stacker.news API will not have this.

So I think it would be better if formatting like this is done server-side.

**Comment by huumn** [comment]
The approach that I think is best is to avoid modifying the markdown and instead modify the rendering of the markdown. e.g. when a stacker enters a mention @<stacker nym> in a text field it gets rendered specially, but I don't modify the markdown itself. 

I'd like to keep the image link recognizing/rendering behavior consistent with that unless there's a reason not to.

**Comment by jowo-io** [comment]
> Would the shown approach of formatting image links as markdown would still make it possible to just display the url of an image as a fellow stacker asked about?
> 
> > What if, for some reason, you just want to display the url of an image?
> 
> -- https://stacker.news/items/138604
> 
> I am not sure if this autoformatting will only get triggered during paste or if it will reformat the URL when the autoformatting was manually removed.

Yes it's on paste only

> This approach is also consistent with markdown: during text render, plain markdown (afaik) is rendered. No additional steps required like formatting the image URLs to markdown just before rendering or something. So I think this fellow stacker would be happy as it is:
> 
> > We'll still be able to use markdown right?
> 
> -- https://stacker.news/items/138590

Yup, i agree. it's kinda a trade off between advances and novice users that imo works nicely.

> However, I don't like the asynchronous formatting inside the text editor. I see that it is a obvious solution but depending on how this is implemented, this could be weird. I don't expect my text editor to make HTTP requests. Maybe that's just me.
> 
> Also, this depends that the async formatting will work in any context. For example, posts created with the stacker.news API will not have this.
> 
> So I think it would be better if formatting like this is done server-side.

I think it's not anything to controversial tbh to make an async request. Are you familiar with the GitHub drag/drop image upload? it works it much the same way!
there's no point shifting this burden to the server side when we can offload the responsibility to the client. also if the server does it, there's no way to show the user a preview.

**Comment by jowo-io** [comment]
@huumn any thoughts on the above comments?
after having looked at the code for rendering markdown I think most of the points I made above are still worth considering

**Comment by ekzyis** [comment]
Oh, I noticed I never sent my reply lol

> I think it's not anything to controversial tbh to make an async request. Are you familiar with the GitHub drag/drop image upload? it works it much the same way!
there's no point shifting this burden to the server side when we can offload the responsibility to the client. also if the server does it, there's no way to show the user a preview.

Oh, yes, totally forgot about GitHub. Fair enough. Was just a gut feeling about that async formatting.

> doing the checks at render time would presumably mean firing off an async request to check all the URLs each time the markdown is rendered. this will add significant bloat to the network requests made every time a user previews a post and more significantly, every time a user view a sn post containing any url.

Mhh, good point. A friend of mine has a website with a similar feature as requested in the bounty.
I guess that's why he is using a URL whitelist so he does not have to check every URL for images.
However, regarding the bloat: A simple HEAD request would be enough to check the headers, no?
So this would at least be less bloat than actually fetching every URL using GET.
So maybe this is not _that_ big of an issue? (I agree that it _is_ an issue, though)

Also, [didn't you want to create a PR](https://stacker.news/items/139293)? I think it's easier to discuss things more deeply using existing code as an example or "guidance".

**Comment by jowo-io** [comment]
@huumn
> My thoughts remain the same. "the above comments" were known to me when I said what I said.

I'm curious why consistency here is so key when there are several pros/cons that I mentioned? mind expanding a little on it? Doesn't have to be an essay just a little context :)

@ekzyis
> Mhh, good point. A friend of mine has a website with a similar feature as requested in the bounty.
> I guess that's why he is using a URL whitelist so he does not have to check every URL for images.
> However, regarding the bloat: A simple HEAD request would be enough to check if it's an image using the headers, no?
> So this would at least be less bloat than actually fetching every URL using GET. (Not sure if you considered this)
> So maybe this is not that big of an issue? (I agree that it is an issue, though)

Yeah i thought this initially too, but after digging a little (and trying a `HEAD` request on the image link provided in the bounty description, as well as a few other links) I came to understand that the `HEAD` method is just a specification, and not necessarily implemented by the server that's hosting the image. So basically, not all servers implement it and it cannot be relied upon.

The easiest way I've found so far to check if the link is an image is to simply created a JS image object, e.g.
```
const img = new Image();
img.onload= () => {}; // if it loads successfully we know the link is to an image!
img.onerror = () => {}; // if it fails to load we can assume that it's not a link to an image.
img.src = url; // assign the url entered into the textarea here
```

This has the added benefits of:
* saving the image in the cache so when it's rendered in the markdown render component it'll basically already be preloaded.
* avoiding CORS issues that can arise from making cross origin fetch requests

**Comment by ekzyis** [comment]
> Reason i haven't opened a PR just yet is because the code feels a bit rough-and-ready still. I can throw it up though if you're not bothered by that just for the initial context

No, I don't mind. That's what drafts are for :)

**Comment by jowo-io** [comment]
Ok i'll open a PR. However I'll assume the original way i implemented it can be scrapped since it's clear from what huumn has said that he doesn't want it done that way.

So here's another demo of how I understand huumn does what the feature to work:
https://www.loom.com/share/7e6ed97981a64840b25d9e62507eb279

I'll open a PR shortly with this new code.

**Comment by jowo-io** [comment]
PR opened: https://github.com/stackernews/stacker.news/pull/245

**Comment by jowo-io** [comment]
gunna drop a little bump in here

**Comment by huumn** [comment]
Sorry, I’ll try to take a quick look today but I agree with @ekzyis that the PR has unrelated things in it that shouldn’t be there and certainly need to be removed before being merged. 

Regardless, I’ll reward you the bounty minimum if there’s usable code in there.

**Comment by jowo-io** [comment]
ok sure, I'll remove the changes unrelated (will leave the node version as 16 for now on my branch though because i can't run it on node 14 [see](https://github.com/stackernews/stacker.news/issues/238))

**Comment by ekzyis** [comment]
Done in #245
