### ISSUE TITLE
The operation cannot be completed. (OAuthSwiftError error -2.)

### ISSUE THREAD

**Issue by anthonyvardizzone** [stackernews/stacker.news#24]
I noticed a while ago I started getting the above error on macOS when manually refreshing my feed.

Through discussion in the #general Slack channel, it was determined that this error is caused due to a `tokenExpired` status for an enabled Twitter extension (not sure if it would also apply to the Reddit extension as well since I did not have that extension enabled).

A simple fix that was suggested to me was to deactivate the extension and then reactivate. I can confirm this worked. I also revoked NetNewsWire from accessing my Twitter account and re-enabled it, but they may not have been necessary. Based on the language on the Twitter page, NetNewsWire's access had not be previously revoked.

Was told to open an issue so it could be kept track of.

**Comment by anthonyvardizzone** [comment]
My bad. This was meant for a different project.

**Comment by huumn** [comment]
Lol all good! I was reading that super concerned for a minute.
