### ISSUE TITLE
Broken link "top users" /top/users in settings page

### ISSUE THREAD

**Issue by emanuelb** [stackernews/stacker.news#240]
visit settings page: https://stacker.news/settings
click on "top users" in setting:
> hide me from [top users](https://stacker.news/top/users)

result in 404 page not found.

link in code:
https://github.com/stackernews/stacker.news/blob/97f74da0fd4dfe1a94f707ca0a32865cfe5a1c19/pages/settings.js#L206

currently the working links under users are: 
https://stacker.news/top/users/forever
https://stacker.news/top/users/day
https://stacker.news/top/users/week
https://stacker.news/top/users/month
https://stacker.news/top/users/year
https://stacker.news/top/users/forever

**Comment by ekzyis** [comment]
I guess it should point to `/top/users/day` since day seems to be the default.

Clicking on `top` also goes to `/top/posts/day`.
