### ISSUE TITLE
Inconsistent behavior while checking if nym is already taken

### ISSUE THREAD

**Issue by ekzyis** [stackernews/stacker.news#257]
https://user-images.githubusercontent.com/27162016/230557133-a3a57655-cd42-4684-a4e0-5a422ba2c45b.mp4

**Comment by ekzyis** [comment]
Probably same cause as #213

**Comment by huumn** [comment]
If it is like #213 it's caused by multiple query requests being issued and their responses returning out of order. 

In this case, fixing would be either

1. cancel any pending requests when a new one is issued, or
2. delay/debounce requests until the stacker stops typing

**Comment by SatsAllDay** [comment]
I think I’d like to work on this one. My thought was to take the debounce approach, less unnecessary server load is always a bonus. 

Thoughts on debounce period? 300ms? 500?
