### ISSUE TITLE
Allow zapping without funds or an account

### ISSUE THREAD

**Issue by huumn** [stackernews/stacker.news#266]
This is something I've been wanting to do for awhile. 

It'd be nice to allow lurkers to zap *and* allow stackers to zap arbitrary amounts even if their wallet doesn't have enough sats ... by presenting an invoice for them to pay in a modal.

**Comment by ekzyis** [comment]
I think this needs more explanation. How should this work? Like "likes" on nostr?

**Comment by huumn** [comment]
> I think this needs more explanation. How should this work? Like "likes" on nostr?

My bad. Basically it means: present the person an invoice in a modal when they don't have enough funds to zap or are logged out.

**Comment by dhk2** [comment]
You could also check for webLN support in the browser for zapping/refill using alby/joule or mobile a wallet browser instead of QR code modal.

**Comment by huumn** [comment]
Those would definitely be nice to have in addition to a qr.

**Comment by ekzyis** [comment]
Should this be limited to zaps or also allow posting and anything else that costs sats on SN?

I would only allow zaps in the first iteration but wanted to ask if the scope should become larger further down the road

**Comment by huumn** [comment]
Yes, we'd like to eventually allow posting/commenting without accounts too. 

We might want to make those more expensive than usual but tbd.
