### ISSUE TITLE
Enhancement request: Add to Search a link to a guide

### ISSUE THREAD

**Issue by cointastical** [stackernews/stacker.news#274]
[Search filters were added in October 2022](https://stacker.news/items/83923), and I still don't really know how to use them. 

For instance, today I want to find a comment that I had made by searching for some set of words, and this comment would have been before Jan 2023. 

Another [post with "refinements"](https://stacker.news/items/85615) gives more info, in that i would add nym:cointastical to see my own comments.  But this is not intuitive.

A comprehensive guide for search and search filtering would be useful   (just as how for composing comments replies, a link to a guide for markdown is just a click away).

**Comment by ekzyis** [comment]
Multiple users (me included) noticed some lacking of UX with the search.

Thanks for the issue, the search definitely needs a rework

**Comment by huumn** [comment]
Current hidden filters that definitely need to be documented are: 

- `~subname`, search within a specific sub
- `nym:ausersnym`, search for items from a certain user
- `url:aurl`, search for certain urls ... currently this is only domain names iirc

These should probably be added to the FAQ @kerooke and we can link to it from the empty search page.
