### ISSUE TITLE
Add ability to subscribe to threads 

### ISSUE THREAD

**Issue by huumn** [stackernews/stacker.news#283]
moneyball asked about this recently ... its something I've been wanting to do but was going to do it with an overlapping feature.

Basically: user who isn't OP can get notifications about new comments to an item.

It's pretty straightforward.

**Comment by huumn** [comment]
Good point! Symmetrical subscriptions complicate this a little, but worth doing.

**Comment by ekzyis** [comment]
Wasn't there an issue for following users? I haven't found one ... 

But, I wanted to add here: Maybe this can be implemented such that we get "following users" for free? For example, if users are also items in the backend and every post they make is a reply to that item? Then we could follow that user/item and would get notified about every post they make with minimal additional code.

This wouldn't work to see every comment they make but I realized I would find that creepy anyway. You can already see all comments a user made but getting notifications about it feels a lot more like "stalking" than following at this point, lol. What do you think?

Is btw "following users" what you meant with:
> overlapping feature

?

**Comment by huumn** [comment]
> Is btw "following users" what you meant with:
> > overlapping feature

No. We were going to do group discussions, ie multiple OPs on a post, so we could ask people to come on and debate something.

> following users?

I think this is a bit of a mirage like bookmarks. People think they want it because they know its a thing they can ask for, but I'm not sure it makes sense for us.

**Comment by ekzyis** [comment]
This would also be useful for me so I can subscribe to posts of https://stacker.news/hn to reply to comments
