### ISSUE TITLE
RSS Feed Errors

### ISSUE THREAD

**Issue by abetusk** [stackernews/stacker.news#29]
When navigating to the [rss feed](https://stacker.news/rss), I get the following error:

```
XML Parsing Error: not well-formed
Location: https://stacker.news/rss
Line Number 86, Column 99:
      <link>https://twitter.com/irisenergyco/status/1428677975537377285?t=esQNOfvjbmpMrItP9oHjSA&s=19</link>
--------------------------------------------------------------------------------------------------^
```

**Comment by huumn** [comment]
Weird that it failed on that `=` and not the others. I'm an XML noob. I'll see what I can do.

**Comment by huumn** [comment]
I guess I needed to escape links of special characters too. smh xml. Thanks for reporting!

**Comment by abetusk** [comment]
Was it just the `=` or did you have to escape other special characters as well, like `&` and `?`?

**Comment by huumn** [comment]
It was the ampersand which is why single GET param URLs worked fine.
