### ISSUE TITLE
Pay bounty still visible after bounty was paid

### ISSUE THREAD

**Issue by ekzyis** [stackernews/stacker.news#306]
![2023-06-07-155745_1920x1080_scrot](https://github.com/stackernews/stacker.news/assets/27162016/cce2f2f4-cb6d-4933-996c-c7e96e813c8a)

:thinking:

**Comment by ekzyis** [comment]
Ah, was wondering if this was the use case. So it would actually have sent you 25k sats if I pressed the button?
I was about to just test what happens lol

I guess then it's not a bug but confusing UX (since it looks like a bug). Maybe this can be clarified/specified when creating the bounty?

Also, will it update the amount paid when multiple people are paid?

**Comment by huumn** [comment]
> Maybe this can be clarified/specified when creating the bounty?

It could be. I personally don't think it's *that* unclear that there can be many bounty recipients but maybe.

> Also, will it update the amount paid when multiple people are paid? (unclear from your example post)

No but it could. It might be fun to have it say '25000x2 sats paid'

**Comment by ekzyis** [comment]
> It could be. I personally don't think it's that unclear that there can be many bounty recipients but maybe.

Think about it like https://bountsr.org/. I think most people (myself included) don't assume that multiple people can win a bounty. It's regarded as a competition where only one can win. But now that you mention it, I am no longer sure that's how bounstr works, lol. I was pretty sure before, though.

> No but it could. It might be fun to have it say '25000x2 sats paid'

Yeah I think that would be good
