### ISSUE TITLE
UX: Scrolling to collapsed comments does not uncollapse them

### ISSUE THREAD

**Issue by ekzyis** [stackernews/stacker.news#307]
Scrolling to a comment assumes the comment is uncollapsed:

https://github.com/stackernews/stacker.news/assets/27162016/a32a172b-a1d2-42c0-83da-ad02bff3139e

**Comment by huumn** [comment]
Ah yeah we scroll before collapsing I think

**Comment by huumn** [comment]
We delay scrolling for 20ms now to allow comments to collapse first.
