### ISSUE TITLE
No mention after markdown link

### ISSUE THREAD

**Issue by ekzyis** [stackernews/stacker.news#322]
https://github.com/stackernews/stacker.news/assets/27162016/964bbce9-24fd-484e-8c14-67847e5fd01e

See https://stacker.news/items/193398

**Comment by SatsAllDay** [comment]
Is this still happening? I tried it on prod and it seems to be working now

**Comment by ekzyis** [comment]
Mhh, yes, in the linked comment, siggy47 is not highlighted as a mention.

Interesting, don't know what we changed such that it works now. Maybe because we removed a markdown extension [here](https://github.com/stackernews/stacker.news/pull/508)?
