### ISSUE TITLE
Display A Stacker's Longest Cowboy Hat Streak On Their Profile

### ISSUE THREAD

**Issue by kerooke** [stackernews/stacker.news#326]
Cowboy hat streaks have become a point of pride for Stackers, and some already compete with other stackers to see who can maintain the longest cowboy hat streak.

However, once a cowboy hat streak is lost, stackers lose all of the status associated with their streak and their hard work maintaining it.

To preserve some piece of the hard work a stacker puts into maintaining their streak, Stacker News should display the longest streak that each stacker has ever achieved directly on the stacker's profile, just like how SN displays a "Stacking since" link referring to the date the user joined the site.

This way, even if someone loses a 100 day streak, they will still be able to show other users that they once built up a 100 day cowboy hat streak. A user's cowboy hat streak record will also serve as a target for users to compete with themselves to beat their previous best.

**Comment by ekzyis** [comment]
Forgot to link this ticket in https://github.com/stackernews/stacker.news/pull/353

But since there is a bug anyway, I will close this ticket when it's fixed
