### ISSUE TITLE
Duplicate comments when using Control + Enter

### ISSUE THREAD

**Issue by orthzar** [stackernews/stacker.news#327]
I noticed recently that when I post a comment using Control + Enter, SN will post my comment twice. Here is an example: https://stacker.news/items/198123
Notice that those duplicates comments were posted 0.044 seconds apart.

Here's the spending breakdown of those comments:
![image](https://github.com/stackernews/stacker.news/assets/1767056/a5cc1820-cca5-4d4c-9e67-ad8ff11c89e4)

**Comment by ekzyis** [comment]
Reproduced, will look into it, thanks!

Will send you some sats for the tests
