### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by huumn** [stackernews/stacker.news#33]
Users want this. I do too but I keep forgetting.

**Comment by johnpaulkiser** [comment]
How were you thinking about doing this? I'm interested in this, although Sass color theming is not that straightforward.

**Comment by huumn** [comment]
I'd love a PR of any sort on this.  It's easy for this to slip down the de-prioritization slope.

tbh I haven't done a dark mode before so I don't know technically how to achieve it best - although I suspect there are some best practices here. Naively, I'd just break up the global sass file and define another one with different color theming and maybe nest it in a `.darkmode` class that can be put on the body. (note: I'm a pretty hard sass n00b.) I'd probably also attempt to pull out some of the colors spread across css modules to make overriding them easier.

From a design standpoint, it's mostly a fairly straightfoward flipperoo with dark grey and off-white but it will need refinements in the greys and possibly the colors (although I hope not ... but the green I use is quite dark). 
<img width="1263" alt="Screen Shot 2021-08-29 at 12 08 25 PM" src="https://user-images.githubusercontent.com/34140557/131259055-87f967f7-6b5e-4583-bdee-90f14ef1e422.png">

**Comment by johnpaulkiser** [comment]
A pretty straight forward way to do this would be to put all of your theming into styled-components then create a global theme provider. The upside is that you still get to use Sass and don't have to worry about keeping 2 global stylesheets in sync. The downside is that you have to migrate to styled-components.  I personally love styled-components & would like to make this PR, but if you don't think the project is ready for that kind of migration I'm sure there is another way.

**Comment by huumn** [comment]
From a quick google around it seems like it has a lot of advantages and ACK the migration proposal if it's something you'd like to do. It seems like styled components would make it easy to provide not just light and dark mode but perhaps even other, user defined themes.

If you pursue, forgiveness in advance for a lot of my styling and component hacks 😂 - I tend to prioritize upfront development speed at the cost of everything else when a product is young.

**Comment by johnpaulkiser** [comment]
> I tend to prioritize upfront development speed at the cost of everything else when a product is young. 

I wouldn't have it any other way!

I probably won't get to this until the weekend but I'll open a PR.

**Comment by huumn** [comment]
Very much looking forward to it!

**Comment by johnpaulkiser** [comment]
Hi, I don't think I have time to complete this. I'm running into a lot of trouble running the app locally 😕. I'll post PR with a few commits if anyone wants to take it on from there but maybe consider dockerizing the app or updating the readme.

**Comment by huumn** [comment]
Dockerizing the app is a todo. Thanks for the effort!

**Comment by notnout** [comment]
I think going with a bit darker background may be better, e.g. something like #111, but you could give it a bit of yellow tint. 
<img width="1210" alt="Screen Shot 2021-09-28 at 12 32 47" src="https://user-images.githubusercontent.com/91558366/135154237-6b8582e1-4d79-4989-9b86-d6123c09a936.png">

**Comment by huumn** [comment]
Yes, that's much better!

**Comment by huumn** [comment]
After much grief and a working dark-mode using styled components, with SSR this isn't the way to go as it'll require either: users be signed in to get dark mode (so we can know on the server which style they want), a variety of hacks. The move instead is to probably use css variables like is suggested here: https://www.joshwcomeau.com/react/dark-mode/
