### ISSUE TITLE
Different font sizes for write and preview of comments.

### ISSUE THREAD

**Issue by orthzar** [stackernews/stacker.news#333]
I've noticed that SN uses different font sizes for Write and Preview of comments. This is a problem when writing more than a few lines of text. For instance, see the highlighted word in the first picture below and try to find that exact word in the second picture:
![image](https://github.com/stackernews/stacker.news/assets/1767056/b3690d76-693b-497d-aaf3-b29fad4675ad)
![image](https://github.com/stackernews/stacker.news/assets/1767056/2aae5db1-4262-4870-ac14-5374014752c5)

I've tested this in Chromium and Firefox, and got the same results.

**Comment by huumn** [comment]
Nice catch. Yeah it's definitely smaller. Line height is also different.
