### ISSUE TITLE
Improve Visibility of Daily Rewards Payout

### ISSUE THREAD

**Issue by kerooke** [stackernews/stacker.news#339]
**Is your feature request related to a problem? Please describe.**
Right now, there is almost no visibility into the daily rewards being paid out each day by Stacker News. Tens of thousands of sats each day are being distributed to top posters, commenters, and voters, but I suspect most visitors and stackers still have no idea.

**Describe the solution you'd like**
As a MVP solution, Stacker News should display the number of sats being rewarded each day as part of the "Daily Discussion Thread" post title. The display should also include a countdown timer to the payout.

For example, a stacker visiting the site at 8am CT might see "Daily Discussion Thread - 34,257 Sat Payout in 16:00:00". To get the full effect, and to improve liveliness on SN, both the number of sats and the countdown timer should update in real-time.

Furthermore, when a stacker clicks on the Daily Discussion Thread item, the copy above the message box could also include a line with the same information above, along with a link to the rewards page for anyone who wants a detailed overview of the upcoming payouts.

This solution dramatically improves the visibility of the daily rewards payout, and it doesn't add any other UX challenges. In fact, it has a really nice tie-in to the daily discussion thread as both the discussion thread and the payout amounts are referring to the current day.

**Describe alternatives you've considered**
Initially I considered adding this feature to the navbar, but the visibility wouldn't be as high (since there are already 3 other navbar numbers which stackers can rotate through. 

Furthermore, the lack of space on mobile doesn't allow for a detailed description, limiting the amount of useful context we could add to the daily rewards number.

**Additional context**
This is an MVP feature, but I am thinking through a bigger upgrade to the daily discussion thread as well. This feature will be fully compatible with the bigger upgrade too.

**Comment by ekzyis** [comment]
I fully agree that the daily reward is not transparent enough for stackers.

I still remember that it was a big surprise when I received my first earn notification. I didn't know there were daily rewards. 
However, the notification itself has some room for improvement: It does not include enough context to understand which post or comment was responsible for their daily reward. It only shows "for top comments" or "for top posts" etc.

However, information like this would be useful for a stacker to know which content they should produce more of.

I may create a own issue for this.
