### ISSUE TITLE
Add WebLN

### ISSUE THREAD

**Issue by huumn** [stackernews/stacker.news#35]
Wallet providers use a protocol (https://webln.dev/) to make sending lightning payments less cumbersome is my understanding. It'd be nice to support this.

**Comment by bumi** [comment]
I was thinking of the most simple WebLN integration. (so without changing the concept that the user has an account and a balance). 

we could simply check for webln on the QR topup page: https://github.com/stackernews/stacker.news/compare/master...bumi:webln?expand=1 (pseudo code - because I could not run it)

the idea is, that it checks of WebLN is available, if so it hands over to WebLN. if NOT it shows the current flow with the QR code

**Comment by huumn** [comment]
Thanks for this! This is roughly the level of change required to support WebLN? Much less work than I thought

**Comment by bumi** [comment]
Yeah, just call some JS instead of showing a QR code. + some error handling (and showing the QR code in the error case)

**Comment by huumn** [comment]
Right on, I'll reprioritize this. Might be able to cram it in today even.

**Comment by bumi** [comment]
Let me know if you have questions. I am happy to help (you can also find me in the bitcoin design slack)

**Comment by huumn** [comment]
Hey @bumi, deployed this. SN now supports both fund and withdrawals through WebLN. Tested it with Joule - seems to work well. Thanks for giving me the push!

Lmk if you have any gripes.

**Comment by bumi** [comment]
whoop whoop! you're fast. works great! 🎉 :shipit: 
Though I would only show the QR code if WebLN is NOT available or the WebLN request fails. - I find doing both a bit confusing...

is there a reason why you do it like this? (In my code I tried to do that with the `useWebln` state.)

**Comment by huumn** [comment]
I don't disagree but a blank page is also confusing - in a different way. This is just version get.it.done. On my MacBook Air the popup from Joule covers most of the page, so it also didn't seem too confusing too. Up to changing it though if your experience differs significantly.

**Comment by bumi** [comment]
I'd show a loading spinner instead. 

Our [extension](https://github.com/bumi/lightning-browser-extension/) currently pretty quickly closes the popup after confirmation and it takes a second until the payment is done. 
So I guess there the QR code is visible longer. 
I also think the idea is that most should be handled in the website (e.g. also error handling) - so we do not wait but leave it up to the website.
