### ISSUE TITLE
Internal Linking and References

### ISSUE THREAD

**Issue by huumn** [stackernews/stacker.news#350]
Motivated by this question: https://stacker.news/items/205407

We should give special treatment to SN content that links to other SN content. This would allow older SN content to be more easily rediscovered. It could work a lot like github issues/prs do, e.g. #349 creates a relationship between that PR and this Issue and if you view the PR, it mentions this issue. GH will even trigger actions based on references.

This kind of linking provides rich context, content discovery, and is a simple yet very powerful primitive.

**Comment by ekzyis** [comment]
> GH will even trigger actions based on references.

Yes!

One such action that could make sense for SN is to have a opt-in notification setting to get notified if someone links to a post or comment that you created.

**Comment by huumn** [comment]
Oh that'd be cool. Didn't even think of that.

**Comment by huumn** [comment]
This is a duplicate
