### ISSUE TITLE
Push subscriptions are lost

### ISSUE THREAD

**Issue by ekzyis** [stackernews/stacker.news#354]
**Description**

Users lose their push subscriptions

**Steps to Reproduce**

Wait a random amount of time

**Expected behavior**

Push subscriptions are not lost

**Environment:**

Happens on every device afaict

**Additional context**

https://stacker.news/items/208422

**Comment by ekzyis** [comment]
> **10.5 The _pushsubscriptionchange_ Event**
>
> The [pushsubscriptionchange](https://w3c.github.io/push-api/#dfn-pushsubscriptionchange) event indicates a change in a [push subscription](https://w3c.github.io/push-api/#dfn-push-subscription) that was triggered outside of the application's control, for example because it has been refreshed, revoked or lost.
>
> To fire the "pushsubscriptionchange" event given a [service worker registration](https://www.w3.org/TR/service-workers/#dfn-service-worker-registration) of registration, newSubscription and oldSubscription, the [user agent](https://w3c.github.io/push-api/#dfn-user-agent) must [fire a functional event](https://www.w3.org/TR/service-workers/#fire-functional-event) named "pushsubscriptionchange" using [PushSubscriptionChangeEvent](https://w3c.github.io/push-api/#dom-pushsubscriptionchangeevent) on registration with the following properties:
> - newSubscription
> - oldSubscription

> _NOTE_
Consider using a more reliable synchronization mechanism such as [[WEB-BACKGROUND-SYNC](https://w3c.github.io/push-api/#bib-web-background-sync)] when sending the details of the new [push subscription](https://w3c.github.io/push-api/#dfn-push-subscription) to your [application server](https://w3c.github.io/push-api/#dfn-application-server). The user might be subject to unreliable network conditions that could cause a fetch to fail.

-- https://w3c.github.io/push-api/#the-pushsubscriptionchange-event



> **10.5.2 _PushSubscriptionChangeEventInit_ Interface**

```
dictionary PushSubscriptionChangeEventInit : ExtendableEventInit {
  PushSubscription newSubscription = null;
  PushSubscription oldSubscription = null;
};
```

> The newSubscription member details the [push subscription](https://w3c.github.io/push-api/#dfn-push-subscription) that is valid per invocation of the [pushsubscriptionchange](https://w3c.github.io/push-api/#dfn-pushsubscriptionchange) event. The value will be null when no new [push subscription](https://w3c.github.io/push-api/#dfn-push-subscription) could be established, for example because the web application has lost [express permission](https://www.w3.org/TR/permissions/#dfn-express-permission).
> 
> The oldSubscription member details the [push subscription](https://w3c.github.io/push-api/#dfn-push-subscription) that SHOULD NOT be used anymore. The value will be null when the [user agent](https://w3c.github.io/push-api/#dfn-user-agent) is not able to provide the full set of details, for example because of partial database corruption.

-- https://w3c.github.io/push-api/#pushsubscriptionchangeeventinit-interface

So I see following reasons why our code doesn't work:

- it doesn't handle unreliable network conditions
- it doesn't handle cases where `oldSubscription` is null or `newSubscription` is not null
- **it doesn't even get called since it's [still not supported by a lot of browsers](https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerGlobalScope/pushsubscriptionchange_event#browser_compatibility)**

The last point is the most likely the issue, so I guess we need a workaround and can't rely on this event listener. [Here](https://medium.com/@madridserginho/how-to-handle-webpush-api-pushsubscriptionchange-event-in-modern-browsers-6e47840d756f) is a post from 2019 how to do this.

**Comment by huumn** [comment]
Pretty impressive how unsupported it still is 4 years later.
