### ISSUE TITLE
Local development doesn't work without setting VAPID config

### ISSUE THREAD

**Issue by felipebueno** [stackernews/stacker.news#357]
**Description**
Local development doesn't work without setting up VAPID config on .env

**Steps to Reproduce**
```git clone git@github.com:stackernews/stacker.news.git sn && cd sn```

```docker-compose up --build```

**Expected behavior**
Local development should(?) work without the need to setup web push. Or, maybe, documenting how to modify the .env file to satisfy webPush.setVapidDetails.

**Screenshots**
![image](https://github.com/stackernews/stacker.news/assets/241271/763f1d77-9251-44b0-a103-b442721f4b36)

![image](https://github.com/stackernews/stacker.news/assets/241271/8f5f3e02-9b67-487b-a634-5d78181bc4bf)

![image](https://github.com/stackernews/stacker.news/assets/241271/7f54cbd5-71f6-4493-bb0e-3be152302891)

![image](https://github.com/stackernews/stacker.news/assets/241271/50d3fb22-ca7a-4a7b-aff6-00f4626cfef7)

![image](https://github.com/stackernews/stacker.news/assets/241271/4026469a-22ca-4873-a175-55648477d8c4)

**Comment by ekzyis** [comment]
Ah, thanks for the issue and you are right! It doesn't work without setting up these environment variables and we should update our documentation.

For the VAPID keys, you can run `npx web-push generate-vapid-keys`. `VAPID_MAILTO` should just be a mail prefixed with `mailto:`. So `mailto:foo@bar.com` should work.

There may be a similar issue for the imgproxy env but these don't prevent starting the server. However, It may break the frontend when visiting some posts. For `IMGPROXY_KEY` and `IMGPROXY_SALT` you can run `openssl rand -hex 64`.

Would you mind creating a PR to document this? Else I can do this soon.

**Comment by wbobeirne** [comment]
IMO would love to see the effort to get a dev env setup reduced. I think wrapping that in a conditional for running in development would be nice, e.g.

```ts
if (process.env.NODE_ENV === 'development' && !process.env.VAPID_MAILTO) {
  console.info('VAPID_* env vars not set in development, skipping webPush setup')
} else {
  webPush.setVapidDetails(
    process.env.VAPID_MAILTO,
    process.env.NEXT_PUBLIC_VAPID_PUBKEY,
    process.env.VAPID_PRIVKEY
  )
}
```

Alternatively, move the `setVapidDetails `call into one of the async functions so that it just throws on the first time you attempt to do anything with push, rather than during initial render.

**Comment by SatsAllDay** [comment]
> IMO would love to see the effort to get a dev env setup reduced. I think wrapping that in a conditional for running in development would be nice, e.g.
> 
> ```ts
> if (process.env.NODE_ENV === 'development' && !process.env.VAPID_MAILTO) {
>   console.info('VAPID_* env vars not set in development, skipping webPush setup')
> } else {
>   webPush.setVapidDetails(
>     process.env.VAPID_MAILTO,
>     process.env.NEXT_PUBLIC_VAPID_PUBKEY,
>     process.env.VAPID_PRIVKEY
>   )
> }
> ```
> 
> Alternatively, move the `setVapidDetails `call into one (or many) of the async functions so that it just throws on the first time you attempt to do anything with push, rather than during initial render.

Just a +1 here, I used the above quoted code snippet to enable local development and it got me past this issue. Thank you for the workaround!
