### ISSUE TITLE
LNURL withdraw needs CORS headers

### ISSUE THREAD

**Issue by wbobeirne** [stackernews/stacker.news#358]
*Note: this template is meant to help you report the bug so that we can fix it faster, ie not all of these sections are required*

**Description**

The `/api/lnwith` endpoints do not have CORS headers, resulting in errors when trying to make withdrawal requests from webpages.

**Steps to Reproduce**

Go to any site except stacker news and run this in the console:
```ts
fetch("https://stacker.news/api/lnwith?tag=withdrawRequest&k1=test", {
  "method": "GET",
  "mode": "cors"
});
```

You'll get
> Access to fetch at 'https://stacker.news/api/lnwith?tag=withdrawRequest&k1=test' from origin '[website]' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**Comment by wbobeirne** [comment]
Note that this isn't a major blocker, a user could just create an invoice and copy / paste it over. But on the off chance they decide to copy the LNURL instead, it'd be nice if it worked.

**Comment by huumn** [comment]
Another example is https://clams.tech/
