### ISSUE TITLE
async-retry bug?

### ISSUE THREAD

**Issue by huumn** [stackernews/stacker.news#36]
Got a. report on twitter that async-retry might not work with a try block inside or something like that. Need to investigate. We use this for when there are serialization conflicts when updating user wallet balances.

**Comment by ekzyis** [comment]
They may have been referring to this: https://github.com/vercel/async-retry/issues/69

So it's only broken if you use `bail` and then throw an error afterwards. Which we don't do.

**Comment by huumn** [comment]
cool, going to close
