### ISSUE TITLE
Search field no longer exists at bottom, except for /search

### ISSUE THREAD

**Issue by cointastical** [stackernews/stacker.news#365]
Not sure if that was intended behavior, or if that was a regression.   But it's gone now, ... as far as I can tell, site-wide, except for /search.

If that change was intended behavior, then perhaps modify /search to put it prominently up in the body, like how Google search UI (and most every other search page) has it, at least for the first /search page, maybe only when there's no ?q= yet, or ... if that's now the main method for search, then fix the serach fields to be up above the search results all the time, if /search is the only page that has those fields now.

Others requesting a fixed search bar up in the body (when in /search page): 

*Stacker Search box proposal - search box similar to google*
https://stacker.news/items/148535

**Comment by ekzyis** [comment]
makes sense to have the search field at the top, thanks for the issue!

**Comment by brihuang99** [comment]
Sharing @cryptofolyo's mockup here:

![image](https://github.com/stackernews/stacker.news/assets/122472324/6f3c2daa-19f1-401c-8dfc-ddc5bd375cc4)

**Comment by huumn** [comment]
While I agree that search being at the top is ideal, it's not as trivial as drawing it at the top. 

That mockup does not account for mobile or other context generally.

**Comment by brihuang99** [comment]
> While I agree that search being at the top is ideal, it's not as trivial as drawing it at the top.
> 
> That mockup does not account for mobile or other context generally.

No problem, I understand. I'll see about providing some designs that give more context without changing the current UI drastically.

**Comment by brihuang99** [comment]
Here are some of my ideas: 

## Desktop

#### Empty State
![Search 1](https://github.com/stackernews/stacker.news/assets/122472324/60bc6643-7c55-45f3-839d-73c1c45d4846)

#### Search State
![Search 2](https://github.com/stackernews/stacker.news/assets/122472324/aca79f7f-d739-497d-9f5b-46e3242f89fc)


## Mobile

#### Empty State
![Mobile Search 1](https://github.com/stackernews/stacker.news/assets/122472324/ed239c6c-c593-4977-8361-915cb3950756)

#### Search State
![Mobile Search 2](https://github.com/stackernews/stacker.news/assets/122472324/de125546-a9f0-40f1-8cfa-ea6ce5bd58f3)

#### Scrolled State??
![Mobile Search 3](https://github.com/stackernews/stacker.news/assets/122472324/41355f18-1466-42a7-bfcc-395d267aadc8)

I am a little uncertain of the mobile view I have here...it feels rather crowded at the top with the header and the search UI, plus part of me knows that having the search bar fixed at the bottom makes it easier to access on a phone. 

Open to feedback! Here's the [Figma link. ](https://www.figma.com/file/uinnFisxyx3I0N1KbW5xLn/Stacker-News?type=design&node-id=6-2&mode=design&t=OPkqEIzNczthTV2k-4)

**Comment by huumn** [comment]
> .it feels rather crowded at the top with the header and the search UI, plus part of me knows that having the search bar fixed at the bottom makes it easier to access on a phone.

Yeah I agree. We should probably move nav to the bottom on mobile like everyone else does. Tricky tradeoffs in general but your mockups look good!

**Comment by rleed** [comment]
I believe this issue can be closed, right?
