### ISSUE TITLE
Filter markdown in push notifications

### ISSUE THREAD

**Issue by ekzyis** [stackernews/stacker.news#371]
**Is your feature request related to a problem? Please describe.**

Any markdown that is included in a push notification will be displayed raw on clients.

So any link (or any other markdown feature) like `[link text](https://stacker.news/)` will be shown as is.

**Describe the solution you'd like**

Filter markdown in push notifications

**Describe alternatives you've considered**

**Additional context**

- Project which had to solve the same problem: https://github.com/RocketChat/Rocket.Chat/pull/9995/files#diff-3b563da47bb14ac6102c649119eb288b072288a630dcf06acdfcbd1243625db7
- we could also parse markdown to properly include images in push notifications

**Comment by huumn** [comment]
just fyi: we do this already for search and SEO description tags
