### ISSUE TITLE
More push notification types

### ISSUE THREAD

**Issue by ekzyis** [stackernews/stacker.news#372]
**Is your feature request related to a problem? Please describe.**

We currently only have push notifications for zaps, mentions and replies.

Following types are missing:
- cowboy hat
- daily reward
- invites
- deposits
- referrals
- job updates

**Describe the solution you'd like**

Add missing push notification types

**Describe alternatives you've considered**

**Additional context**

**Comment by SatsAllDay** [comment]
@ekzyis Is this still on your radar? I think with LUD-12 support being merged, supporting deposit push notifications would be nice, especially since folks are talking about using them as DMs lol. If you want, we can break that use case out separately if you're working on other items.

**Comment by ekzyis** [comment]
Ahh, ohh, thanks for the reminder. I looked into it but must have gotten distracted with other stuff.

I'll look into it tomorrow again :)
