### ISSUE TITLE
Referrals not working for lightning (and others)?

### ISSUE THREAD

**Issue by ekzyis** [stackernews/stacker.news#375]
**Description**

For some reason, `isNewUser` is always false in the jwt callback on sign up when using lightning and thus `referrerId` is not set

**Steps to Reproduce**

- Create user and set name to `test01` and logout
- Go to `/r/test01` and see `sn_referrer` cookie being set with `test01` as value
- Sign up as new user using lightning

=> `isNewUser` is false in jwt callback and `referrerId` was not set for the new user

**Expected behavior**

`referrerId` is set

**Comment by huumn** [comment]
Got another report that an invite link wasn't recorded for one github login and another email login
