### ISSUE TITLE
Upvote/tip/boost abort/delay window

### ISSUE THREAD

**Issue by abetusk** [stackernews/stacker.news#38]
It would be nice to be able to "undo" an upvote,  tip or boost. From what I understand, the upvote/tip/boost (UpTiBo) represents an actual transaction on the Lightning network which, in my opinion is "the right way", so once the transaction is sent, there's no going back. To try and mitigate a mistaken UpTiBo, the transaction could be delayed for 5s, say, allowing a user to do a 'quick undo' with the understanding that waiting any longer than that will finalize the transaction.

I believe Gmail does something similar, allowing you to 'undo send' of an email by holding it for some number of seconds/minutes before finally pushing it through.

I think most of the time, people will realize their mistake within some short time, like 5s, taking care of 90%+ of the cases where users would want to rescind their UpTiBo.

I would consider this a very low priority, "nice to have" feature and nothing that is significantly interfering with the user (or my) experience.

**Comment by huumn** [comment]
💯 I like the "final and instant settlement"  too and don't want to remove that, but agree it'd be nice to give the user an abort window.

**Comment by ekzyis** [comment]
Done in #857
