### ISSUE TITLE
Warning or disabled/confirmed reply button when submitting a reply past the edit time frame

### ISSUE THREAD

**Issue by llamabyte** [stackernews/stacker.news#383]
I just submitted a reply that had a lengthy addition during the edit period. The reply was submitted but only kept the old pre-edit comment with my additions now lost. 

If there was some sort of warning at the bottom near the submission button, saying that the edit time has run out, i could copy paste into a follow up reply. as it is i would have to scroll up to see that the time has run out.

**Comment by huumn** [comment]
Can you describe the context more? I can't recreate. In both cases my writing is preserved and I'm given an error.

<img width="681" alt="Screenshot 2023-08-08 at 3 16 35 PM" src="https://github.com/stackernews/stacker.news/assets/34140557/5cbaf241-a24a-4275-a77f-c4cee0629a7c">
<img width="778" alt="Screenshot 2023-08-08 at 3 16 51 PM" src="https://github.com/stackernews/stacker.news/assets/34140557/f1eccc4c-73fe-4184-8629-970564cf6b6a">

**Comment by llamabyte** [comment]
So what i think may have happened was that my comment was so long i did not see the warning at the the top. As you can see, a warning does not appear at the bottom. 

![1](https://github.com/stackernews/stacker.news/assets/130471564/d57314ef-ba1a-4341-b9e8-4acf1a6c1b24)

**Comment by huumn** [comment]
Okay, that's a UX bug that we should fix I guess but you also said

> The reply was submitted but only kept the old pre-edit comment with my additions now lost.

I'm concerned about this but I couldn't recreate. How did you lose your additions?

**Comment by ekzyis** [comment]
>> So what i think may have happened was that my comment was so long i did not see the warning at the the top. As you can see, a warning does not appear at the bottom.
>
> Okay, that's a UX bug that we should fix I guess but you also said

Probably fixed by #431

**Comment by SatsAllDay** [comment]
> > > So what i think may have happened was that my comment was so long i did not see the warning at the the top. As you can see, a warning does not appear at the bottom.
> > 
> > 
> > Okay, that's a UX bug that we should fix I guess but you also said
> 
> Probably fixed by #431

Yep!

<img width="594" alt="Screen Shot 2023-08-24 at 3 31 00 PM" src="https://github.com/stackernews/stacker.news/assets/128755788/414ea17e-c8ee-47aa-8f72-e2f18ef895d2">
