### ISSUE TITLE
Twitter login on PWA fails, with Android 13 and Pixel 7 Pro

### ISSUE THREAD

**Issue by cointastical** [stackernews/stacker.news#388]
After launching browser (e.g., Firefox) and then before logging in I install SN ( as a PWA), I cannot then login via Twitter.  The on screen keyboard will flicker but never will stay to allow me to enter username or password.

If I login to SN first, then install SN as a PWA, then I can continue using SN PWA without any issue. At least until I delete all cookies and everything, and nthen try to log in again ... Where I get the same thing, where Twitter login does that on screen keyboard flash again.

**Comment by cointastical** [comment]
Video

**Comment by huumn** [comment]
Weird I'm not sure what would cause that. I'll try to recreate tomorrow
