### ISSUE TITLE
Provide a significant database seed for local dev

### ISSUE THREAD

**Issue by huumn** [stackernews/stacker.news#391]
Ideally we'd do what is called "subsetting" on production data while obfuscating PII.

Looking into this further, we probably want to take prod data and:
1. produce a sample of roughly 20% of the data with https://github.com/mla/pg_sample
2. take the sample then anonymize it *thoroughly* with https://postgresql-anonymizer.readthedocs.io/en/latest/ through [static masking](https://postgresql-anonymizer.readthedocs.io/en/latest/static_masking/)

In general this will be really hard because nothing should be identifiable in the end. Foreign keys will need to be shuffled thoroughly in addition to every column being randomized.

------------------------

Non-ideally, we create a seed from generated values which will lack the "shape" of production data but will make certain classes of contributions easier at least.

**Comment by SatsAllDay** [comment]
+1 to this. I saw the seed.js file in the repo and tried to run it unsuccessfully.
