### ISSUE TITLE
Sub choosing dropdown unselected items are again invisible with dark theme under Google Chrome

### ISSUE THREAD

**Issue by kristapsk** [stackernews/stacker.news#392]
**Description**
Sub choosing dropdown unselected items are again invisible with dark theme under Google Chrome. Not so with Firefox, there everything is ok. Both in main page and new post page.

**Screenshots**
![image](https://github.com/stackernews/stacker.news/assets/4500994/f683b0ed-309b-4a32-930e-1a126a5ee350)

**Environment:**
 - OS: Linux with Xfce4 DE
 - Browser: Google Chrome
 - Version: 114.0.5735.198

**Comment by kristapsk** [comment]
Seems fixed with https://stacker.news/items/223686.

**Comment by ekzyis** [comment]
Yup!
