### ISSUE TITLE
option to turn off red notification indicator.

### ISSUE THREAD

**Issue by llamabyte** [stackernews/stacker.news#396]
I like the notification alert, i'm even curious from a technical perspective how you've managed to do it on a page that appears otherwise static. Facebook has a similar red notificaiton alert for its inbox that i always felt was psychologicaly abusive. We now know that Facebook has over the years designed and timed its various features to trigger and initiate at various points to increase screentime.
Well, the red indicator that appears on the bell and accross all tabs, is triggering Facebook flashbacks. Facebook leaves a lingering distaste for manipulation on online platforms.

 I don't think that is what's happening here at all, but it would be nice to be able to know for sure that that's not what's happening and be able to turn it off in a way facebook does not allow. 

thanks !

**Comment by SatsAllDay** [comment]
As far as how the icon works: https://github.com/stackernews/stacker.news/blob/e913ab71ada66dce0129ae9bff3d56598a616a3f/components/header.js#L60

Dynamic favicon FTW

I'm just a recent contributor, so I can't speak to the intent nor willingness to implement this feature request

**Comment by huumn** [comment]
Please share this post as a ~meta and see if anyone else agrees with you.
