### ISSUE TITLE
Multi-way split for sat forwarding on posts

### ISSUE THREAD

**Issue by SatsAllDay** [stackernews/stacker.news#399]
**Is your feature request related to a problem? Please describe.**
No problem, just an idea I had.

**Describe the solution you'd like**
I think it would be nice if we could enhance the current "sats forwarding" capabilities to allow forwarding sats to multiple users, allowing OP to specify the split/breakdown.

For example, the following splits could be allowed:

1. No forwarding, 100% of sats go to OP
2. 100% of sats go to user 1
3. 50% of sats go to user 1, 50% of sats go to user 2
4. 50% of sats go to user 1, 50% of sats go to OP
5. 40% of sats go to user 1, 40% of sats go to user 2, 20% of sats go to OP

Basically, OP can specify other users to receive a percentage of sats. All other users specified percentages must add up to 100% or less. If less, the remainder goes to OP. Percentage splits should have a precision of 1, meaning no fractional percentages. And perhaps a max number of users to split (5? Implicitly it would be 100 given the integer limitation, but that seems excessive)

**Describe alternatives you've considered**
I don't think there's really any other alternative, aside from OP not doing any forwarding, then manually zapping other users with the sats that OP has earned from the post.

**Additional context**
One consideration is: how would we handle forwarding a quantity of sats that does not evenly divide into the specified splits? Perhaps we `Math.floor` each forward amount, and give the remainder to OP? Should be negligible, but something to think about.

Thoughts? Other considerations?

**Comment by ekzyis** [comment]
I think this would be a great addition. Thanks for the issue! I never took the time to write it down.

**Comment by huumn** [comment]
This has been requested many times. Great to have it written down clearly

**Comment by SatsAllDay** [comment]
I can work on a more technical spec and PR for it. Might take more time than the rest of my PRs so far, but this piques my interest.

**Comment by huumn** [comment]
Excellent, I'd love to see it. 

Off the top of my head, on the backend (hopefully this helpful and not smothering):
- a new db table indicating an `Item` has-many `fwdUser` 
- the item create/update stored procedure need to change 
    - create_{item,poll}, update_{item,poll}
- the item_act stored procedure would need to change
    - this is where we actually modify our internal ledger and consider who gets sats for a zap 

Accomplishing this task would probably make you feel comfortable making nearly any other changes to the codebase.

The trickiest part of working on SN for newcomers is stored procedure stuff right now. We did this originally to get around the lack of transaction isolation in our ORM.

**Comment by SatsAllDay** [comment]
Thank you, that is helpful. It's basically the idea I had in my head but hadn't formalized it yet. But it's good to have pointers to what will need to be impacted. I'll get to work!

**Comment by SatsAllDay** [comment]
Closed by #403
