### ISSUE TITLE
LNURL-auth with Phoenix no longer works

### ISSUE THREAD

**Issue by ekzyis** [stackernews/stacker.news#407]
**Description**

When using Phoenix to login, the backend responds with 500 and this error is logged in the console:

```
app  | - error Failed to handle request for /api/lnauth?tag=login&k1=bc39afa971bfbc961cca0d49f0d5256b330ef1b27987d5d9aaeb69e63512f1b1&sig=3045022100fec2a4a4152c99a70785aeb8753ffa93f37e8fd53cac92d643c457e5d7b31ca10220738046ea8aa822b17c1ef41bcdd74be5bc179062de78affeeb078312cae01e8c&key=03cbf859c4fa54b5f5eb1e55cfadc2aaf663b6b8b6583938dce4bbe2d0688d81c2
app  | TypeError: fetch failed
app  |     at Object.fetch (node:internal/deps/undici/undici:11576:11)
app  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
app  |     at async invokeRequest (/app/node_modules/next/dist/server/lib/server-ipc/invoke-request.js:21:12)
app  |     at async requestHandler (/app/node_modules/next/dist/server/lib/start-server.js:336:33)
app  |     at async Server.<anonymous> (/app/node_modules/next/dist/server/lib/start-server.js:152:13) {
app  |   cause: RequestContentLengthMismatchError: Request body length does not match content-length header
app  |       at write (node:internal/deps/undici/undici:10059:41)
app  |       at _resume (node:internal/deps/undici/undici:10037:33)
app  |       at resume (node:internal/deps/undici/undici:9938:7)
app  |       at [dispatch] (node:internal/deps/undici/undici:9286:11)
app  |       at Client.Intercept (node:internal/deps/undici/undici:9017:20)
app  |       at Client.dispatch (node:internal/deps/undici/undici:7772:44)
app  |       at [dispatch] (node:internal/deps/undici/undici:7991:32)
app  |       at Pool.dispatch (node:internal/deps/undici/undici:7772:44)
app  |       at [dispatch] (node:internal/deps/undici/undici:10556:27)
app  |       at Agent.Intercept (node:internal/deps/undici/undici:9017:20) {
app  |     code: 'UND_ERR_REQ_CONTENT_LENGTH_MISMATCH'
app  |   }
app  | }
```

**Steps to Reproduce**

Use "Login with Lightning" with Phoenix

**Expected behavior**

Login works

**Additional context**

This is probably related to us upgrading NextJS. It might be more adhering to HTTP spec where the `Content-length` header should not be set for GET requests. We suspect it is set with value 0. We did not confirm this though.

Creating this ticket here to track status (I forgot about this error and just encountered this error again). Maybe we need to report this to ACINQ and/or we try to accommodate clients which don't implement the HTTP spec 100%.

**Comment by huumn** [comment]
I think the move is to remove this upstream in nginx or something

**Comment by ekzyis** [comment]
Confirmed that `Content-length` header is set to 0 by Phoenix:

`87.XXX.XXX.XXX GET https://sn.ekzyis.com/api/lnauth?tag=login&k1=1ce277587259d33312a372013f08c89a432022983574c671f9c2dc8744f36af5&sig=3044022040d1951e0bac9036850507e06656cf2a37678122f2cd1629924ed60955141ec202205c9996bf9d2e8a4fc3faed499f2ce41f1754580bca62168a625d6a97eda69246&key=03cbf859c4fa54b5f5eb1e55cfadc2aaf663b6b8b6583938dce4bbe2d0688d81c2 500 0.027ms sent=174 recv=483 Ktor client 0`

This is my nginx log format:

`log_format custom '$remote_addr $request_method $scheme://$http_host$request_uri $status ${request_time}ms sent=$bytes_sent recv=$request_length $http_user_agent $http_content_length';`

Using `proxy_set_header Content-Length ""` for requests to `/api/lnauth` indeed fixes login with lightning.
