### ISSUE TITLE
YouTube player x-overflow

### ISSUE THREAD

**Issue by ekzyis** [stackernews/stacker.news#408]
**Description**

The embedded YouTube player overflows in the x-direction. See screenshot

**Steps to Reproduce**

Visit any SN link post to YT. Example: https://stacker.news/items/119384

**Expected behavior**

No overflow

**Screenshots**

![signal-2023-08-15-034644s](https://github.com/stackernews/stacker.news/assets/27162016/7244b59d-8d10-4e64-9943-7305444f9e20)

![2023-08-15-035003_1920x1080_scrot](https://github.com/stackernews/stacker.news/assets/27162016/a8404236-e987-4076-92d1-37adc9139bff)

**Environment:**

Browser: Chrome on Android, Brave on Linux

**Comment by huumn** [comment]
Ah yeah I noticed too and put it on "the list"

**Comment by ekzyis** [comment]
haha, yes, me too. It's always "I'll create a ticket on desktop"
