### ISSUE TITLE
Custom Date Selector (250,000 Sat Bounty)

### ISSUE THREAD

**Issue by kerooke** [stackernews/stacker.news#410]
**Is your feature request related to a problem? Please describe.**
The tools for filtering content by date on Stacker News are limited, and do not allow people to fully customize their date parameters for top stackers, posts, on user profiles, or on the search page.

**Describe the solution you'd like**
In addition to the existing date filters that allow one to filter by day, week, month, year, or forever, there should be tools that allows anyone to insert custom date parameters to find content on any given date/dates.

People should be able to search for content on a given day, week, month, or year with the ability to scroll between previous periods at the click of a button. This is similar to how [Plausible](https://plausible.io/stacker.news?period=month&date=2023-07-15) allows anyone to segment their site traffic by various custom date options.

This would enable more robust leaderboards and improve access to historical content on SN. 

**Additional context**
For the completion of this feature, Stacker News is offering a 250,000 sat bounty.

**Comment by huumn** [comment]
Hints: 
- backend queries will need to change (hard part):
    -  `/api/resolvers/search.js` (in `search` resolver) ... this is an OpenSearch query 
    -  `/api/resolvers/item.js` (`items` resolver) ... this is a sql query
- this'll require a date range picker on the frontend (tedious part)
- graphql queries will need to be modified to take date ranges (relaxing part)

**Comment by SuperAtic** [comment]
Have been playing around a bit, but I'll be definitely not able to build/code the functionality. Not sure I understand it properly... @kerooke you'd need something like this?
👇

`1.` Select Custom
![Select Custom](https://snipboard.io/SBHch1.jpg)

`2.` Select Custom Date-Range
![Select Custom Date-Range](https://snipboard.io/0zwM9s.jpg)

`3.` Visualize** selected Date-Range as current option on the `select` input
![Visualize selected Date-Range as current option on the `select` input](https://snipboard.io/h9uiH1.jpg)

Hope it helps, and happy to make some changes to the mockup if needed

**Comment by brihuang99** [comment]
> Have been playing around a bit, but I'll be definitely not able to build/code the functionality. Not sure I understand it properly...  @kerooke you'd need something like this?
> 👇
> 
> `1.` Select Custom
> ![Select Custom](https://snipboard.io/SBHch1.jpg)
> 
> `2.` Select Custom Date-Range
> ![Select Custom Date-Range](https://snipboard.io/0zwM9s.jpg)
> 
> `3.` Visualize selected Date-Range as current option on the `select` input
> ![Visualize selected Date-Range as current option on the `select` input](https://snipboard.io/h9uiH1.jpg)
> 
> The date-picked design is obviously just an example. @huumn there's also libraries ([like this](https://www.npmjs.com/package/react-datepicker)) you can might use?
> 
> Hope it helps, and happy to make some changes to the mockup if needed
> 

I think we _might_ need two calendar inputs for a Start Date and an End Date to give users a greater control over the time range they're searching, unless the calendar component can support selecting a range already. 

I'm curious if we're already using a component library or if we'll need to start using one.

**Comment by SuperAtic** [comment]
> I think we _might_ need two calendar inputs for a Start Date and an End Date to give users a greater control over the time range they're searching, unless the calendar component can support selecting a range already. It'll probably depend on whatever library we use.

Yes correct, that's why I place 14-18 Aug in the select menu after the two dates are selected. Another example could be 23 Aug 2021- 22 Aug 2022

**Comment by huumn** [comment]
I imagine we can find a FOSS component that allows this kind of range selection within a single calendar overlay.

**Comment by SuperAtic** [comment]
Yes correct, I shared a link above. I believe there's existing libraries you can use for this common components

[https://www.npmjs.com/package/react-datepicker](https://www.npmjs.com/package/react-datepicker)

**Comment by SatsAllDay** [comment]
Is this issue fully resolved by #494, or is there more remaining?

**Comment by huumn** [comment]
More! We want it to exist for all pages where we do time based filtering, e.g. top, growth, and profile pages

**Comment by rleed** [comment]
I am just now circling back to work on this. I should have status early next week...

**Comment by rleed** [comment]
Virtually done, but I'm stuck on a couple of points... if someone could jump over to the PR and take a look at my two questions on the code, I would much appreciate it.

**Comment by ekzyis** [comment]
I'll try to take a look at this tomorrow :)
