### ISSUE TITLE
Ads V2 Upgrades (400,000 Sat Bounty)

### ISSUE THREAD

**Issue by kerooke** [stackernews/stacker.news#417]
**Is your feature request related to a problem? Please describe.**
The [advertising experiment](https://stacker.news/ad/all) Stacker News began a few days ago has catalyzed the community to provide a bunch of feedback on V1, and it is clear that the community urgently wants an experience that further separates advertising from all other forms of posting on Stacker News.

**Describe the solution you'd like**
For the next iteration of advertising on Stacker News, the following features should be included:
- A new post type that allows advertisers to set how many days their ad will run, and how much they are willing to pay per day. This new ad post type should be placed in the "more types" section of the Post page, next to "Poll" and "Bounty".
- Similar to the feature which is available for promoted jobs, running an ad would automatically pull funds out of the SN wallet associated with the advertisement and give advertisers flexibility over how much they are willing to pay. 
- A toggle button in settings that gives stackers the ability to opt-out of advertisements (and as a result, the portion of daily rewards that are attributed to the advertisers payment).

**Additional context**
There is a 400,000 sat bounty for the completion of this task.

A few more notes:
- It should only be possible to create one ad on the homepage at any given time. That ad should be pinned above the top post on Stacker News. In order to displace the current ad, another advertiser would need to bid a higher amount of sats per day.
- When stackers toggle ads on or off, they will not receive the advertiser-related portion of the daily rewards that day. Beginning the following day, those who had toggled ads on will begin receiving the extra portion of daily rewards.

**Comment by brihuang99** [comment]
Has this issue already been resolved? I'm seeing the 'Ad' tag on mobile at least:

![Screenshot_20230817-091032__01.jpg](https://github.com/stackernews/stacker.news/assets/122472324/137683f3-48b5-476e-bc4f-923c854825b2)

**Comment by huumn** [comment]
Yep, that one is done

**Comment by huumn** [comment]
@kerooke please update the issue to reflect recent changes when you get a chance

**Comment by huumn** [comment]
Closing in favor of our a more iterative approach with auto-boost.
