### ISSUE TITLE
Global Toast mechanism for better feedback

### ISSUE THREAD

**Issue by SatsAllDay** [stackernews/stacker.news#428]
**Is your feature request related to a problem? Please describe.**
There are several actions in SN that don't offer any visual feedback to indicate success/failure e.g.
1. Subscribing to a post
2. Bookmarking an item
3. Probably others

Additionally, in places that do offer feedback, it's usually statically placed on the page. If you're scrolled down too far, like editing user settings or making a post, you don't immediately see the feedback.

**Describe the solution you'd like**
I'd like to propose a global toast system that displays notifications in a fixed position on the screen so that you can see them regardless of your scrolling position on the page.

The toast messages should probably be auto-dismissed, at least for success messages. Maybe not for error, but they should still be dismissable by the user.

As far as styling goes, they can be styled just like how messages are displayed today.

**Describe alternatives you've considered**
N/A

**Additional context**
react-bootstrap has [toasts](https://react-bootstrap.netlify.app/docs/components/toasts/) that we should be able to use, though I haven't explored them yet.

**Comment by ekzyis** [comment]
> 3. Probably others

There is in general no feedback after clicking on anything in the context menu
(except for the OTS timestamps which redirect to a new page):

![2023-08-21-151349_176x166_scrot](https://github.com/stackernews/stacker.news/assets/27162016/e8ecfc52-cf77-4181-9ee7-c40cdbbe4e56)

The menu just closes which can be confusing. Therefore, I agree with this proposal

**Comment by huumn** [comment]
I can think of a few others where it might be useful:

- settings page saves (maybe we can rid ourselves of the 'save' button all together and make it save on change)
- form error/success

**Comment by SatsAllDay** [comment]
> settings page saves (maybe we can rid ourselves of the 'save' button all together and make it save on change)

I like this idea, but it would probably necessitate other changes e.g. checkboxes -> toggles, to provide a better UX aligning with immediate save, IMO anyway.

**Comment by huumn** [comment]
I agree. Not an mvp type change
