### ISSUE TITLE
Convert SN user into a LNDHUB account

### ISSUE THREAD

**Issue by Darth-Coin** [stackernews/stacker.news#429]
**Description**
I know it's a custodial lndhub, but is just fine. It could be very handy for various uses and can be imported into the amazing app Zeus or even Bluewallet as lndhub account or even LNbits as funding source 😂. The options are endless.

I know you are running LND node, but with some tweaks and additional software I think you can convert the SN users into lndhub accounts.

Please consider it.

**Comment by Darth-Coin** [comment]
Don't worry. I know it not easy to implement this feature and takes time.
I post it here, just to have it as a reminder, in the pipeline.

**Comment by Darth-Coin** [comment]
How is the status of this feature?
It is abandoned?

**Comment by ekzyis** [comment]
> You will see that in the end you will come back to my words.

We will see indeed :)

**Comment by huumn** [comment]
While our plan is to eventually remove the custodial wallet, if possible, we could provide a LNDHub interface to the "attached wallets."
