### ISSUE TITLE
LNURL withdraw can return negative numbers

### ISSUE THREAD

**Issue by wbobeirne** [stackernews/stacker.news#430]
*Note: this template is meant to help you report the bug so that we can fix it faster, ie not all of these sections are required*

**Description**

If you have a low balance, LNURL withdrawal can return a negative number for `maxWithdrawable`
```json
{
  "minWithdrawable":1000,
  "maxWithdrawable":-100,
  ...
}
```

**Steps to Reproduce**

1. Withdraw your balance to as low to zero as you can
2. Submit an LNURL withdrawal request

**Expected behavior**

I would either expect the endpoint to 4XX due to lack of balance, or set min & max to zero to indicate you have no balance. I'm not sure what's the typical behavior.

**Comment by huumn** [comment]
Nice catch!
