### ISSUE TITLE
Block height clock

### ISSUE THREAD

**Issue by llamabyte** [stackernews/stacker.news#435]
It's been a year since another user recommended this , so i hope this is not spam.
https://stacker.news/items/22352/r/llamabyte
In this bear market it would be nice have the option to open SN and see the blockheight instead

**Comment by huumn** [comment]
I'm sure mempool.space has an API for this but we could also hit SN's node.

**Comment by SatsAllDay** [comment]
Just to be clear for whoever may work on this, are we looking to implement a user setting that replaces all timestamps in the UI with corresponding block height, or is this to add another item in the "current price" carousel in the page header that displays the current block height? I think the scope of work varies wildly depending on the answer.

**Comment by huumn** [comment]
I think this is just for the price area for now.

**Comment by llamabyte** [comment]
My request was only for adding a BTC timestamp to the current price corrousel. Another user in the notes about this request thought it might be nice to have the option to have each date in the site reflected as the timestamp. Bit intense for me but options are nice.

**Comment by SatsAllDay** [comment]
For others to be aware, I am working on adding the current block height to the price carousel. Just so we can avoid doing any duplicate work :)
