### ISSUE TITLE
ApolloError

### ISSUE THREAD

**Issue by sa70sh1** [stackernews/stacker.news#441]
Hey guys, I am getting this error:
app       | - error Error [ApolloError]: no user has that name
app       |     at new ApolloError (/app/node_modules/@apollo/client/errors/errors.cjs:31:28)
app       |     at /app/node_modules/@apollo/client/core/core.cjs:1947:47
app       |     at both (/app/node_modules/@apollo/client/utilities/utilities.cjs:1239:53)
app       |     at /app/node_modules/@apollo/client/utilities/utilities.cjs:1232:72
app       |     at new Promise (<anonymous>)
app       |     at Object.then (/app/node_modules/@apollo/client/utilities/utilities.cjs:1232:24)
app       |     at Object.next (/app/node_modules/@apollo/client/utilities/utilities.cjs:1240:49)
app       |     at notifySubscription (/app/node_modules/zen-observable/lib/Observable.js:135:18)
app       |     at onNotify (/app/node_modules/zen-observable/lib/Observable.js:179:3)
app       |     at SubscriptionObserver.next (/app/node_modules/zen-observable/lib/Observable.js:235:7)
app       |     at /app/node_modules/@apollo/client/utilities/utilities.cjs:1222:68
app       |     at Array.forEach (<anonymous>)
app       |     at iterateObserversSafely (/app/node_modules/@apollo/client/utilities/utilities.cjs:1222:25)
app       |     at Object.next (/app/node_modules/@apollo/client/utilities/utilities.cjs:1304:21)
app       |     at notifySubscription (/app/node_modules/zen-observable/lib/Observable.js:135:18)
app       |     at onNotify (/app/node_modules/zen-observable/lib/Observable.js:179:3)
app       |     at SubscriptionObserver.next (/app/node_modules/zen-observable/lib/Observable.js:235:7)
app       |     at /app/node_modules/@apollo/client/link/schema/schema.cjs:42:30 {
app       |   digest: undefined
app       | }

**Comment by huumn** [comment]
When?

**Comment by huumn** [comment]
Is this just something you get in your logs?

Or is there other behavior associated with this bug?

**Comment by ekzyis** [comment]
> Is this just something you get in your logs?
>
> Or is there other behavior associated with this bug?

Yes, I think we need some reproduction steps. The current information in the ticket is not enough for us to be able to help you
