### ISSUE TITLE
Subscribe to a user

### ISSUE THREAD

**Issue by SatsAllDay** [stackernews/stacker.news#442]
# Subscribe to a user

As a stacker, I'd like to be notified when another stacker has activity (posts, comments, etc.)

## UX Proposal

Add an overflow menu next to stacker's nym in their profile page with a "subscribe" dropdown item. Toast feedback just like when subscribing to a post

## Technical Proposal

new DB model: `UserSubscription`
```
followerId    Int
followeeId    Int
createdAt     DateTime @default(now()) @map("created_at")
follower      User     @relation(fields: [followerId], references: [id], onDelete: Cascade)
followee      User     @relation(fields: [followeeId], references: [id], onDelete: Cascade)

@@id([followerId, followeeId])
@@index([createdAt], map: "UserSubscription.created_at_index")
```

new gql mutation: `subscribeUser(id: ID)` which toggles the user subscription for the specified user

update the `user` typeDef to include a boolean `meSubscription` field, indicating whether the calling user is subscribed to the target user
update the `user` api resolver to implement the `meSubscription` field using the above model

update the notifications api resolver for the notifications query to also search for items (posts, comments) that are from any followed users.

Question: Introduce a new notification type, or re-use `reply`?

I'm sure there's more details I've overlooked, but this is what I expect it to take to make this happen.

Thoughts? Concerns? Questions?

**Comment by huumn** [comment]
Legit! We'll probably want a new notification type

**Comment by SatsAllDay** [comment]
> People have asked for this.

I basically just think of things I have wanted to do on SN and try to make them happen :P

**Comment by huumn** [comment]
That is the way!
