### ISSUE TITLE
Zap action button should not show in item list if you are a forward recipient

### ISSUE THREAD

**Issue by SatsAllDay** [stackernews/stacker.news#445]
**Description**
With the new multi-forward support, if you are one of the _n_ stackers specified as a recipient of forwarded zaps, the zap action button is visible and actionable any item listing page. The zap fails, as verified by network tab, but it shouldn't be shown at all.

It is not shown on the item full page.

This is probably due to us not loading all forwarded users for non-item-full gql queries.

**Steps to Reproduce**
1. Be forwarded sats for a post
2. View this post on a listing page (home, recent, sub, etc.)
3. View the zap button

**Expected behavior**
Zap button should not be present in this scenario

**Screenshots**
<img width="638" alt="image" src="https://github.com/stackernews/stacker.news/assets/128755788/32a3a4ac-b093-48d9-bc39-e539eabd1f2f">

<img width="648" alt="image" src="https://github.com/stackernews/stacker.news/assets/128755788/f58a76cc-8d6f-4289-8e9d-ef39179bf555">

**Comment by SatsAllDay** [comment]
Why is it that I always find a bug as soon as something's deployed >:|

**Comment by SatsAllDay** [comment]
IIRC we decided not to load forwards on list-views because of the performance implications of going to the DB for all 21 items per page (rightfully so). So maybe we can just show a danger toast if a zap fails instead of silently undoing the zap result locally. This would at least give the user some feedback as to why zapping didn't work, which does explain because they're forwarded sats for the post.

**Comment by huumn** [comment]
> Why is it that I always find a bug as soon as something's deployed >:|

Nothing beats real world data/usage.

> So maybe we can just show a danger toast if a zap fails instead of silently undoing the zap result locally. 

I think we should probably just join `"ItemForward"` in `itemQueryMeta` ... I'll try to fix this today.
