### ISSUE TITLE
"Potato" image quality via proxy

### ISSUE THREAD

**Issue by huumn** [stackernews/stacker.news#451]
Context: https://stacker.news/items/237871

Images of text generally get messed up. We probably need to tune the quality params of the proxy.

**Comment by ekzyis** [comment]
We can tune quality params or/and we can provide the option to view the original image.

For example, I had the idea [here](https://stacker.news/items/247907) to make long press show images in full screen (or at least in a very big modal with the background blurred).

There could then be a link there to the original image.

**Comment by huumn** [comment]
I think we should tune the parameters. By default we shouldn't make text illegible. 

I also like the idea of using srcset if we want to vary the quality depending on the context https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Responsive_images

**Comment by ekzyis** [comment]
We could use this image to test image quality: https://files.ekzyis.com/public/sn/image_proxy_test.png

**Comment by ekzyis** [comment]
Site for sample images in different sizes: https://www.learningcontainer.com/sample-jpeg-file-download-for-testing/
