### ISSUE TITLE
De-dupe notifications

### ISSUE THREAD

**Issue by SatsAllDay** [stackernews/stacker.news#453]
# De-dupe notifications

There are many different kinds of notifications support by SN. Sometimes, one action by a user can trigger several notifications to appear for another user. It would be nice if these were de-duped/aggregated so as to reduce noise and visual clutter.

### Creating a top-level post

* If a user is mentioned in the content of the post, this will trigger a notification for the mentioned user (if enabled)

* If a user is subscribed to the user who posts, this will trigger a notification for the subscriber.

### Replying to a top-level post

* If a user is mentioned in the content of the comment/reply, this will trigger a notification for the mentioned user (if enabled)

* A notification is triggered for a user to which the comment is replying, e.g. the OP of the post, or a parent comment in the reply tree (this is conditional based on whether descendent notifications are enabled)

* If a user is subscribed to the thread upon which the reply is made, this will trigger a notification for the subscriber.

* If a user is subscribed to the user who posts, this will trigger a notification for the subscriber.

## Summary

Based on the above, we can see that the duplicate notifications come when users create items, and when other users are subscribed to the posting user, subscribed to the containing thread, mentioned in the item, or are being replied to in one way or another.

Ideally, we would only dispatch 1 notification per item, as applicable.

How do we represent this notification? I propose a ranking of precedence, in descending order:

1. mentions

2. replies

3. thread subscriptions

4. user subscriptions

In other words, if you are mentioned in an item from a user that you subscribe to, the notification is labeled as a mention. If you are replied to by a user that you subscribe to, the notification is labeled as a reply, etc.

## Technical details

From a technical perspective, as @huumn mentioned [here](https://github.com/stackernews/stacker.news/pull/443#issuecomment-1694722055), we should be able to reduce duplication by performing unions of the sources of dupes, grouped by item id, then unioning with the rest of the notifications.

I'm not sure how exactly we will implement the above order of precedence, but that can probably also be baked in to the SQL queries

### Push notifications

I think once we get the "in-app" notifications sorted, a similar kind of logic should be applied to our push notifications, as well. In other words, let's not spam users with push notifications for one item being created. Perhaps that can come separately, since push notifications aren't widely integrated yet, and getting this work done first would set clear expectations for the push implementation.

### Zapping an item

This isn't actually a source of duplicate notifications, but does have some lacking behavior. It can be addressed separately, IMO.

* When an item is zapped, the creator of the item gets notified (if enabled)

* Note: If the zap is for a post that has forwarding rules configured, the forward recipients _DO NOT_ currently get notified. IMO this is something we should fix

**Comment by huumn** [comment]
Excellent deconstruction. Fully agree with the notification priorities.

> I'm not sure how exactly we will implement the above order of precedence, but that can probably also be baked in to the SQL queries

It can. You'll union mentions, replies, thread subscriptions, and user subscriptions grouping by everything but the notification type. In the select statement, you'll `CASE WHEN type = 'mention' THEN 'mention' ELSE IF type = 'reply' THEN 'reply' ELSE IF type = 'theadsub' ELSE 'follow' END as type`. Then you'll union this sub-union with the other notification subqueries.

> Note: If the zap is for a post that has forwarding rules configured, the forward recipients DO NOT currently get notified. IMO this is something we should fix

I originally did this to deter spamming people with forwards (also a *touch* of laziness). I definitely think this should be implemented though, but you should be able to opt out in settings.

### also

While we're on the topic of forward notifications, I think forwards should also come with implicit thread subscriptions.

**Comment by SatsAllDay** [comment]
> > Note: If the zap is for a post that has forwarding rules configured, the forward recipients DO NOT currently get notified. IMO this is something we should fix
> 
> I originally did this to deter spamming people with forwards (also a _touch_ of laziness). I definitely think this should be implemented though, but you should be able to opt out in settings.
> 
> ### also
> While we're on the topic of forward notifications, I think forwards should also come with implicit thread subscriptions.

I'll open separate issues to address these. I agree with what you've outlined, though.
