### ISSUE TITLE
Toasts in iOS PWA (possibly other mobile contexts) are visually buggy

### ISSUE THREAD

**Issue by huumn** [stackernews/stacker.news#456]
**Description**
When toasts appear on an item feed and I scroll, they don't stay fixed. Sometimes multiple will also appear.

**Steps to Reproduce**
Flag something in the PWA and begin scrolling.

**Comment by SatsAllDay** [comment]
+1, I just encountered this as well. Definitely seems to be some kind of rendering issue, because the duplicate toast isn't clickable.

**Comment by SatsAllDay** [comment]
I tried to recreate this locally and I can't seem to get it to happen when accessing my locally-running SN app. I tried in Chrome, Safari, and both of those installed on home screen as PWA (iOS across the board). Doesn't happen on any of them? So maybe some difference with dev vs prod builds maybe?

**Comment by huumn** [comment]
That's weird. Did you try doing a prod build or just `npm run dev`?

**Comment by SatsAllDay** [comment]
I tried just with `npm run dev`. I am trying a prod build next. 

I am hoping to try [this](https://muffinman.io/blog/ios-safari-scroll-position-fixed/), it seems like maybe a viable workaround. I'll report back here on my findings.

**Comment by SatsAllDay** [comment]
Same results with a prod build, still can't reproduce it locally 🤔

**Comment by huumn** [comment]
Ah it might be because when you interact with an item, it triggers the list to rerender (because the apollo watch query sees the update and updates the items component state).

**Comment by SatsAllDay** [comment]
Maybe, but the toasts are rendered outside the list container's react component tree, so I didn't think that'd be an issue
