### ISSUE TITLE
you have no sats, so this one is on us  .... [ no, wait .... ] you need more sats

### ISSUE THREAD

**Issue by cointastical** [stackernews/stacker.news#460]
Make up my mind.

Do I get to post comments for free or not?

![image](https://github.com/stackernews/stacker.news/assets/60823751/9dcf9ec3-87ff-4977-9b75-fdf9475d23f6)

**Comment by huumn** [comment]
Oh yeah, because your reply is 10 sats it isn't actually free. It only applies to 1 sat replies.

We should remove that freebie message in that case. Nice catch!

**Comment by rleed** [comment]
I'll be taking care of this
