### ISSUE TITLE
Error: Cannot find module '/opt/elasticbeanstalk/deployment/app_version_manifest.json'

### ISSUE THREAD

**Issue by sa70sh1** [stackernews/stacker.news#465]
Hey guys, I am now trying to run it production on a remote server on ubuntu 22.04 

here is an error I am getting after docker-compose up --build

I have modified all .env variables to fit my needs replacing localhost with the server including changing the address in the docker-compose.yml

✔ Generated Prisma Client (5.1.1 | library) to ./node_modules/@prisma/client in 
app       | 712ms
app       | 
app       | 
app       | 
app       | 
app       | 
app       | > stackernews@0.1.0 dev
app       | > NODE_OPTIONS='--trace-warnings' next dev
app       | 
app       | 
app       | - warn You are using a non-standard "NODE_ENV" value in your environment. This creates inconsistencies in the project and is strongly advised against. Read more: https://nextjs.org/docs/messages/non-standard-node-env
app       | - info Loaded env from /app/.env
app       | - error Failed to load next.config.js, see more info here https://nextjs.org/docs/messages/next-config-error
app       | node:internal/modules/cjs/loader:1077
app       |   const err = new Error(message);
app       |               ^
app       | 
app       | Error: Cannot find module '/opt/elasticbeanstalk/deployment/app_version_manifest.json'
app       | Require stack:
app       | - /app/next.config.js
app       |     at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
app       |     at /app/node_modules/next/dist/server/require-hook.js:110:36
app       |     at Module._load (node:internal/modules/cjs/loader:922:27)
app       |     at Module.require (node:internal/modules/cjs/loader:1143:19)
app       |     at require (node:internal/modules/cjs/helpers:110:18)
app       |     at Object.<anonymous> (/app/next.config.js:20:28)
app       |     at Module._compile (node:internal/modules/cjs/loader:1256:14)
app       |     at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
app       |     at Module.load (node:internal/modules/cjs/loader:1119:32)
app       |     at Module._load (node:internal/modules/cjs/loader:960:12) {
app       |   code: 'MODULE_NOT_FOUND',
app       |   requireStack: [ '/app/next.config.js' ]
app       | }
app       | 
app       | Node.js v18.17.0
app       | 
app exited with code 1
dependency failed to start: container app exited (1)

**Comment by SatsAllDay** [comment]
Take a look at [this](https://github.com/stackernews/stacker.news/blob/29d17dce21734d593e530557ae26466dd42f3eb5/next.config.js#L20)

I ran into this issue trying to run the app in prod mode locally, as well.

I think this file is specific to the deployment environment that stacker.news uses, so you might need to wrap it in a try catch to avoid this blocking deployment.

**Comment by ekzyis** [comment]
Do you have to run with `NODE_ENV=production`? This line only runs if you set `NODE_ENV` to `production`

**Comment by huumn** [comment]
The offending line is in next.config.js. It allows us to get the commit hash without having git in prod.

If you're trying to run SN in your own prod environment, change that line to whatever gives you the commit hash.
