### ISSUE TITLE
Push notification for subscribed user post on link post has 'null' body

### ISSUE THREAD

**Issue by SatsAllDay** [stackernews/stacker.news#475]
**Description**
When you are subscribed to a user, and that user submits a link post, the push notification sent includes "null" as the body of the notification. This is because we're trying to fill the notification body with [`item.text`](https://github.com/stackernews/stacker.news/blob/e6ffeb8f763303de9ac881507809c0fdc6cc2053/api/resolvers/item.js#L1205-L1210), which doesn't exist for a link post.

**Steps to Reproduce**
1. Subscribe to a user A
2. Enable push notifications
3. Have User A submit a link post
4. Observer push notification with `null` as body text

**Expected behavior**
Push notification should probably contain the `item.title` for posts, and `item.text` for replies/comments

**Screenshots**
I subscribe to `anon` and got this notification today, which prompted me to open this issue:
![image](https://github.com/stackernews/stacker.news/assets/128755788/4324c75e-8561-4a23-a521-145e18704ef9)

**Comment by ekzyis** [comment]
Interesting, I am subscribed to anon too but got no push notification, lol. Push notifications are still very wonky I guess ...

**Comment by huumn** [comment]
Can confirm. I got this too. iOS.
