### ISSUE TITLE
Require less GitHub permissions to log in

### ISSUE THREAD

**Issue by purrgrammer** [stackernews/stacker.news#48]
First of all thanks for the project, it's pretty cool!

When trying to log in with GitHub I've noticed that it requires **read & write** permission for:
- Private email address
- Profile info
- Followers

I think we could probably relax this a bit to just require reading public data, since it appears that the [login](https://github.com/stackernews/stacker.news/blob/87a6b0278a763dd5a1c9cbe9bacdeccba7bffa90/pages/api/auth/%5B...nextauth%5D.js#L74) is what we are interested in. I might be wrong since I'm not too familiar with `next-auth` so feel free to close this issue if so.

<img width="531" alt="Screenshot 2021-10-04 at 12 01 05" src="https://user-images.githubusercontent.com/42009830/135832171-b173299f-294d-441b-baa9-55dc46b8d578.png">

**Comment by huumn** [comment]
This makes sense. I think this is just the defaults of next-auth but perhaps they can be overridden.

**Comment by huumn** [comment]
Removed the email address requirement. Still need the profile to get username afaik
