### ISSUE TITLE
Auto-rotate setting not respected in PWA on Chrome

### ISSUE THREAD

**Issue by ekzyis** [stackernews/stacker.news#482]
**Description**

Even if I disable "auto-rotate", the SN PWA still rotates if I rotate my phone.

This is super annoying when lying in bed and similar.

The only other PWA that I have is Mutiny and this doesn't happen there.

**Steps to Reproduce**

1. Disable auto-rotate
2. Rotate phone
3. SN PWA rotates

**Expected behavior**

SN PWA does not rotate if auto-rotation is disabled

**Screenshots**

![signal-2023-09-08-145443_002](https://github.com/stackernews/stacker.news/assets/27162016/abb7709b-c3e0-4524-a8fc-c825e88b1273)
![signal-2023-09-08-145443_003](https://github.com/stackernews/stacker.news/assets/27162016/bd70e1b2-75a0-4e90-b438-ec788086adc9)

**Environment:**

Chrome on Android

**Additional context:**

I believe this is the case since the latest manifest changes because of `orientation: 'any'`.

This doesn't happen if I open SN in the browser.

This might be a bug in the PWA implementation of Chrome, not sure. Read [here](https://w3c.github.io/manifest/#orientation-member) for the specs of `orientation`

**Comment by ekzyis** [comment]
> This might be a bug in the PWA implementation of Chrome, not sure. Read [here](https://w3c.github.io/manifest/#orientation-member) for the specs of orientation

@SatsAllDay @huumn Does this happen for you on iOS with Safari, too?

**Comment by SatsAllDay** [comment]
If I lock the orientation on my iOS device, the SN PWA does not rotate if I rotate my phone. Does that answer it?

**Comment by ekzyis** [comment]
Yes, thanks!

Just tested with Firefox. Setting is respected there. 

Tried Brave Browser, settings is not respected there. This makes sense since it's based on Chromium.

Guess I have to use Firefox for the PWA to fix this. This looks like a bug in the PWA implementation to me.

I am surprised no other stacker has mentioned this yet.

**Comment by ekzyis** [comment]
But Firefox does not apply the theme color ...

![signal-2023-09-08-155948](https://github.com/stackernews/stacker.news/assets/27162016/00e8b063-7e3a-4a50-a278-64e4caa2e354)

The web is a mess, lol

**Comment by SatsAllDay** [comment]
> The web is a mess, lol

Welcome to the forefront :P

**Comment by ekzyis** [comment]
lol, I think that the PWA from Chrome does not respect my auto-rotate settings is not a bug. It's probably just that only Chrome supports `orientation`: https://developer.mozilla.org/en-US/docs/Web/Manifest/orientation#browser_compatibility

Maybe `any` is not the correct setting we should use?

**Comment by ekzyis** [comment]
I would propose to just remove `orientation` all together since it's only supported by Chrome and it's experimental.

If you want to rotate, you can still manually rotate or enable the OS setting.

![signal-2023-09-08-161252](https://github.com/stackernews/stacker.news/assets/27162016/e27ba4c8-633c-44cd-b60a-042835f461d4)
_press icon in red circle to manually follow phone orientation_
