### ISSUE TITLE
Account switching

### ISSUE THREAD

**Issue by ekzyis** [stackernews/stacker.news#489]
**Is your feature request related to a problem? Please describe.**

It would be nice if we make it very easy to switch between different accounts.

- stackers could easier maintain multiple nyms 
- companies can easier maintain individual and an official account (like our [official stacker news account](https://stacker.news/sn))

Additionally, it would be nice if we could easily switch to anon without having to log out. But we don't want a real session as anon for privacy reasons (wallet history including invoices would be visible).

**Describe the solution you'd like**

Add a "switch account" option to the user dropdown which then opens up a modal to pick or add another account:

![2023-09-11-215001_182x372_scrot](https://github.com/stackernews/stacker.news/assets/27162016/8572a739-35ae-4c1b-9be8-d0953fea2968)

After clicking on an account, we swap the existing JWT with the one for that account which should be all that is needed to impersonate a different account.

If you want to add another account, you need to verify ownership of that account first (using any authentication method of that account).

If you want to switch to anon, you just click on it and then it looks like you are logged out but clicking on login would show you all available accounts. Clicking on any of these would instantly log you in without new authentication (since we already have the required JWT stored).

**Comment by huumn** [comment]
I looked into this a bit out of curiosity. Twitter stores the other auth tokens in a separate cookie key:

```
twid=<user_id0>
auth_token=<relatively static auth token corresponding to user_id0>
multi_auth=<user_id1>:<auth_token1>|<user_id2>:<auth_token2>...
```

**Comment by ekzyis** [comment]
Mhh, so they don't care about the privacy aspect of this solution: they can know which accounts are linked.

I think a solution where we don't know any links between accounts would definitely be nice.

But not sure on how relevant this is since in theory, if we want, we could use the IP address to link accounts.

So maybe we could use the same solution as twitter since there is not significantly more trust required with the one-to-many cookie solution compared to just looking at IP addresses.

_(I am ignoring networks like Tor or I2P here which don't leak IP addresses.)_

**Comment by huumn** [comment]
I think from a security perspective it's the only thing that makes sense afaik

**Comment by ekzyis** [comment]
A nice unintended side effect of this could be that it's easier to [turn off personalized feeds](https://stacker.news/items/304159)

**Comment by hellmanhellman** [comment]
Isn't it important that you know if accounts are linked? IP isn't necessary, but of course a great part of the fingerprint, which also includes literally every aspect of the user's vocabulary, typing speed, user agent, etc. Just treat the fingerprint like a password and encrypt it clientside. Locality-sensitive hashing can keep the clients unknowable to your records, except for the fact that similar fingerprints will have similar hashes. 
You don't want a botnet bought by Michael Saylor raining down on you screaming Buy tulips! Do you?

**Comment by ekzyis** [comment]
> Isn't it important that you know if accounts are linked? IP isn't necessary, but of course a great part of the fingerprint, which also includes literally every aspect of the user's vocabulary, typing speed, user agent, etc. Just treat the fingerprint like a password and encrypt it clientside. Locality-sensitive hashing can keep the clients unknowable to your records, except for the fact that similar fingerprints will have similar hashes. You don't want a botnet bought by Michael Saylor raining down on you screaming Buy tulips! Do you?

Not sure I understand what you want to say. Did you want to say "Isn't it important that you **don't** know if accounts are linked?"? Then it would make more sense.

> Just treat the fingerprint like a password and encrypt it clientside

Encrypt _what_ clientside using the fingerprint as the "secret key"? The JWTs of the individual accounts? How would encryption even be possible on the client for JWTs inside [HttpOnly cookies](https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies#restrict_access_to_cookies)?

Also, that sounds a lot like "roll your own crypto". [Never roll your own crypto.](https://security.stackexchange.com/questions/18197/why-shouldnt-we-roll-our-own)

> You don't want a botnet bought by Michael Saylor raining down on you screaming Buy tulips! Do you?

I don't understand how this is related to anything before it.

**Comment by ekzyis** [comment]
> I've yet to be convinced that I'm helping professionals here, and your link to "Roll your own crypto" helps little. It seems to me that the end goals of your organization misalign with my own, on a larger scale. Wish you the best out there.

DM'ed you on SimpleX since I am confused by this answer. We're trying to understand what you're saying and engage with your comments but

> I've yet to be convinced that I'm helping professionals here

is not a respectful way to respond. You didn't even respond to any questions I had.

Just FYI, you obviously don't have to engage with us.

**Comment by ekzyis** [comment]
UX question:

If we login into account X, and want to add account Y, we need to authenticate for account Y. This means a login flow within the existing session for X is started. After successful authentication, an additional session cookie for that account is set. Assuming we can now switch out the session cookie the server will use for user actions on the client (thinking about using a cookie which is a pointer to the session cookie we want to use and modifying this "pointer cookie" via JS), this should work fine.

However, the moment we log out, all session cookies are destroyed.

So if we login into account X again, all accounts are lost and we need to add all accounts again.

I think this is bad UX. The accounts should at least show up but we need to authenticate again that we own them.

But this means we need to persist the links in the database, too. So we can show the user which accounts they did link in the past.

But at this point, we could also implement that if you login into X, session cookies for all linked accounts are set. So no need for authenticating that we own Y ever again. But not sure if that's good.

**Comment by huumn** [comment]
Yeah KISS it. fwiw twitter doesn't remember which accounts I've auth'd before
