### ISSUE TITLE
SN wallet integration for seamless payments

### ISSUE THREAD

**Issue by ekzyis** [stackernews/stacker.news#490]
**Is your feature request related to a problem? Please describe.**

We want to let stackers use their SN account more seamlessly with the rest of the Lightning ecosystem.

[Nostr Wallet Connect](https://github.com/nostr-protocol/nips/blob/master/47.md) is one option for this.

LNDHub (#429) is another.

**Describe the solution you'd like**

Support [NIP-47](https://github.com/nostr-protocol/nips/blob/master/47.md)

**Comment by huumn** [comment]
There are many more options for bidirectional flows:
- LNC (lnd)
- WebLN
- Commando (cln)
- Strike API?

Withdrawal only:
- lightning address

**Comment by ekzyis** [comment]
> There are many more options for bidirectional flows:

Yeah, I thought we would track each integration individually but I guess it's better to have them all at one place.

Renamed this ticket now :)

**Comment by huumn** [comment]
We seem to have a number of related tickets for this. It's probably better to list wallet options out individually at this point.
