### ISSUE TITLE
Hidden user feedback on errors in options

### ISSUE THREAD

**Issue by ekzyis** [stackernews/stacker.news#491]
**Description**

I just tried to post something and it didn't work and I got not feedback why:

![2023-09-12-081439_743x368_scrot](https://github.com/stackernews/stacker.news/assets/27162016/ec862f4b-9449-4f24-94a0-2427b626ae86)

Turned out it was because of an error in the options which were collapsed:

![2023-09-12-081633_749x605_scrot](https://github.com/stackernews/stacker.news/assets/27162016/ca6f9c1a-08e3-480a-b7bb-6e3988bde886)

**Steps to Reproduce**

- Create error in options
- Hide options
- Try to post

**Expected behavior**

I get feedback why I can't post even if error is in collapsed options

**Additional context**

The percentage error message is also not displayed correctly below the field

**Comment by huumn** [comment]
> The percentage error message is also not displayed correctly below the field

I fixed this at least

**Comment by benalleng** [comment]
I wonder what we think would be a good UX for this? Do we want the option to display the actual error below it? but this could cause some confusion as seeing "You can't forward to yourself" under `> option` doesn't make much sense IMO. 
I also thought about forcing option open when there is an error
Curious what others think

**Comment by huumn** [comment]
> forcing option open when there is an error

This is the way I think.
