### ISSUE TITLE
nostr: URIs doesn't work in bio

### ISSUE THREAD

**Issue by kristapsk** [stackernews/stacker.news#499]
Was editing my bio - https://stacker.news/kristapsk.

If I change my Nostr description to "nostr:npub1vxpwwydpmmc4usmxf2zkr8shdjq888g532ydyls3nadxxd9wyx5ssjq5nd" (like a proper nostr URI), it becomes hidden and not visible / clickable.

![image](https://github.com/stackernews/stacker.news/assets/4500994/3c6b7e82-ccbc-4c3a-997a-16028edca44c)

![image](https://github.com/stackernews/stacker.news/assets/4500994/acb80b54-309d-4a78-aa7f-fccb5e41c16f)

**Comment by huumn** [comment]
Nice catch! Thanks for reporting

**Comment by tom335** [comment]
Hi, apparently the `remarkDirective` plugins was causing this problem. I've opened a draft PR which can be tested locally for confirmation.

**Comment by SatsAllDay** [comment]
Can this issue be closed? It looks like the net changes from #508 have landed in master.

**Comment by huumn** [comment]
Yep, let's close
