### ISSUE TITLE
SN wallet transactions details

### ISSUE THREAD

**Issue by Darth-Coin** [stackernews/stacker.news#503]
**Description**
Based on my experiment post on SN https://stacker.news/items/259459/ I notice that paying a beer with sats from SN account, it doesn't have enough details to be like a real payment.

**Solution proposal**
Until SN account will be converted into a lndhub account (see #490 ) I would like to see in SN "wallet" section more details for payments done from there (not withdrawals to my own other wallets).

In that thread "Pay it forward" I tried to use as much is possible the sats received from other kind stackers, to pay directly the beers for people joining to this initiative.
I also wanted to give them some kind of proof, posting the payment hash, just in case somebody will come up with complaints that the payment wasn't done or I am some kind of liar.
Some other wallet apps provide this information and is good.

**What I would like to see in SN wallet?**
- payment hash of the tx
- description taken from the payment details. This is good for own tracking later. Or at least a field to add my own notes.
- pre-image (if is not too much)

**Comment by ekzyis** [comment]
We could add a collapsible section for every invoice as was done for lightning zaps from nostr in https://github.com/stackernews/stacker.news/pull/368

but just a bit prettier, not a raw JSON

**Comment by SatsAllDay** [comment]
We can just decode the bolt11 to get this info, right?

**Comment by huumn** [comment]
> We can just decode the bolt11 to get this info, right?

Yep

**Comment by SatsAllDay** [comment]
Broadcast for others, I am planning to look into this issue sometime in the next few days.
