### ISSUE TITLE
Add OpenSearch to docker setup for development

### ISSUE THREAD

**Issue by rleed** [stackernews/stacker.news#505]
Searching SN posts in the development environment isn't supported out-of-box. We need to add an OpenSearch instance in its own container to provide the back-end search functionality.

**Comment by rleed** [comment]
Do we have existing index and mapping definitions that can be used to initialize the OpenSearch instance?

**Comment by huumn** [comment]
Mapping should happen automatically. The index called `item` will need to be created in some kind of initialization step, but that's it.
