### ISSUE TITLE
Image links are messed up in satistics

### ISSUE THREAD

**Issue by ekzyis** [stackernews/stacker.news#507]
https://github.com/stackernews/stacker.news/assets/27162016/dc5d4767-aa4c-4110-8917-3b38944682b4

**Comment by huumn** [comment]
They're being truncated by the looks of it

**Comment by SatsAllDay** [comment]
Is this still happening? I tried to reproduce it in prod and can't seem to get it to happen.

**Comment by huumn** [comment]
Oh this was unintentionally fixed when we shipped the image changes. Closing!
