### ISSUE TITLE
Allow unsubscribing from our own threads

### ISSUE THREAD

**Issue by huumn** [stackernews/stacker.news#512]
Occasionally a thread will fork into a tangent and I want to tune it out. 

MVP is probably just allowing us to unsubscribe from *our* own post/comment.

Ideally, we can unsubscribe from *any* child comment ... that way we can unsubscribe from just the tangent.

**Comment by rleed** [comment]
> Ideally, we can unsubscribe from _any_ child comment ... that way we can unsubscribe from just the tangent.

I've given this some thought... I think a general solution would easily become prohibitively expensive. I think we need to restrict this feature for example by saying all unsubscriptions will take precedence (meaning you can't arbitrarily nest unsubscriptions and subscriptions). Your thoughts?
