### ISSUE TITLE
Quote reply option

### ISSUE THREAD

**Issue by SatsAllDay** [stackernews/stacker.news#516]
**Is your feature request related to a problem? Please describe.**
If I want to reply to multiple parts of someone's item (post or comment), I need to copy-paste their text into the reply input, annotate it with quote markdown (`>`), then go from there.

**Describe the solution you'd like**
I'd like a "quote reply" action that can be taken which copies the quoted item into the reply, automatically annotated with quotation markdown syntax. This action could live in the item overflow menu so as to avoid visual clutter.

**Describe alternatives you've considered**
Alternative is as I described above: manually copy-paste and annotate by hand.

**Additional context**
https://stacker.news/items/264216/r/WeAreAllSatoshi

See GitHub's implementation: 
<img width="284" alt="image" src="https://github.com/stackernews/stacker.news/assets/128755788/6ea4774e-7e95-4eb8-b43a-efae35e0dfbe">

**Comment by rleed** [comment]
What do you think about adding the `quote` option right next to the `reply`, like so:
![image](https://github.com/stackernews/stacker.news/assets/101502594/422fb1fb-94c4-42bb-8e05-b015d54ee154)

Maybe this could set the stage for a future enhancement to make the buttons dynamically appear on hover instead of being always present on every post? Just exploring ideas...

**Comment by SatsAllDay** [comment]
I'll defer to @huumn regarding the UX, but I do think a quote button _could_ work there.

I should have mentioned it on this issue, but I did start working on this today. @rleed If you've already gotten pretty far, I can stop working on it and let you finish it off. Let me know!

**Comment by rleed** [comment]
I have bandwidth so was looking at it, but I first wanted to know if the UI was decided for sure. Anyway, go ahead since you've started...

**Comment by huumn** [comment]
It should be in the overflow `...` for now. No more new buttons please

**Comment by ekzyis** [comment]
> I'd like a "quote reply" action that can be taken which copies the quoted item into the reply, automatically annotated with quotation markdown syntax. This action could live in the item overflow menu so as to avoid visual clutter.

I think it would also be nice if you can create partial quotes. What's funny is that I came up with this idea looking at how I usually quote stuff. Then I thought "what if we can select text and then click `quote reply` and it only quotes that part". Then I realized that's also what Github does:


https://github.com/stackernews/stacker.news/assets/27162016/cd51378e-3ae7-4838-95d8-1251c04c1e03

**Comment by SatsAllDay** [comment]
Whoa, cool! I did not know that was possible.

I only had quoting the entire item in mind, but this would be a nice extension. I'll see about incorporating it in my PR (#526)

**Comment by ekzyis** [comment]
I think a hotkey for this would also be nice.

So you only need to select stuff and then can press CTRL+Q to quote that part. Hotkeys are implemented in `components/form.js`.

**Comment by SatsAllDay** [comment]
> I think a hotkey for this would also be nice. Then you can select stuff and then press CTRL+Q to quote that part.
> Hotkeys are implemented in `components/form.js`.

That would be cool. I might try it in my current PR, or maybe that can come as a follow-up. I'm kinda going back and forth between quote reply and LUD-18 right now :)

**Comment by ekzyis** [comment]
> or maybe that can come as a follow-up

yeah, follow-up is fine, too
