### ISSUE TITLE
Autowithdrawl to lightning address

### ISSUE THREAD

**Issue by huumn** [stackernews/stacker.news#524]
Basically allow lightning addressed people to autowithdrawl their account balance from SN.

This could work a number of ways, but we probably want it to leave some sats in wallet. Options:

A. conditionally, e.g. withdrawal anything over 12k sats, leaving 10k sats, and paying a max fee of 50 sats
B. unconditionally, e.g. always attempt to withdrawal any balance, even if it's just 1 sat, paying a max fee of 10 sats
C? direct funding, e.g. don't hold my sats at all and zap me directly

C is probably a little wacky to do if we want to take our zap sybil fee, but we might be able to cook up something with hold invoices. It's also unclear what to do on failure.

**Comment by ekzyis** [comment]
> C? direct funding, e.g. don't hold my sats at all and zap me directly
> C is probably a little wacky to do if we want to take our zap sybil fee

Maybe we could use routing hints? As if the user uses a private channel with us. Then we could take our zap synbil fee as a routing fee

**Comment by huumn** [comment]
If routing hints can specify a fee explicitly then that would work.

**Comment by ekzyis** [comment]
> The elements contained in the field `r` are commonly referred to as _routing hints_. They allow the receiver to communicate an extra set of edges that may help the sender complete their payment. The hints are usually used when the receiver has some/all private channels, and they wish to guide the sender into this "unmapped" portion of the channel graph. A routing hint encodes effectively the same information that a normal `channel_update` message does. The update is itself packed into a single value with the following fields:
>
> The `pubkey` of the outgoing node in the edge (264 bits)
>
> The `short_channel_id` of the "virtual" edge (64 bits)
>
> The base fee (`fee_base_msat`) of the edge (32 bits)
>
> The proportional fee (`fee_proportional_millionths`) (32 bits)
>
> The CLTV expiry delta (`cltv_expiry_delta`) (16 bits)
>
> The final portion of the data segment is the set of feature bits that communicate to the sender the functionality needed to complete a payment. As an example, if a new payment type is added in the future that isn’t backward compatible with the original payment type, then the receiver can set a required feature bit to communicate that the payer needs to understand that feature to complete the payment.

-- [_Mastering the Lightning Network_, Chapter 15](https://github.com/lnbook/lnbook/blob/develop/15_payment_requests.asciidoc)

So I believe this could work.

However, there is one problem:

_The receiver_ has to add the routing hints since they create the invoice. Since I am not aware of any wallet that supports configuring routing hints - that's also how wallet companies like Muun and ACINQ make their money afaik so it's probably actually against their interests -, this autowithdrawal feature would only work with routing hints if the stackers have full control over their nodes and good knowledge to use "advanced" features like configuring routing hints.

But assuming they added the routing hints with the appropriate proportional fee, the payment would route through us and, we could take the sybil fee as a routing fee.

The flow could be like this:

- A wants to zap B 1 sat on SN for a good meme
- SN requests invoice from B's node
- SN verifies invoice includes routing hints including fees
- we show that invoice to A
- A pays
- Payment routes through us and we take the sybil fee
- B receives payment
- We can show the payment on SN (since we were paid our fee)

Another downside may be that B needs to have a channel open with us. But I am not 100% sure on that. Maybe routing hints can just be used as a pit stop? So A would need  to find a route to SN and we would need to find a route to B. Which is naturally way easier if B has a channel with us.

**Comment by huumn** [comment]
This would require us setting these fees statically on some number of channels right?

What if we wrapped the receivers invoice in a hold invoice with our own hints that go through our node?

**Comment by ekzyis** [comment]
> This would require us setting these fees statically on some number of channels right?

Mhh, I believed the fee in the routing hint is independent of fees configured per channel. As I understood it, the routing hint is like announcing a channel just for this invoice so you can set any fee.

But yes, the existing static channel fees may make things more complicated.

> What if we wrapped the receivers invoice in a hold invoice with our own hints that go through our node?

So A would pay us and then we would pay B? Settling the invoice with A when the payment to B was successful and else cancelling it?

That sounds really promising, I like that!

**Comment by huumn** [comment]
I guess we'd need to determine if a hint is just a hint or a requirement.

> So A would pay us and then we would pay B? Settling the invoice with A when the payment to B was successful and else cancelling it?

What I'm thinking is something exactly like https://lnproxy.org/ which manages to take an arbitrary fee by "wrapping" the original invoice in a hold invoice to itself.

**Comment by TonyGiorgio** [comment]
The route hints won't force the sender to route through you. It's just including additional hops that might not be on the graph. 

The wrapped invoice method would work, but you have to be absolutely sure you won't lose money doing it.

**Comment by TonyGiorgio** [comment]
The route hints won't force the sender to route through you. It's just including additional hops that might not be on the graph. 

The wrapped invoice method would work, but you have to be absolutely sure you won't lose money doing it.

**Comment by ekzyis** [comment]
> The route hints won't force the sender to route through you. It's just including additional hops that might not be on the graph. 
> 
> The wrapped invoice method would work, but you have to be absolutely sure you won't lose money doing it. 

Ahh, makes sense. Thanks for clarifying it!

**Comment by huumn** [comment]
> The wrapped invoice method would work, but you have to be absolutely sure you won't lose money doing it.

I suspect the concern here is outgoing route to the receiver could fee-jack you. We'd probably want the receiver to tell us how much they're willing to pay in fees upfront and take those fees unconditionally and failing the payment if a route can't be found <= the set fee.

**Comment by huumn** [comment]
Aside from failure UX (which is definitely tractable), the only other hard part to the hold invoice method is we now have to get really serious about managing liquidity and connectedness.

**Comment by TonyGiorgio** [comment]
The concern is you're glueing multiple payments together. I'd highly advise not doing this if you're unsure of how you'd lose money by doing such a thing.

**Comment by huumn** [comment]
You're right, I haven't studied the money losing scenarios when "gluing multiple payments together." I'm top of dome discussing this.

afaik money loss would happen on the route outgoing to the final receiver. If you're implying there are other, less obvious ways, then we'll do our best to find them before implementing.

**Comment by TonyGiorgio** [comment]
Yes, the money being received by the final recipient but you being unable to redeem the payment made to you. But I guess it also depends on if you actually want to implement the same payment hash in the wrapped invoice, that would make it trustless. However, naively you can implement it without invoice wrapping and just normal invoices that you always have the preimage to so you can redeem at any time if needed.

The problems mostly come with making sure your program can always settle the payment under these scenarios and more: 

1. Restarts (service or lnd)
2. Internet disconnections
3. Stuck payments on the 2nd part
4. Make sure the 2nd timelock is always longer than the first, long enough for you to manually settle issues

You never want one side to settle without the other, and you're not in control of when the final recipient settles it, only the max amount of time when they can settle it.

**Comment by huumn** [comment]
That's very helpful thank you! (I wish there were zaps on github.)

It sounds like the problems are a near 1-to-1 map of all the problems lightning nodes solve on a normal route and because we're getting in-between that we'll have to re-solve all those issues.
