### ISSUE TITLE
Worker is broken when not run with tsx

### ISSUE THREAD

**Issue by huumn** [stackernews/stacker.news#525]
@ekzyis I deployed the esm changes to the worker and eventually learned it was failing to start because of module issues. There are no version discrepancies between prod and dev.

I was able to get it to work by running the worker with [tsx](https://www.npmjs.com/package/tsx) in 51299820 but I'm not sure why. I also had to manipulate some imports to get it working even then.

I thought it was working locally but I might have failed to rerun the worker and you might be failing to fully restart your docker env (the worker does not hot reload) on your end.

I might've change stuff when doing other changes since your esm pr, but I don't think so.

**Comment by ekzyis** [comment]
I think we can continue using `tsx` and update imports since the worker then also no longer requires the annoying JS extension and then close this ticket?

![2023-09-27-181415_389x709_scrot](https://github.com/stackernews/stacker.news/assets/27162016/a73ed937-5f19-4fae-892e-93c480d251d8)

**Comment by huumn** [comment]
I see. I guess it's not worth removing tsx if it's going to cause this problem to crop up again. 

I still had to `import * as pkg from '../fragments/...'` to get it to work with tsx, but making fragments a module made it complain about `@apollo/client` being commonjs. 

We could probably get this working properly using some kind of webpack config but maybe not worth it if we plan to spin the worker out anyway.

This esm crap is such a mess. I'll close.

**Comment by ekzyis** [comment]
> maybe not worth it if we plan to spin the worker out anyway.

wdym with "spin the worker out anyway"? as a microservice?

**Comment by huumn** [comment]
Yes!
