### ISSUE TITLE
Provide category tag per item containing the sub in the 'home' RSS feed

### ISSUE THREAD

**Issue by PMK** [stackernews/stacker.news#528]
**Is your feature request related to a problem? Please describe.**
I'm using the RSS feeds to get the latest posts. The user can select a specific sub, or it defaults to the home RSS feed. To determine the active sub, you can parse the URL. However, in the 'home' RSS feed all subs are visible in random order.

**Describe the solution you'd like**
To determine the sub per item in the 'home' RSS feed, I would like to see the `<category>` tag being used. This tag will contain the name of the sub per item. Optionally, a 'domain' attribute can be provided with the full URL to the sub as the attribute's contents. This tag is part of the [RSS 2.0 specification](https://www.rssboard.org/rss-specification#ltcategorygtSubelementOfLtitemgt).

**Additional context**
In `lib/rss.js` the `generateRssFeed()` function gets a list of items and separately the sub. Here the category tag could also be used for all RSS feeds but the 'home' feed to provide the sub for all items at once. The `generateRssItem()` function gets only the item object. Does this item object contain the sub as well (as in `item.sub`)? Then it can be added conditionally if it is available. The link tag off the channel part of the RSS feed should be a function so it can be reused in `generateRssFeed()` and in the attribute 'domain' of the category tag in `generateRssItem()`.

**Comment by huumn** [comment]
Great recommendation! Thanks
