### ISSUE TITLE
mention autocompletes

### ISSUE THREAD

**Issue by huumn** [stackernews/stacker.news#529]
It'd be nice in a post or comment when `@`ing someone to have some help getting the spelling right.

**Comment by SatsAllDay** [comment]
Any specific UX in mind for this?

**Comment by SatsAllDay** [comment]
I _very quickly_ whipped up this. I haven't even checked the code in, it's so rough lol but is this sorta what you're looking for? 

https://github.com/stackernews/stacker.news/assets/128755788/dd37b2bb-5fd4-4621-8c61-5839f0bda969

**Comment by ekzyis** [comment]
What I had in mind - inspired by Github again:

- immediately shows up after pressing @ _(not sure, maybe only show after 2-3 characters in?)_
- you can use arrow keys   
- you can use tab to select
- does not show up if anything comes before @ like this x@ 
- also shows up if you press backspace and cursor is next to @ again
- does not show up if you use arrow keys or mouse to move cursor next to @


https://github.com/stackernews/stacker.news/assets/27162016/8700b84e-6a77-4073-9773-ecd27e0299f9

i would also prefer if it shows up next to the cursor and the first entry is marked as selected. this makes it more clear that arrow navigation and tab completion is possible imo

**Comment by SatsAllDay** [comment]
Great feedback! I had most of this in mind, just hadn't gotten there yet. Thank you for formally writing it all out, I think that's very helpful

**Comment by huumn** [comment]
> Top stackers in some timeframe

I like top stackers

> Most mentioned users in some timeframe

Those poor souls lol
