### ISSUE TITLE
Mentioning yourself results in a push notification

### ISSUE THREAD

**Issue by ekzyis** [stackernews/stacker.news#537]
I don't think this should happen, lol

**Comment by SatsAllDay** [comment]
I'll work on this one, should be pretty straight-forward.

Side note: should we even create mentions in the DB when we mention ourselves? Skipping the push notification is simple, but I wondered if the mentions should exist at all.

**Comment by huumn** [comment]
They shouldn't exist really ... I think I just assumed no one would do that ... but even sane usage might lead someone to quote a mention of themselves

**Comment by SatsAllDay** [comment]
Yea, that makes sense. 

As far as I can tell, mentions are on used for notifications to the mentionee. And we also filter out self mentions in those queries, so I don't see any reason to create them in the DB. My PR makes that change.

**Comment by ekzyis** [comment]
> but even sane usage might lead someone to quote a mention of themselves

yes, in my case, I think I just quoted a reply in which I was mentioned
