### ISSUE TITLE
Images are not centered in fullscreen on Firefox 

### ISSUE THREAD

**Issue by ekzyis** [stackernews/stacker.news#539]
_Firefox:_
![2023-10-02-215600_1920x1080_scrot](https://github.com/stackernews/stacker.news/assets/27162016/e71a1249-0011-45b3-a33e-bdf70f625f4a)

_Brave:_
![2023-10-02-215544_1920x1080_scrot](https://github.com/stackernews/stacker.news/assets/27162016/cb1f0acf-b913-4097-9fa6-720f5752bcfe)

_even crazier shift to the left in Firefox (not sure how this happened):_
![2023-10-02-220426_1920x1080_scrot](https://github.com/stackernews/stacker.news/assets/27162016/c47c48d7-f035-4634-a28a-5535376882fc)

Context: https://stacker.news/items/272832

**Comment by huumn** [comment]
Weird! The must not fully support grid `place-content` yet

**Comment by ekzyis** [comment]
Seems like they do, it works with `display: flex` and `place-content: center` but not without `place-content: center`:

_`display: flex` + `place-content: center`:_
![2023-10-02-222926_1920x1080_scrot](https://github.com/stackernews/stacker.news/assets/27162016/414163ed-3418-412a-a043-e7f5b75877a6)

_`display: flex` w/o `place-content: center`:_
![2023-10-02-222931_1920x1080_scrot](https://github.com/stackernews/stacker.news/assets/27162016/024d2986-231c-4bf4-9e79-14243a4ddad5)

See fix in #540
