### ISSUE TITLE
subs

### ISSUE THREAD

**Issue by huumn** [stackernews/stacker.news#54]
Subreddit like feature. I'm not sure what to name these yet (child, substackers?), but many users have asked for them.

**Comment by huumn** [comment]
A few thoughts I've had in the background of my mind:

1. I want these to be recursive -- i.e. subs can have subs
2. Substacker is the intuitive name, but it's a mouthful. I like that it's self referential. Other names: block, topic, kid, economy, state, nation ...
3. I think these should exist at the top-level path, e.g.`stacker.news/<substacker name>` ... it increases the odds of colliding with usernames but I suspect this is not too bad. It also would be intuitive for users who want following both subs and other users.
4. Economics
    - creator of the sub sets the "economic policy" and earns 50% of the revenue the sub generates
    - they set: cost to post, min comment cost, and upvote cost
    - by setting the policy, they are tuning sybil resistance and their returns

**Comment by trosel** [comment]
It sounds like there's two different goals at play here. 

1. organizing posts
2. supporting unique communities

I think adding simple tags like they have on [lobsters ](https://lobste.rs/) would solve goal 1

**Comment by huumn** [comment]
Tags is a nice short term solution for 1, you're right, but if we want to ever do 2, we might as well just have subs. I think subs unlock a lot of cool potential stuff like alternative post types, e.g. maybe there's a sub that only allows media posts, or job board sub, or a product hunt like sub, etc.
