### ISSUE TITLE
Limit visible portion of post/comment body and 'click to view more'

### ISSUE THREAD

**Issue by huumn** [stackernews/stacker.news#549]
On even a very large screen, https://stacker.news/items/275618 is 5+ view heights. On mobile, I suspect it's 2x that.

If you are trying to navigate to the comments, it's pretty crappy to scroll so much.

We should visually truncate the text to ~2vh for posts and maybe ~1vh for comments then provide a 'click to view full'.

Ideally this is done using CSS so there isn't vertical layout shift.

**Comment by huumn** [comment]
Even with [the checkbox hack](https://css-tricks.com/the-checkbox-hack/) this is probably done with js.

We'll just to reserve enough vertical space to be able to remove the 'read more' without causing layout shift when the page simply loads.

**Comment by ekzyis** [comment]
This would be a feature for the comments from [unpaywall](https://stacker.news/unpaywall) which are still quite large on mobile.
