### ISSUE TITLE
AbortError: Registration failed - push service error

### ISSUE THREAD

**Issue by Sebastix** [stackernews/stacker.news#574]
**Description**
Push notifications have never worked on my side since it got implemented. 

Screen record displaying the issue: https://shares.sebastix.dev/xQbB15i7.mp4

**Environment:**
If you only experience the issue on certain devices or browsers, provide that info.
 - Device: Macbook
 - OS: MacOS
 - Browser: Brave Browser
 - Version: 1.59

Any idea how to fix this? :)

**Comment by ekzyis** [comment]
Did you check this box?

![2023-10-19-125923_1920x1080_scrot](https://github.com/stackernews/stacker.news/assets/27162016/23040fa6-e07d-4716-84eb-cfb7b59c4461)

**Comment by Sebastix** [comment]
> Did you check this box?
> 
> ![2023-10-19-125923_1920x1080_scrot](https://user-images.githubusercontent.com/27162016/276588358-23040fa6-e07d-4716-84eb-cfb7b59c4461.png)

Ah, nope it's unchecked. And for a reason! I don't like spyware ;-) 
Thanks for pointing out the cause, I will close this issue.
