### ISSUE TITLE
Allow both zap and flag on an item

### ISSUE THREAD

**Issue by SatsAllDay** [stackernews/stacker.news#578]
**Is your feature request related to a problem? Please describe.**
Sometimes users change their mind about an item after having zapped it, but they currently can't flag an item after having zapped. This feature request is to allow flagging an item after having zapped it. 

**Describe the solution you'd like**
I'd like to be able to flag an item even after I've zapped it. 

**Describe alternatives you've considered**
I don't think you can do much since you can't un-zap an item, so it's pretty stuck right now. 

**Additional context**

https://stacker.news/items/291085/r/WeAreAllSatoshi

Side note: should we also allow the inverse? In other words, allow you to unflag and subsequently zap an item you've flagged? AFAICT that's also not currently possible.

**Comment by huumn** [comment]
> should we also allow the inverse?

There have been occasions when people ask for the inverse, so yes
