### ISSUE TITLE
Surface timestamps in wallet history UI

### ISSUE THREAD

**Issue by SatsAllDay** [stackernews/stacker.news#583]
**Is your feature request related to a problem? Please describe.**
I often look for when certain events occurred in my wallet history. The data is there in the API call but it's not surfaced in the UI. It would be nice to have an option to see this on the page, especially for invoices and withdrawals 

**Describe the solution you'd like**
Timestamps for wallet history events surfaced in some way. If we don't want to add another column to the table, it could be a tooltip that surfaces the info on click. 

**Describe alternatives you've considered**
The only alternative I've found is to explore the API data directly. 

**Additional context**
This is probably most useful for invoices, withdrawals, and spent events. Earned events are rolled up to the most recent earning per item, so while it's kinda useful, it's not as useful as the others, IMO.

**Comment by huumn** [comment]
This would be great. Many people have asked for this

**Comment by SatsAllDay** [comment]
Any thoughts on UX? Tooltip per row? Extra column in the table? Control the column via checkbox?

**Comment by huumn** [comment]
We have more vertical space than horizontal in this view.

I think it'd be best to put the full time under the detail for each entry.

![Screenshot 2023-10-24 at 1 32 55 PM](https://github.com/stackernews/stacker.news/assets/34140557/e9a5407c-8076-425e-8dd9-40dd01660381)

**Comment by SatsAllDay** [comment]
I'll work on this one. I imagine it should be pretty straight-forward.
