### ISSUE TITLE
few feature requests when trying to run docker-compose locally

### ISSUE THREAD

**Issue by ralyodio** [stackernews/stacker.news#592]
Need more info on how to setup wallet in .env.sample comments

I have a btcpayserver running, but I don'jt know where to find these values.

ability to modify port number service listens on. i'm behind nginx and can't use port 3000 as its already used.

when using getalby extension to login via nostr the callback url goes to localhost:3000 not my domain name.

**Comment by ekzyis** [comment]
> I have a btcpayserver running, but I don'jt know where to find these values.

[We recommend](https://github.com/stackernews/stacker.news/blob/master/docs/local-lnd.md) using [polar](https://lightningpolar.com/) to setup some LN nodes in regtest. Keep in mind that you don't want to run a LN node on mainnet for development purposes. Not sure if you're running a BTCPayServer on mainnet or testnet/regtest/signet.

> ability to modify port number service listens on. i'm behind nginx and can't use port 3000 as its already used.

You can run `npm run dev -- -p 3001` to run on port 3001

> when using getalby extension to login via nostr the callback url goes to localhost:3000 not my domain name.

you need to configure `PUBLIC_URL`
