### ISSUE TITLE
Use Badging API to indicate notification status on PWA

### ISSUE THREAD

**Issue by SatsAllDay** [stackernews/stacker.news#594]
**Is your feature request related to a problem? Please describe.**
I'd like to know when I have SN notifications from my home screen via native notification badges

**Describe the solution you'd like**
Basically I want a non-numeric notification badge on the PWA app icon on my home screen, similar to the red indicator on the notification bell within the SN app, and on the favicon.

**Describe alternatives you've considered**
None

**Additional context**
[Badging API MDN docs](https://developer.mozilla.org/en-US/docs/Web/API/Badging_API)

**Comment by huumn** [comment]
I've been wanting this!

**Comment by SatsAllDay** [comment]
I'll start working on it as my next item. It might help me learn more about service workers too.
