### ISSUE TITLE
QR code scanner for withdraw

### ISSUE THREAD

**Issue by ekzyis** [stackernews/stacker.news#598]
**Is your feature request related to a problem? Please describe.**

During an experiment of @Darth-Coin, some issues with the wallet were discovered. Most of them were handled in #503 but I believe one is still missing: to be able to pay QR code invoices with the SN wallet.

**Describe the solution you'd like**

Allow scanning of invoices with a QR code scanner.

**Additional context**

UX could be like this:
![2023-11-03-154419_1920x1080_scrot](https://github.com/stackernews/stacker.news/assets/27162016/5a33b600-6392-40fa-8912-91459db2781b)

After clicking the camera icon, a camera view is opened and the user can scan a QR code. On successful scan, the invoice is entered into the text field and the camera view is closed.

**Comment by ekzyis** [comment]
Going to work on this now since I believe this is an essential feature and a good foundation for upcoming work on the wallet like #533 and #490 where QR codes might also need to be scanned.

**Comment by Darth-Coin** [comment]
Please also look into LN-auth QR code. Maybe is related.
I was reporting this foe weeks now.

If you try to login with Alby extension in a browser, just by clicking the QR code image, is getting an error. but if you copy and paste the lnbc... code into alby is working to login just fine.
It must be something with the link generated for the QR code.

**Comment by ekzyis** [comment]
Need to fix my Alby extension first. Reinstalling didn't help:

![2023-11-03-163244_1918x1059_scrot](https://github.com/stackernews/stacker.news/assets/27162016/ec88f729-5ff7-4362-8598-a95600f99088)

Created another ticket for this "login with Alby" issue: https://github.com/stackernews/stacker.news/issues/599
