### ISSUE TITLE
Login with Alby via QR code does not work

### ISSUE THREAD

**Issue by ekzyis** [stackernews/stacker.news#599]
**Description**

_Reported by @Darth-Coin:_

When trying to login with the Alby extension and clicking the QR code, the following error message is shown:

![photo_2023-10-14_09-29-20](https://github.com/stackernews/stacker.news/assets/27162016/3d63c398-97cd-4dee-a792-47f19db18bfe)

But pasting `lnbc...` into Alby works fine.

**Expected behavior**

LNURL-auth via QR code works with Alby extension

**Comment by Darth-Coin** [comment]
hmmm just test it and still the same error. I don't know now what to think.
I also notice that with latest alby extension I cannot zap anymore in Primal.
