### ISSUE TITLE
display balance on wallet page

### ISSUE THREAD

**Issue by ndalliard** [stackernews/stacker.news#6]
i know that the second number besides my name (`nathanael [2,1]`) means that i have one satoshi, but i think on the wallet page it is useful to also display the balance above the two buttons (fund / withdraw)

btw. there is a little typo: withdraw and not withdrawl (for the withdraw button on the wallet page)

**Comment by huumn** [comment]
Good idea. It’ll make things more obvious

**Comment by huumn** [comment]
Done. The typo is still there but it's not actually a typo - I spelled withdrawal wrong everywhere so I need to change it everywhere to withdraw.
