### ISSUE TITLE
CORS error loading font from CDN in prod

### ISSUE THREAD

**Issue by SatsAllDay** [stackernews/stacker.news#601]
**Description**
The following error shows up in the JS console:
```
Access to fetch at 'https://a.stacker.news/Lightningvolt-xoqm.ttf' from origin 'https://stacker.news' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```
Other fonts load fine, so perhaps some config based on the file extension? Not sure, just spitballing.

**Steps to Reproduce**
1. Load stacker.news in browser
2. Check browser console for error

**Expected behavior**
Fonts to load successfully w/o CORS errors

**Screenshots**
N/A

**Logs**
Included above

**Environment:**
Chrome on macOS, haven't tried others

**Additional context**
N/A

**Comment by huumn** [comment]
Oh there's a typo in `next.config.js`! Nice catch.

**Comment by SatsAllDay** [comment]
> Oh there's a typo in `next.config.js`! Nice catch.

Ah

```diff
- tff
+ ttf
```

👍
