### ISSUE TITLE
Make clientside error boundary work

### ISSUE THREAD

**Issue by huumn** [stackernews/stacker.news#609]
Currently our error boundary doesn't actually catch the error and nextjs shows it's default - which is totally nondescript.

Ideally, it would show our error boundary but ALSO:

Display a copy-on-click textarea of the error details so people can send it to us.

**Comment by SatsAllDay** [comment]
I can look at this one.

**Comment by SatsAllDay** [comment]
Did you verify this in production, or just in local dev? I ask because I found [this thread](https://github.com/vercel/next.js/discussions/44926) that basically indicates in dev mode, the default dialog/overlay takes over regardless of whether there's an error boundary.

**Comment by huumn** [comment]
Verified not working in prod

**Comment by SatsAllDay** [comment]
Is this the kind of thing you see in prod?

<img width="686" alt="image" src="https://github.com/stackernews/stacker.news/assets/128755788/5b7e5109-e6a4-43e1-954b-6c47d351721b">

**Comment by huumn** [comment]
Yep!

**Comment by SatsAllDay** [comment]
So I made this change locally, and also in an override file for prod (making changes to minified code is so fun!), and it _seems_ to work now:

```diff
diff --git a/pages/_app.js b/pages/_app.js
index e41b9c1..81b6145 100644
--- a/pages/_app.js
+++ b/pages/_app.js
@@ -96,7 +96,9 @@ export default function MyApp ({ Component, pageProps: { ...props } }) {
                       <ToastProvider>
                         <ShowModalProvider>
                           <BlockHeightProvider blockHeight={blockHeight}>
-                            <Component ssrData={ssrData} {...otherProps} />
+                            <ErrorBoundary>
+                              <Component ssrData={ssrData} {...otherProps} />
+                            </ErrorBoundary>
                           </BlockHeightProvider>
                         </ShowModalProvider>
                       </ToastProvider>

diff --git a/pages/~/post.js b/pages/~/post.js
index efb26e0..68a8d9e 100644
--- a/pages/~/post.js
+++ b/pages/~/post.js
@@ -12,6 +12,7 @@ export const getServerSideProps = getGetServerSideProps({
 })
 
 export default function PostPage ({ ssrData }) {
+  throw new Error('f')
   const router = useRouter()
   const { data } = useQuery(SUB, { variables: { sub: router.query.sub } })
   if (!data && !ssrData) return <PageLoading />

```

<img width="646" alt="image" src="https://github.com/stackernews/stacker.news/assets/128755788/77219c5f-aaf0-416d-999c-dc5c613c4934">

This just doesn't seem right to me, though. I don't see why the error wouldn't have bubbled through the context providers, but evidently it was not making it to the ErrorBoundary higher in the tree?

**Comment by huumn** [comment]
That's so weird. I wonder if there's an error boundary in one of the other providers that's somehow interfering. 

That doesn't make sense entirely though because the error somehow still hits Next's error boundary.

**Comment by SatsAllDay** [comment]
> That's so weird. I wonder if there's an error boundary in one of the other providers that's somehow interfering.
> 
> That doesn't make sense entirely though because the error somehow still hits Next's error boundary.

Yea, doesn't make sense to me. I'll continue to investigate!

**Comment by SatsAllDay** [comment]
I think I figured it out in #623 , though it still doesn't totally make sense to me.
