### ISSUE TITLE
Search fuzzy matches are scored too highly

### ISSUE THREAD

**Issue by felipebueno** [stackernews/stacker.news#617]
I explicitly searched for "brazil" but 90% or more of the results were for "brain" 

![image](https://github.com/stackernews/stacker.news/assets/241271/76bc6065-a3b8-459c-97cb-d1b87e459f10)

**Comment by huumn** [comment]
Yeah looks to be favoring fuzzy matches too much. Thanks!

**Comment by huumn** [comment]
I just fixed this. I'll deploy it in the next release

Thanks so much for flagging this! It prompted me to make search results **_WAY_** better

**Comment by felipebueno** [comment]
> Thanks so much for flagging this! It prompted me to make search results WAY better

Anytime, Keyan!
