### ISSUE TITLE
Dupes detection over-triggers for Youtube

### ISSUE THREAD

**Issue by notnout** [stackernews/stacker.news#62]
Pasting any youtube video will highlight any other youtube video as a dupe. It would be good to use the query param "v" to check for uniqueness.

**Comment by huumn** [comment]
Yep also happens with hacker news.

**Comment by huumn** [comment]
Deploying the fix now. 

Whitelists GET params for: www.youtube.com/watch, news.ycombinator.com/item, and bitcointalk.org/index.php ... and is more robust generally.
