### ISSUE TITLE
Link NOSTR - Internal server error redirect

### ISSUE THREAD

**Issue by ncryppt** [stackernews/stacker.news#621]
When trying to use the "Link NOSTR" feature in the settings, I get redirected to a blank page with "internal server error" message displayed. This happens after alby wallet pops up (chrome extension).

To reproduce:
- Alby chrome extension connected to npub
- Click link nostr in settings

internal server error redirect URL: https://stacker.news/api/auth/error?error=%0AInvalid%20%60prisma.lnAuth.update()%60%20invocation%3A%0A%0A%0AAn%20operation%20failed%20because%20it%20depends%20on%20one%20or%20more%20records%20that%20were%20required%20but%20not%20found.%20Record%20to%20update%20not%20found.

![2023-11-09 09 05 14](https://github.com/stackernews/stacker.news/assets/66481391/8d97e8dc-10f1-4860-9c36-dda66c77ee98)

**Comment by huumn** [comment]
Thanks for reporting! I'll look at this today

**Comment by ncryppt** [comment]
@huumn tried out again on mac this time (still chrome). Also got an error but a little different this time.

![Screenshot 2023-11-11 at 11 40 51 AM](https://github.com/stackernews/stacker.news/assets/66481391/840f04ad-e500-47f4-b86e-9682caec8444)
![Screenshot 2023-11-11 at 11 41 04 AM](https://github.com/stackernews/stacker.news/assets/66481391/e967c7f6-a623-4572-8087-b01802fec0f2)
![Screenshot 2023-11-11 at 11 41 17 AM](https://github.com/stackernews/stacker.news/assets/66481391/e2516a9a-4748-4a13-b85a-ed95af509fa9)

**Comment by huumn** [comment]
I've been able to reproduce in prod but not locally. I'll try to fix it today.

**Comment by huumn** [comment]
I didn't get to this today again. It'll be my first things tomorrow morning

**Comment by ncryppt** [comment]
awesome :)

**Comment by huumn** [comment]
I think I fixed this. Please let me know it it's still broken

**Comment by ncryppt** [comment]
I am still getting an error. No redirect this time though.
![Screenshot 2023-11-12 at 2 00 48 PM](https://github.com/stackernews/stacker.news/assets/66481391/1f477561-72d8-47f0-bb38-94f09309b60a)

**Comment by huumn** [comment]
Is it linked to another account maybe?

**Comment by ncryppt** [comment]
Only linked to 1 npub / nsec. Might be an issue with alby itself?

**Comment by huumn** [comment]
I meant, do you have another SN account that might be using the same keypair?

**Comment by huumn** [comment]
If that's the case, you'll just want to unlink it from that account so it can be associated with your real one.

**Comment by ncryppt** [comment]
Confirmed that was the problem! I feel like an idiot lmao, complete forgot about that second account.
Thanks for everything @huumn !

**Comment by ekzyis** [comment]
> I feel like an idiot lmao, complete forgot about that second account.

Nah, our error messages aren't good.

But I wonder how we could improve it to catch such mistakes without leaking any data? Could we just mention all kinds of common errors?

But I can only recall that trying to link an auth method which was already linked to another account happened before. Not sure if that already counts as "common" or whatever "common" errors there are we could mention.

Just brainstorming, error messages are definitely not my strength, haha

**Comment by ncryppt** [comment]
Maybe could add a line to the auth fail message along the lines of "Auth failed. Try another method / double check that [x auth method] isn't linked to another SN account"

**Comment by huumn** [comment]
It's supposed to tell you that. It must be losing the error details somewhere
