### ISSUE TITLE
Style calendar for custom date selector consistent with the rest of the UI

### ISSUE THREAD

**Issue by huumn** [stackernews/stacker.news#624]
It currently uses the stock styling from the package and doesn't support darkmode.

**Comment by kantakshay** [comment]
hello, 
would like to solve this issue can provide any image or video for a better understanding of the issue

**Comment by ekzyis** [comment]
Hey! Thanks for your interest in contributing to SN :)

If you go to https://stacker.news/search?q=test&when=custom and click into the date range, you should see the calendar that was added in #567 for custom date selection:

![2023-11-13-050106_1920x1080_scrot](https://github.com/stackernews/stacker.news/assets/27162016/6cc90aa1-e207-400a-9af2-7e63ae4cb395)

![2023-11-13-050056_1920x1080_scrot](https://github.com/stackernews/stacker.news/assets/27162016/b7879e79-d5a6-4f22-9d21-ffb8ce788ae4)

As you can see, the calendar currently uses the stock styling from the package and doesn't support darkmode.

So this ticket is about changing that.
