### ISSUE TITLE
Allow twitter embeds

### ISSUE THREAD

**Issue by huumn** [stackernews/stacker.news#63]
A lot of users are sharing links to Bitcoin Twitter. It'd be nice to embed the tweet.

**Comment by cointastical** [comment]
I see now when using Chrome, for an SN post that is a Twitter link, there is an embed that now renders.  So this feature is live. 

However, this embed doesn't work on Firefox (at least, not when checked using Firefox v96).

**Comment by huumn** [comment]
Works for me on Mac with v96.0.3

**Comment by cointastical** [comment]
Ok, I see a reason that I am encountering the issue and you might not.

 I use Private Window feature of Mozilla Firefox. I'm presuming it is loosely similar to "Incognito mode" with Chrome.

So to replicate the issue:

- From Firefox, press Ctrl+Shit+P
- visit https://Stacker.News/items/8993

Wait a few moments, .... no Twitter Embed will appear.

I actually have "Private" mode made permanent:
Settings -> Privacy & Security, then under History I selected Never remember history

When I change that to Remember history, and Firefox restarts, then the URL will load the Twitter embed, matching what your screenshot shows. 

So, I don't know how many people will encounter this -- with Firefox having a [small minority of the browser market share](https://en.wikipedia.org/wiki/Usage_share_of_web_browsers#Summary_tables), (e.g., under 10%) and of that, even fewer would be running in Private mode, probably there will not be very many users impacted.

**Comment by huumn** [comment]
It works in incognito in Chrome. I suspect firefox disallows iframes in private mode which this requires.

**Comment by cointastical** [comment]
Is it possibly a bug in TweetEmbed (from react-tweet-embed)?

I can see embedded Tweets in Private mode on Firefox when rendered using the Twitter widget:

https://publish.twitter.com/?query=https%3A%2F%2Ftwitter.com%2Fkollider_trade%2Fstatus%2F1486765296031522826&widget=Tweet

**Comment by huumn** [comment]
I get a link to this in my console when private browsing on firefox https://developer.mozilla.org/en-US/docs/Web/Privacy/Tracking_Protection ... It looks like it assumes the embed is a tracker.
