### ISSUE TITLE
Add latest tx fees to page header price carousel

### ISSUE THREAD

**Issue by SatsAllDay** [stackernews/stacker.news#640]
**Is your feature request related to a problem? Please describe.**
No existing problem, I just had the idea of displaying the latest fee rate as one of the price carousel options, alongside price, block height, etc. I thought this would be an interesting metric to see since lately the on-chain fees have been pretty high

**Describe the solution you'd like**
Another option that shows the fee rate for the most recent block. I assume we can get this from SN's node via LND but I have not investigated further.

**Describe alternatives you've considered**
N/A

**Additional context**
https://stacker.news/items/315636/r/WeAreAllSatoshi

**Comment by huumn** [comment]
That'd be fun! They are just so crazy right now

**Comment by SatsAllDay** [comment]
I think this is done, right?

**Comment by ekzyis** [comment]
> I think this is done, right?

_nothing to see here_
