### ISSUE TITLE
Tab autocompletion doesn't work

### ISSUE THREAD

**Issue by ekzyis** [stackernews/stacker.news#641]
https://github.com/stackernews/stacker.news/assets/27162016/299afdb1-1951-406c-9526-8e1dfce24396

**Comment by huumn** [comment]
This might be fixed now. It was difficult to recreate reliably for me.

Give it a shot on master and let me know.

**Comment by ekzyis** [comment]
Works, good job!

**Comment by huumn** [comment]
Oh lol commented on the wrong issue. I meant the to comment on this one: https://github.com/stackernews/stacker.news/issues/646

**Comment by ekzyis** [comment]
Mhh, can't reproduce it locally either, neither on 5cf3a42 or on d211fe9. I believe it's related to network latency, but can't reproduce it with throttling either.

However, I noticed that on d211fe9, the dropdown is below the cursor:

![2023-11-22-044027_1920x1080_scrot](https://github.com/stackernews/stacker.news/assets/27162016/0c28efc4-3c0c-448f-93f6-5d7aa1958eae)

but on 5cf3a42, it's below the text input:

![2023-11-22-044051_1920x1080_scrot](https://github.com/stackernews/stacker.news/assets/27162016/7532b68b-21bb-4514-8f5d-5ef5254c5006)

is this intended?
