### ISSUE TITLE
Mention autocomplete dropdown race condition

### ISSUE THREAD

**Issue by ekzyis** [stackernews/stacker.news#646]
**Description**

sometimes, when typing on mobile, the dropdown shows up but then you continue typing but it doesn't disappear after a space.

and sometimes, when you select a user, the user is put at the front instead of where the cursor is

**Steps to Reproduce**

If you enter Space too fast, the dropdown stays open. And if you then select something, it gets pasted at the front of the text:

https://github.com/stackernews/stacker.news/assets/27162016/f304ddd8-d809-4443-9771-3d38a7ca6cc4

**Expected behavior**

Consistent behavior

**Additional context**

probably a race condition somewhere

https://stacker.news/items/322254

**Comment by ekzyis** [comment]
_continuing conversation from https://github.com/stackernews/stacker.news/issues/641#issuecomment-1821999733 here:_

Mhh, can't reproduce it locally either, neither on 5cf3a42 or on d211fe9. I believe it's related to network latency, but can't reproduce it even with throttling.

However, I noticed that on d211fe9, the dropdown is below the cursor:

![2023-11-22-044027_1920x1080_scrot](https://github.com/stackernews/stacker.news/assets/27162016/0c28efc4-3c0c-448f-93f6-5d7aa1958eae)

but on 5cf3a42, it's below the text input:

![2023-11-22-044051_1920x1080_scrot](https://github.com/stackernews/stacker.news/assets/27162016/7532b68b-21bb-4514-8f5d-5ef5254c5006)

is this intended?

**Comment by huumn** [comment]
Not intentional. That’s weird. Works fine for me in Brave

**Comment by huumn** [comment]
Actually it didn't work for me in brave. I wasn't sending the styling to the component.

Fix is live. Closing this one because I fixed the race.
