### ISSUE TITLE
Feature Idea: In top section add top "comments"  tab

### ISSUE THREAD

**Issue by notnout** [stackernews/stacker.news#65]
Currently the "top" section includes only posts with drilldowns in different timeframes. 
It would be cool to add another tab that shows top comments (I don't we need the time-based drilldowns - all-time top comments would probably be enough :) )

This would help with discoverability of some cool content and hidden gems in the comment threads. I haven't thought through the downsides though.

**Comment by huumn** [comment]
I like this idea. I've been trying to figure out how to incentivize commenting more. Making them more easy to discover is a good way.
