### ISSUE TITLE
Zapping and reply buttons not working on iPhone 7

### ISSUE THREAD

**Issue by codyellingham** [stackernews/stacker.news#656]
**Description**
On iPhone 7 "Reply" and Zap buttons are not clickable and do not work. Profile page stacker.news email addresses are also not clickable. There may be other things not working either.

**Steps to Reproduce**
Go to any thread with this device to reproduce.

**Expected behavior**
Should be able to reply and zap.

**Screenshots**
N/A

**Logs**
If applicable, add your browsers console logs.

**Environment:**
If you only experience the issue on certain devices or browsers, provide that info.
 - Device: iPhone 7
 - OS: iOS 15.8
 - Browser: Brave

**Additional context**
Other users have reported this same issue:
[https://stacker.news/items/328115/r/chungkingexpress](https://stacker.news/items/328115/r/chungkingexpress)

**Comment by huumn** [comment]
Pushing a fix for this now. Please reopen if the issue continues.
