### ISSUE TITLE
Back button at the bottom of PWA

### ISSUE THREAD

**Issue by aChrisYouKnow** [stackernews/stacker.news#665]
**Is your feature request related to a problem? Please describe.**
I find myself using the website version more than the Progressive Web App as it can be annoying to scroll back to the top to get to the back button each time, especially in posts with lots of comments. 

**Describe the solution you'd like**
A way to return to the territory feed from inside a post without scrolling back to the top of the page. 

**Describe alternatives you've considered**
Other options could be a floating back button that is always within view. Or a gesture such as swipe the page to one side to go back. Or a back button at the bottom of the page so when you reach the bottom, you can return without going back to the top.

**Comment by aChrisYouKnow** [comment]
I'm on iOS 17, on an iPhone 13 mini. The browser has a back button, but not in the PWA. No back button at the bottom, just the SN back arrow in the top left.

**Comment by huumn** [comment]
While I agree this would be better at the bottom, we don't have somewhere to place the button at the bottom, and if we don't like reaching to the top left, we can swipe right.
