### ISSUE TITLE
Question: How does the wallet work exactly?

### ISSUE THREAD

**Issue by trosel** [stackernews/stacker.news#67]
Is the server creating one custodial *Lightning channel* per user? And then when I tip another user, it goes from me to the server and then from the server to the user?

Or is the server creating one custodial *wallet* per user and then also somehow managing Lightning liquidity from me to every other user I want to tip?

**Comment by huumn** [comment]
User custodial wallets are virtual. I create an abstraction layer over a single lightning wallet, ie the SN's node, that manages user balances which are stored in that single wallet.
