### ISSUE TITLE
Withdrawal invoices are showing as deleted despite not having enabled the feature

### ISSUE THREAD

**Issue by SatsAllDay** [stackernews/stacker.news#672]
**Description**
My withdrawal invoices are showing as deleted in my wallet history, even though I have not ever enabled the auto-delete invoice user setting.

**Steps to Reproduce**
1. View invoices in wallet history

**Expected behavior**
1. Expect invoices to not be deleted if I haven't enabled the feature.

**Screenshots**
N/A

**Logs**
N/A

**Environment:**
N/A

**Additional context**
https://stacker.news/items/344715/r/WeAreAllSatoshi

**Comment by huumn** [comment]
fixed in 0d5ef11 

fortunately it was just a display issue (and not data loss). Thanks!

**Comment by ekzyis** [comment]
lol, I just got out of bed because I wanted to see how fast I can fix this ... well well :)
