### ISSUE TITLE
Ampersands in URLs getting messed up

### ISSUE THREAD

**Issue by ekzyis** [stackernews/stacker.news#673]
[This bug almost drove me crazy](https://stacker.news/items/344921)

https://github.com/stackernews/stacker.news/assets/27162016/14ab0c06-d8eb-465e-b886-35e2fa088b89

**Comment by huumn** [comment]
Related https://github.com/stackernews/stacker.news/issues/606

**Comment by ekzyis** [comment]
confirmed fixed in 7c49aa5
