### ISSUE TITLE
Reward across multiple days is confusing

### ISSUE THREAD

**Issue by nostrangerdev** [stackernews/stacker.news#677]
**Description**
Today I received the daily reward, but a minute after the amount was reduced.

I received 1140 today and my balance reflected that, but now the amount in the wallet history dropped to 904 in both my history and balance.

**Steps to Reproduce**
Check the wallet and notification immediately after receiving, check if it changes after a while.

**Expected behavior**
The amount should stay the same and not be reduced after.

**Screenshot**
Notification:
![IMG_20231210_081306](https://github.com/stackernews/stacker.news/assets/147932744/d5cd5c43-e0bd-43b4-ba9f-e2929ce82822)
Wallet history:
![IMG_20231210_081249](https://github.com/stackernews/stacker.news/assets/147932744/48106593-5a20-44fc-ad47-35f43ffdf001)

**Additional context**
Noticed for the first time, not sure if it happened before.

Is there any amount shared with territories owners? If it is, it should be shown on a separate notification.

**Comment by huumn** [comment]
That reward notification is summarizing your rewards across multiple days, 12/9-12/10. Click on it for a break down across multiple days

**Comment by huumn** [comment]
Multiple people have been confused by this though so we probably need to summarize this in a less ambiguous way.

**Comment by nostrangerdev** [comment]
I see, but why has the wallet's total balance changed too?

Is it based in the aggregation?

**Comment by huumn** [comment]
Your wallet balance shouldn't change as the result of rewards. It should only go up as the result of rewards.

You can see all the sources of spending/stacking by looking at your wallet history. If there's discrepancy after you review that, let me know.

**Comment by nostrangerdev** [comment]
That's what made me notice the issue.

After I received the reward the balance was around 4000 and then it stopped to around 3800 with the change in the notification.

Also I just received today's rewards and it seems to be correct.

**Comment by huumn** [comment]
So when you look at your wallet history there's no - zero - spending but your balance went down?

What's your nym? I can look for myself if you can double check and confirm you spent nothing to explain the difference.

**Comment by nostrangerdev** [comment]
Yes, I did zap two comments the same day but it was after the issue, I didn't do anything before sharing the issue.

The screenshots attached show the latest entries at the time.

Anyway, my nym on SN is `nostranger`.

**Comment by nostrangerdev** [comment]
After double checking, with the 80 sats spent later in the day, they still won't add up to the 4000 I was before the issue with the notification.

**Comment by huumn** [comment]
I just did a full manual accounting on your wallet. It checks out to the millisat:

```
Rewards: +22691497
Zaps earned: +22752900
Invoices paid/funded: +250000
Fee or zaps sent: -16375000
Donations given: -4830000
Withdrawals: -20404933
-------------------------
current balance: 4084464 msats (ie 4084 sats)
```

**Comment by ekzyis** [comment]
Sorry to intervene but I just wanted to mention it might be good to just stop merging the reward notifications until we found a better solution since this has confused quite some people already.

**Comment by huumn** [comment]
That assumes they were merged for no reason

**Comment by nostrangerdev** [comment]
Thanks @huumn for the trouble, so basically the balance was wrong when I received the notification and it updated to the correct value.

I haven't checked the code but maybe it was a wrong sum on the frontend side?

**Comment by nostrangerdev** [comment]
Personally, I think the aggregation could be more readable if it respects the interaction with the notifications.

For example, it adds the amount until it is seen, then it adds as a separate aggregate until seen again later.

Or maybe simpler, it can just show everything separately and then aggregate everything on a daily basis for easier viewing of post events.

What do you think?

**Comment by ekzyis** [comment]
> I haven't checked the code but maybe it was a wrong sum on the frontend side?

According to our current limited understanding and iirc, there was and is no wrong sum on the frontend

> Personally, I think the aggregation could be more readable if it respects the interaction with the notifications.

Interesting, makes sense

**Comment by huumn** [comment]
We send a notification for each reward day now. Thus this is resolved.
