### ISSUE TITLE
Logout from /satistics results in 500: Internal Server Error

### ISSUE THREAD

**Issue by sgornick** [stackernews/stacker.news#68]
A request with the path /satistics results in an HTTP 500 - Internal Server Error when not logged in.

This error will show also after logging out from that satistics page. 

How to replicate:
1. Log in via any method
2. Click link showing your @Username in top right corner, then from drop-down click: profile 
3. From your profile, click link for: satistics
4. From /satistics page, click link showing your @Username in top right corner, then from drop-down click: logout

Expected behavior:
Response to logout expected would be for path to change to the home page (/), or perhaps a message saying /satistics requires login, or something like that.

Actual behavior:
Page with the title "500: Internal Server Error" and the body having contents: "500 | Internal Server Error" -- no login button, nothing else.

Related:
In addition to /satistics, the following URLs do not handle being logged out (or post-logout condition) well:

- https://stacker.news/settings
- https://stacker.news/wallet
- https://stacker.news/wallet?type=fund
- https://stacker.news/wallet?type=withdraw
- https://stacker.news/notifications

**Comment by huumn** [comment]
Nice! Thanks for reporting!

**Comment by huumn** [comment]
Deploying the fix now. Redirects to / on logout.
