### ISSUE TITLE
Notifications for posts in your own territory

### ISSUE THREAD

**Issue by NEEDcreations** [stackernews/stacker.news#681]
I'd like to receive a notification when a user makes a post in a territory that I own. I don't believe I am currently being notified by that. Thanks!

**Comment by huumn** [comment]
Welcome to the feature request fast lane 😄

**Comment by TonyGiorgio** [comment]
I would very much like this, as it's hard to tell when someone has posted in my territory. I often use the PWA more than the website, and the territory navigation is painful on mobile.

**Comment by ekzyis** [comment]
> I would very much like this, as it's hard to tell when someone has posted in my territory. I often use the PWA more than the website, and the territory navigation is painful on mobile.

I didn't get to it yesterday unfortunately but since I am working on push notifications anyway currently (#411) and I also would love to see this, I will _definitely_ look into this today.
