### ISSUE TITLE
"Read more" button sometimes does not show up

### ISSUE THREAD

**Issue by ekzyis** [stackernews/stacker.news#687]
[@Onions](https://stacker.news/onions) keeps complaining to me in SimpleX DMs that there is a bug with "Read more" where it doesn't show up. Then I told him: "Why don't you just create a ticket and help us helping you?"

Then I realized, he already told me he has no Github account, lol. So I said sorry, I am going to create one now and here I am, creating this ticket for him.

For example, he goes to preview, and then he can't see everything because it's hidden and there isn't even that button (happens only sometimes, I think).

I just had this bug on my own profile even since my profile isn't even that long but it still seemed to want to display the button but there was no button.

Probably a race condition somewhere.

_Github should really allow anon tickets, lol. Can't expect everyone to have an account on here._

**Comment by ekzyis** [comment]
caught the bug:

https://github.com/stackernews/stacker.news/assets/27162016/d11620e4-3517-4ddb-9748-4444507c7afc

**Comment by huumn** [comment]
This might be fixed now

**Comment by ekzyis** [comment]
Ok will let you know if it happens again within a week

Since I think it did happen frequently enough that if it doesn't happen in a week, it's probably fixed and we can close it :)

Thanks for the fix!

**Comment by huumn** [comment]
I think this is ultimately related to images causing the container height to change after they load. My more recent fix observes the container size for changes which I think solves this once and for all.
