### ISSUE TITLE
Only view posts that have at least X amount of sats invested in them

### ISSUE THREAD

**Issue by huumn** [stackernews/stacker.news#690]
@benthecarman requested a "cowboy hats only" mode as a way to filter out people only sharing content to farm sats or "assmilk" as DarthCoin puts it. I think having a sat threshold is more generic and useful.

This should probably only be applied to `recent` to start which suffers from this the worst.

It should be available in settings and default to `0` ... this would replace `freebie` mode as `freebie` mode basically means `investment=0`

What we mean by X amount of sats invested: 
- the item cost >=X sats to post
- or the item has >=X sats zapped to it
- or the item has >=X sats of boost

**Comment by ekzyis** [comment]
Ideas for the setting name:

- saloon mode

_(I assume this is going to be just another setting like greeter and wild west mode)_
