### ISSUE TITLE
ip4r extension must be installed for migrations to apply

### ISSUE THREAD

**Issue by ekzyis** [stackernews/stacker.news#692]
**Description**

Since https://github.com/stackernews/stacker.news/commit/a5e50821b7e0dba0400a5f8ada6d3741a92de9d3, migrations no longer apply cleanly. You now get an error that the [ip4r extension](https://github.com/RhodiumToad/ip4r) is missing

```
Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma
Datasource "db": PostgreSQL database "stackernews", schema "public" at "localhost:5431"

Error: P3006

Migration `20231212235400_ofac` failed to apply cleanly to the shadow database.
Error:
ERROR: could not open extension control file "/usr/share/postgresql/13/extension/ip4r.control": No such file or directory
   0: sql_schema_connector::validate_migrations
           with namespaces=None
             at schema-engine/connectors/sql-schema-connector/src/lib.rs:324
   1: schema_core::state::DevDiagnostic
             at schema-engine/core/src/state.rs:270
```

**Steps to Reproduce**

1. Run postgres via docker using container defined in _docker-compose.yml_
2. Run migrations

**Expected behavior**

Migrations apply

**Comment by ekzyis** [comment]
I tried to fix this for now in my local setup by simply installing the extension as mentioned in [this article](https://www.gab.lc/articles/manage_ip_postgresql_with_ip4r/) inside the container:

```
$ docker exec -it db /bin/bash
$ apt-get update
$ apt-get install postgresql-13-ip4r
```

But then I get this error if I run the migrations:

```
Error: P3006

Migration `20210427152429_init` failed to apply cleanly to the shadow database.
Error:
ERROR: could not load library "/usr/lib/postgresql/13/lib/plpgsql.so": /usr/lib/postgresql/13/lib/plpgsql.so: undefined symbol: EnsurePortalSnapshotExists
   0: schema_core::state::DevDiagnostic
             at schema-engine/core/src/state.rs:270
```

To not get blocked by this, I will just "downgrade" my local git repository to a commit before https://github.com/stackernews/stacker.news/commit/a5e50821b7e0dba0400a5f8ada6d3741a92de9d3 which is https://github.com/stackernews/stacker.news/commit/6763ef7bf046a7680a9949419a6fbbc02f94a629

**Comment by huumn** [comment]
Sorry about that. There might be a postgres container with the extension already installed.

**Comment by ekzyis** [comment]
> Sorry about that. There might be a postgres container with the extension already installed.

No worries, worst case, I think we can just update our docker-compose file to create such a container.
