### ISSUE TITLE
Onion address

### ISSUE THREAD

**Issue by jsarenik** [stackernews/stacker.news#7]
Some folks may feel better if stacker.news are available via onion (Tor) network. It can also help in your search for decentralization as Tor now has [Onionbalance](https://onionbalance-v3.readthedocs.io/en/latest/v3/tutorial-v3.html) to distribute the service on multiple hosts while serving it over one onion link.

**Comment by jsarenik** [comment]
See https://community.torproject.org/onion-services/advanced/ for more info from the upstream.

**Comment by huumn** [comment]
Thanks! Yes I want to do this. I was curious about load balancing too.

**Comment by jsarenik** [comment]
@huumn I am happy to run one onion (which would proxy to stacker.news or later when it is easy to set up run my own instance) and you can add me to Onionbalance…

**Comment by huumn** [comment]
Cool, I'll let you know!

**Comment by OliverOffing** [comment]
Here's a 15-minute setup using a very small docker container as a reverse proxy: https://github.com/harshit-budhraja/tor-nginx-proxy/

**Comment by huumn** [comment]
Thanks oliver!
