### ISSUE TITLE
Unable to login locally

### ISSUE THREAD

**Issue by AustinKelsay** [stackernews/stacker.news#70]
Despite editing .env.sample with both my Github and LND (using Polar) credentials it's still crashing every time I try to login locally and throwing this error: 
"Unhandled Runtime Error
Error: Invalid URL: <YOUR PUBLIC TUNNEL TO LOCALHOST, e.g. NGROK>"

<img width="1552" alt="image" src="https://user-images.githubusercontent.com/53542748/147586500-e9e728f3-de3c-41ed-a644-be3739838258.png">

**Comment by huumn** [comment]
Which login method are you attempting to use?

**Comment by AustinKelsay** [comment]
I've tried GitHub and LND using Polar

**Comment by huumn** [comment]
Your error suggests it's attempting to use the variable LNAUTH_URL which should only happen if you're logging in via lightning. But maybe it's attempting to read it even when logging in by other means. Please try setting LNAUTH_URL in the .sample.env file to something like `localhost` and see if you can get further.

**Comment by huumn** [comment]
Also, you might need to restart your docker container after you edit the env file.

**Comment by AustinKelsay** [comment]
Great thanks this fixed it! I just went into my docker container for Polar and grabbed the url for the LND node I had setup in my local cluster and put it as the value for LNAUTH_URL in .env.sample

**Comment by AustinKelsay** [comment]
Hey sorry to open this up again but I'm still having issues logging in with lightning or any other method locally

Adding https://localhost:3000 to lnurl-auth in .env.sample gets my QR code to popup on the login page but it won't work with any of my wallets (despite me being able to login fine on the hosted site)

**Comment by huumn** [comment]
```env
# lnurl-auth
LNAUTH_URL=<YOUR PUBLIC TUNNEL TO LOCALHOST, e.g. NGROK>
```

To login with lnauth locally you need a publicly accessible URL for your wallet to talk to. To make this work locally, you'll need to create an http tunnel from a public endpoint and update your env file with that endpoint. I used https://ngrok.com/ for this.
