### ISSUE TITLE
Show correct error message if funding own account

### ISSUE THREAD

**Issue by ekzyis** [stackernews/stacker.news#700]
> Maybe a longer term solution is to show the original message if the user is funding their own SN wallet. Not sure how difficult that is to do but it would be helpful. Maybe even just posting a help message on the wallet funding page stating the limit. That way it is more obvious to a user trying to fund their wallet.

_Originally posted by @kepford in https://github.com/stackernews/stacker.news/issues/693#issuecomment-1859276172_

**Comment by huumn** [comment]
I already implemented this ee68bd294661417c6be99291d54b4568dea81bd9

**Comment by ekzyis** [comment]
Ah, I see
