### ISSUE TITLE
Search appears to be severely limited right now

### ISSUE THREAD

**Issue by SatsAllDay** [stackernews/stacker.news#705]
**Description**
Search on SN does not appear to be working as it should. I searched my own nym with forever time filter `nym:WeAreAllSatoshi` and I only get 1 result.

Perhaps some re-indexing is occurring? Not sure...

**Steps to Reproduce**
Search with a nym filter and see limited to no results.

**Expected behavior**
All items for the filtered nym should appear

**Screenshots**
<img width="1030" alt="image" src="https://github.com/stackernews/stacker.news/assets/128755788/b4cc72ae-fba9-4705-8958-158baf8f647b">

**Logs**
N/A

**Environment:**
N/A

**Additional context**

**Comment by SatsAllDay** [comment]
OMG nevermind, I had a sub selected, and I didn't realize the sub was filtering my results... How embarrassing

**Comment by SatsAllDay** [comment]
Maybe there's an opportunity to improve UX here? If `No More` said like `in this territory`, or `in this time range`, or both?

**Comment by huumn** [comment]
Definitely!
