### ISSUE TITLE
Searching on a territory shows incorrect context help

### ISSUE THREAD

**Issue by SatsAllDay** [stackernews/stacker.news#706]
**Description**
This text:

> you are searching Agora
home searches show results from all

should be updated to something like

> you are searching Agora
Agora searches show results from just the Agora territory

**Steps to Reproduce**
Navigate to a territory, then navigate to the search page.

**Expected behavior**
The contextual help should say that your searching will be limited to the current territory

**Screenshots**
<img width="1010" alt="image" src="https://github.com/stackernews/stacker.news/assets/128755788/ee48b6c6-169f-4fe6-9320-16bccc2a94e3">

**Logs**
N/A

**Environment:**
N/A

**Additional context**
N/A

**Comment by ekzyis** [comment]
Or actually, I think this is intended. Since we want to tell the user how they can search everything.

So maybe this:

> you are searching Agora
Agora searches show results from just the Agora territory
home searches show results from all

**Comment by SatsAllDay** [comment]
Yea I might have just been particularly dense the day I opened this issue lol. If others don't have this issue, you can probably ignore it
