### ISSUE TITLE
UI improvements, following Fund or Withdraw action, and specifically following a failed withdraw attempt

### ISSUE THREAD

**Issue by cointastical** [stackernews/stacker.news#72]
Following a Fund or Withdraw, there's a status message displayed, but the UI provides no link and no suggestion that would provide an intuitive path forward from there for the user to proceed.

When the transaction is a success, this might be acceptable.  After successful Funding, for instance, I might then click Post (from the top menu) or something like that which had caused me to add try to add funds.   After a successful Withdrawal, then ... I don't know -- maybe I go to the home page, or who knows.

But after a failed Withdrawal, well I'm probably going to want to try again, making adjustments until the Withdrawal transaction has succeeded or I'm no longer wanting to Withdraw.

So, to summarize the problem: 

If I try to Withdraw but the action fails (e.g., due to no route), the UI currently provides no path to either try again, or to return to the wallet, or whatever.

How to replicate:
- From a LN Wallet, generate an LN invoice where the Withdraw attempt will fail. [Unsure how best to do this, but I was able to get a withdraw attempt to fail by creating an invoice for a node where a fee will be required, but then used 0 sat as the "max fee" on my withdrawal attempt.]
- From Stacker.News Wallet, click Withdraw.
- Paste the LN invoice created from above.  Adjust the "max fee" to 0 sat. Click the Withdraw button.

Expected results:
After clicking Withdraw, a status message shows "sending", then "loading", then "pending",
then a message stating either success or an error.
If an error, perhaps a link to return to my Wallet, or perhaps a link to Wallet History, or perhaps a Try again (i.e., link to the Withdraw page). 

Actual results:
After clicking Withdraw, a status message shows "sending", then "loading", then "pending",
then an error message:
_"no route"_ | _"try increasing max fee"_
There's nothing else, ... no link that would bring me to my Wallet, no link to Wallet History, and nothing like "Try again" (i.e., link to the Withdraw page).

Of course, I as a user that knows the site can navigate to those, or otherwise can figure out the next step(s).  However good UX would probably include an intuitive path forward from here for the user.

**Comment by huumn** [comment]
Good idea. I think the try again message should just link back to the withdrawal page, and the success message should link to the wallet history.

**Comment by huumn** [comment]
I made withdrawal failures link back to the withdrawal form. I think proceeding from success is straightforward. lmk!
