### ISSUE TITLE
Improve the error message when LNURL Pay request fails due to reasons

### ISSUE THREAD

**Issue by cointastical** [stackernews/stacker.news#735]
When trying to withdraw to an invalid Lightning Address, it seems the HTTP responses from some servers are not handled well by SN, when the response is not .json or the response is not one that SN is already expecting.

Examples:

Correct, expected behavior:

Lightning Address for an invalid domain: test@totally123invalid456domain.com  <-- SN flash message: "fetch failed"
https://totally123invalid456domain.com/.well-known/lnurlp/test   

Lightning Address for an lnurl pay server, but for an invalid user: notk00b@stacker.news  <-- SN flash message: "user @notk00b does not exist"
https://stacker.news/.well-known/lnurlp/notk00b   <-- HTTP/1.1 400 Bad Request [w/ application/body response, and message is the value for the "reason" key]

Undesired (?) behavior:

Lightning Address that produces an unexpected JSON response: test123@bitrefill.me    <-- SN flash message: "Error message not found."
https://bitrefill.me/.well-known/lnurlp/test123   <-- HTTP/1.1 400 Bad Request [w/ application/body response, but message is the value for the "**message**" key]

Lightning address that produces an HTML response: test@gmail.com  <-- SN flash message: "Unexpected token < in JSON at position 0"
https://gmail.com/.well-known/lnurlp/test   <-- HTTP/1.1 404 Not Found [w/ text-html response]

**Comment by SatsAllDay** [comment]
> Lightning Address that produces an unexpected JSON response: [test123@bitrefill.me](mailto:test123@bitrefill.me) <-- SN flash message: "Error message not found."
https://bitrefill.me/.well-known/lnurlp/test123 <-- HTTP/1.1 400 Bad Request [w/ application/body response, but message is the value for the "message" key]

[The spec](https://github.com/lnurl/luds/blob/luds/06.md#wallet-to-service-interaction-flow) explicitly says to use `reason` for an error explanation. I'm not sure what the desired behavior is in this case, where the lightning address provider isn't adhering to the spec? SN _could_ try to look at other known keys like `message` in this case, but really that's just perpetuating bad implementations.

> Lightning address that produces an HTML response: [test@gmail.com](mailto:test@gmail.com) <-- SN flash message: "Unexpected token < in JSON at position 0"
https://gmail.com/.well-known/lnurlp/test <-- HTTP/1.1 404 Not Found [w/ text-html response]

Yep in this case, JSON parsing is failing, which could probably be handled more gracefully.

I guess in either of these two cases, the desired behavior could be to indicate that the requested lightning address provider is not working, which could be for any multitude of reasons.

**Comment by huumn** [comment]
> I guess in either of these two cases, the desired behavior could be to indicate that the requested lightning address provider is not working, which could be for any multitude of reasons.

Yep.

**Comment by huumn** [comment]
@cointastical I'm sending your contribution award to cointastical@stacker.news. If you'd like them to go somewhere else in the future lmk.
