### ISSUE TITLE
RSS response header does not have charset in Content-Type 

### ISSUE THREAD

**Issue by cointastical** [stackernews/stacker.news#74]
The response header for Content-Type is currently "text/xml":

```
$ wget -q -S -O - https://Stacker.News/rss 2>&1|grep " Content-Type:"
  Content-Type: text/xml
```

When I [try to validate](https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2FStacker.News%2Frss
) using [W3C Feed Validator](https://validator.w3.org/feed), I see the recommendation:
_"Your feed appears to be encoded as "utf-8", but your server is reporting "US-ASCII"_

In looking at a [recent snapshot of the feed](https://archive.is/iHLYl#selection-997.0-1005.8), I do see Unicode characters, for [SN post #7241](https://stacker.news/items/7241).

This can be [remedied](https://erikrunyon.com/2021/05/rss-and-xsl-content-type-requirement) by adding a "charset= [...]" to the Content-Type field of the response header served by the web server.

Change from: 
`text/xml`
to:
`text/xml; charset=utf-8`

Additionally, I notice in the Response there is no XML declaration.  While this is part of the XML spec, it not existing doesn't seem to be a problem for the RSS validators. It is [recommended, nonetheless](https://en.wikipedia.org/wiki/RSS#Example):

So, in the first line of output (above the "<rss [...]>"), insert the following:
`<?xml version="1.0" encoding="UTF-8" ?>`

If this "charset" Issue is being worked on,  there's [another Feed Validator](https://www.rssboard.org/rss-validator/check.cgi?url=https%3A%2F%2FStacker.News%2Frss) that can be used to confirm the fix resolves the current validation issue.

**Comment by huumn** [comment]
Fixed! Thanks for reporting!
