### ISSUE TITLE
Web Share API runs into 500 Internal Server Error

### ISSUE THREAD

**Issue by ekzyis** [stackernews/stacker.news#741]
> Requirements: SN PWA installed ✅
>
> Steps to reproduce:
> - Open a webpage in your browser
> - Click the Share button
> - Click SN News from suggested apps
> - 💥

https://stacker.news/items/383174

**Comment by riccardobl** [comment]
can't reproduce on android with the following steps :thinking: 
1. open google chrome
2. install sn as pwa with Settings -> Add to home screen
3. open google.com
4. click share
5. select SN from the suggested apps
6. everything works as expected, no 500 error

seems like whatever was causing this was fixed at some point, or maybe there are more steps involved

**Comment by ekzyis** [comment]
Mhh, I think this is an Android-only feature since I can't select SN during sharing on iOS.

So I'll close this as this seems to no longer be an issue. Was also reported by an user [here](https://stacker.news/items/383174?commentId=676307).
