### ISSUE TITLE
Login with Email on PWA

### ISSUE THREAD

**Issue by joshdoman** [stackernews/stacker.news#747]
**Is your feature request related to a problem? Please describe.**
I love the initiative to create a PWA, but I was frustrated with how difficult it was to log in. Logging in with email sends you a link, but that link redirects the user to browser, and not the PWA, making it impossible to log in with email.

**Describe the solution you'd like**
I do not know if it is possible for a link to redirect to a PWA. If so, that would be ideal, but if not, a code could be sent to my email when I try to log in. I could then input this code to access my account.

**Comment by huumn** [comment]
We agree! We have an issue for this already https://github.com/stackernews/stacker.news/issues/727 so I'm going to close this one.

This is only a problem on iOS (android allows us to link to the pwa) but we'd like to solve it. It just requires pretty significant heart surgery of our auth process.

**Comment by joshdoman** [comment]
My bad! I didn't see that.
