### ISSUE TITLE
Enable users to get notified for territory posts

### ISSUE THREAD

**Issue by NEEDcreations** [stackernews/stacker.news#754]
Users should be able to "follow" territories and get notifications when new posts are made in the territories they follow.

**Comment by huumn** [comment]
This is how I thought we'd implement https://github.com/stackernews/stacker.news/issues/681. @ekzyis any particular reason why you did founders-only?

**Comment by ekzyis** [comment]
Not really, was just to keep it simple to ship fast. The only state that was required was a setting per user.

Following territories implies a lot more state; like a table similar to `ThreadSubscription`. But I can update the code, that's not a problem.

But I think the setting still makes sense. I can implement it as an "follow override" or something. So if this setting is enabled, you always follow your own territories. Following them manually using a button would be a noop then.

**Comment by huumn** [comment]
> I can implement it as an "follow override" or something. So if this setting is enabled, you always follow your own territories. (Un)following them manually using a button would be a noop then.

I think it might be better to auto-subscribe a founder to their territory when it's created like we do with `ThreadSubscription`. Then we can remove the setting. 

Settings interactions like you describe are confusing I think. As you describe it, it's straightforward but we can't have this conversation with every stacker.
