### ISSUE TITLE
App container fails to start on Docker compose, diagnosis needed

### ISSUE THREAD

**Issue by 617a7a** [stackernews/stacker.news#757]
On master branch, fe59911. I use an M1 chip. Docker version 24.0.7, build afdd53b.
[app.log](https://github.com/stackernews/stacker.news/files/13961429/app.log)

**Comment by benalleng** [comment]
what is your docker-compose version?

**Comment by benalleng** [comment]
generally something quick to try with `ENOTEMPY` errors is to uninstall the `node-modules/` folder

**Comment by 617a7a** [comment]
> what is your docker-compose version?

I'm using built in compose on docker version specified above. 

> generally something quick to try with `ENOTEMPY` errors is to uninstall the `node-modules/` folder

Will try, I'm not sure that this'll fix because it's a fresh clone.

**Comment by huumn** [comment]
The logs suggest `npm verb argv "install" "--loglevel" "verbose" "--legacy-peer-deps"` is called twice. I'm not sure why that would happen.

Which OS are you running on your M1?

**Comment by 617a7a** [comment]
Version 14.0 (23A344)

**Comment by huumn** [comment]
I'm on Sonoma on an M2. I'll try to run this today and see if I can recreate. 

(I normally develop directly on the host so I haven't done the docker setup in a minute, but @ekzyis develops on it so I assume it's functional but it might not be.)

**Comment by ekzyis** [comment]
> I'm on Sonoma on an M2. I'll try to run this today and see if I can recreate.
> 
> (I normally develop directly on the host so I haven't done the docker setup in a minute, but @ekzyis develops on it so I assume it's functional but it might not be.)

I don't use docker anymore since we updated to node v18.17 ([somewhere around this time](https://github.com/stackernews/stacker.news/pull/277)) but I just tried it out and it still works for me. I only had to add a binary target like this error message suggested:

```
app  | Prisma Client could not locate the Query Engine for runtime "debian-openssl-1.1.x".
app  |
app  | This happened because Prisma Client was generated for "debian-openssl-3.0.x", but the actual deployment required "debian-openssl-1.1.x".
app  | Add "debian-openssl-1.1.x" to `binaryTargets` in the "schema.prisma" file and run `prisma generate` after saving it:
app  |
app  | generator client {
app  |   provider      = "prisma-client-js"
app  |   binaryTargets = ["native", "debian-openssl-1.1.x"]
app  | }
```

run `npx prisma migrate` on the host machine and then my docker setup worked. I am running Arch Linux with kernel 6.6.8-arch1-1 though.

**Comment by 617a7a** [comment]
I managed to solve it by running npm install on the host before building the image. The docker setup could use a rework at some point to make it a little more resilient.
