### ISSUE TITLE
Zaps not registered on first click if modal was closed before

### ISSUE THREAD

**Issue by ekzyis** [stackernews/stacker.news#771]
**Description**

The first short press on a zap icon is not registered if a modal was closed before.

**Steps to Reproduce**

1. Open modal
2. Close modal
3. Click zap icon -> Zap not registered
5. Click zap icon again -> Zap registered

**Expected behavior**

Zaps are always registered

**Video**

https://github.com/stackernews/stacker.news/assets/27162016/31c48306-2052-4a41-abdc-38408fefea96

**Additional context**

I thought it might be related to the document losing focus on modal open and the modal not giving back focus to the document, but `document.activeElement` returned the same before and after a modal was closed.

Also, if you add `onClick` to a parent element (see video), it does get registered. So I think it's something wrong with `LongPressable` and not related to missing focus. Using raw HTML works as expected.

I think this was always the case but it annoyed me enough while working on #749 to create a ticket now for this and I found easy steps to reproduce now.

**Comment by huumn** [comment]
Can confirm this has been a bug since we added `LongPressable`

**Comment by jp30566347** [comment]
This is a hard one. Couldn't find a root cause, but have a workaround.
