### ISSUE TITLE
Search on URL to disregard www. unless search included www. 

### ISSUE THREAD

**Issue by cointastical** [stackernews/stacker.news#776]
Search phrase: CoinDesk.com

Expected results:
All link posts or description posts with CoinDesk.com  (including www.CoinDesk.com results)

Actual results:
Only link posts or description posts with CoinDesk.com   (i.e., does not include www.CoinDesk.com)

I suppose that might make it impossible for me to EXCLUDE posts with www.CoinDesk.com 

So maybe it would understand a wildcard rather than just dismissing the subdomain.
e..g,  URL:*.CoinDesk.com would include www.CoinDesk.com as well as CoinDesk.com results.  Eh, ... but then the "*." means anything followed by a dot.   And  CoinDesk.com would not match as there is no "." before the CoinDesk.com

Anyway, .... just requesting a feature so that Search works better in this instance of wanting a wider net when searching on a domain name only.

**Comment by utanapishtim** [comment]
@huumn I can take a crack at this one. Will this require setting up semantic search vis-a-vis the docs?

**Comment by huumn** [comment]
You should be able to use search locally without semantic search. It falls back to term matches so long as there isn't a model id set in `env`.
