### ISSUE TITLE
I received 50+ emails of the Stacker News Saturday Newsletter 2/3/24

### ISSUE THREAD

**Issue by felipebueno** [stackernews/stacker.news#789]
![image](https://github.com/stackernews/stacker.news/assets/241271/f2bf8d9c-6e1c-4c9d-907a-cc5b7bdc464e)

**Comment by huumn** [comment]
How many accounts do you have on SN? Were each of these sent to a distinct one maybe?

**Comment by felipebueno** [comment]
> How many accounts do you have on SN? Were each of these sent to a distinct one maybe?

oops :sweat_smile: 

Yeah, I might have created 20~30 accounts using e-mail aliases when I was implementing the login feature on the app and a couple others I created for fun.
