### ISSUE TITLE
Add dashboard to satistics

### ISSUE THREAD

**Issue by huumn** [stackernews/stacker.news#794]
Currently, when a stacker visits `satistics` they see a table of all their stacking and spending.

Ideally we'd also give them a graphical view of their personal activity like on our [analytics page](https://stacker.news/stackers/month) (which only applies to everyone).

We have a couple views that periodically refresh and have all the data needed: `user_stats_(day|week|month)` and has these columns:

```
t TIMESTAMP(3), id INTEGER, comments BIGINT, posts BIGINT, territories BIGINT,
    referrals BIGINT, msats_tipped BIGINT, msats_rewards BIGINT, msats_referrals BIGINT,
    msats_revenue BIGINT, msats_stacked BIGINT, msats_fees BIGINT, msats_donated BIGINT,
    msats_billing BIGINT, msats_spent BIGINT
```

**Comment by dillon-co** [comment]
I've been working on this one. forgot to assign myself lol

**Comment by ekzyis** [comment]
@dillon-co you unassigned yourself shortly after your assignment. Was this an accident?

**Comment by huumn** [comment]
No he decided to try something else. This one is tricky to do without a seed. I'm going to work on #391 today.
