### ISSUE TITLE
When editing a comment, cancel automatically occurs (after coming from Profile)

### ISSUE THREAD

**Issue by cointastical** [stackernews/stacker.news#80]
I find that, after clicking the "comments" link in my profile, when I click to edit a comment I recently made, I then can't see the comment I wanted to edit.  The browser position jumps and the field is out of view.   It appears that "cancel" is triggering, without me clicking it.

How to replicate:
- Leave a comment to some post on SN
- Go to user profile, then click comments link.
- From the top-most comment of yours, click the link for "edit"  

Expected behavior:
The comment becomes an input field where the comment can be edited.

Actual behavior:
The browser jumps, there is no field for input where the comment can be edited.   

---
I am able to then scroll (if needed) to find the comment, and then hit edit once again, ... but as described above, behavior when coming from the "comments" link in the profile causes this undesirable behavior.

**Comment by cointastical** [comment]
Can replicate this on both Chrome (v97) and Firefox (v96).

**Comment by huumn** [comment]
You're a great pinhole tester! I fixed this locally and it forced me to really improve the click handling. Will ship with the next release. Thanks!
