### ISSUE TITLE
Comments - Javascript error after clicking More

### ISSUE THREAD

**Issue by cointastical** [stackernews/stacker.news#82]
When I visit a Profile to view Comments, 
e.g., https://stacker.news/k00b/comments

and then click More, the skeleton for the additional comments is rendered, but there's no content. 
In the Javascript console, it appears that the HTTP POST is getting an HTTP 400 (Bad Request):  

    POST https://stacker.news/api/graphql 400 (Bad Request)

**Comment by cointastical** [comment]
Looks like clicking More on Posts has an issue as well, but slightly different behavior.
e.g., https://stacker.news/k00b/posts 

After clicking More, the skeleton for the additional comments is rendered but for a few milliseconds, then disappears.   I did not observe any Javascript error in the console.  

Clicking More the second time properly populates the additional content as expected.

**Comment by huumn** [comment]
Shipped a fix. Thanks for reporting!
