### ISSUE TITLE
unsafe-eval used for NWC in Arc browser

### ISSUE THREAD

**Issue by ekzyis** [stackernews/stacker.news#821]
> Uncaught (in promise) EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self' 'wasm-unsafe-eval' 'inline-speculation-rules'".
at bakeCollection (content.7f229555.js:2064:98610)
at Object.u (content.7f229555.js:2064:93234)
at Object.g [as call] (content.7f229555.js:2064:93437)
at es.o [as emit] (content.7f229555.js:2064:85238)
at es.stop (content.7f229555.js:17:30157)
at es.eoseReceived (content.7f229555.js:17:31755)
at content.7f229555.js:17:8787
at Array.forEach (<anonymous>)
at T.eoseReceived (content.7f229555.js:17:8754)
at content.7f229555.js:17:11970

-- https://stacker.news/items/424182

**Comment by ekzyis** [comment]
This confuses me since this is not part of our CSP:

> "script-src 'self' 'wasm-unsafe-eval' 'inline-speculation-rules'"

**Comment by ekzyis** [comment]
We could add unsafe-eval to fix this. However, this will affect every browser since unsafe-eval is independent of nonces. At least here, only unsafe-inline is mentioned as ignored when nonces are present :

> Note: In the presence of a CSP nonce the unsafe-inline directive will be ignored by modern browsers. Older browsers, which don't support nonces, will see unsafe-inline and allow inline scripts to execute.

-- https://csp.withgoogle.com/docs/strict-csp.html#example

Also makes sense: nonces and unsafe-inline are about allowing inline scripts but don't care about the content of the script. unsafe-eval is about what content/syntax is allowed.[^1]

So I would really like to not add unsafe-eval if possible without breaking some browsers since it seems to work like a downgrade attack for browsers that support WASM (assuming that's really the cause of the problem).

Need to understand the problem more before I can come up with a good solution.

Question I have:

- Why was @TonyGiorgio [able to use Arc browser](https://stacker.news/items/424191) but not the other user?
- [Arc](https://arc.net/) is macOS only? No Linux version available?
- Is it really because of missing WASM support? The error message says that the browser allows unsafe-eval-wasm but Javascript's `eval` was blocked.
- Where does this CSP that was quoted in the error message come from?

[I looked a bit into the documentation of `nostr-tools`](https://github.com/nbd-wtf/nostr-tools?tab=readme-ov-file#using-it-with-nostr-wasm) (the library we're using for connecting to relays for NWC) and as I read it, it would only use WASM if explicitly told so with `nostr-wasm`:

```js
import { setNostrWasm, generateSecretKey, finalizeEvent, verifyEvent } from 'nostr-tools/wasm'
import { initNostrWasm } from 'nostr-wasm'

// make sure this promise resolves before your app starts calling finalizeEvent or verifyEvent
initNostrWasm().then(setNostrWasm)
```

[^1]: At least that's my attempt of making sense of this behaviour.

**Comment by huumn** [comment]
To be clear, I was just guessing about wasm. I saw that nostr-tools had wasm in it and assumed that might be the difference in these cases but it might be something else.

**Comment by ekzyis** [comment]
Another user report about wasm:

> Uncaught (in promise) CompileError: WebAssembly.compile():
at o.fromBase64 (content-script.js:2:2534119)
at content-script.js:2:2534319
at I.a (content-script.js:2:2857805)
at 39718 (content-script.js:2:2533793)
at I (content-script.js:2:2857284)
at content-script.js:2:2836069
at I.a (content-script.js:2:2857805)
at 4690 (content-script.js:2:2835546)
at I (content-script.js:2:2857284)
at content-script.js:2:2505330

-- https://stacker.news/items/425584

Will take a deeper look into the source code of `nostr-tools`. Maybe this will get fixed by only using browser native APIs like `window.WebSocket` and writing our own NIP-04 encryption.

**Comment by ekzyis** [comment]
Mhh, I don't think the right call is to not use nostr-tools.

The stuff we use for NWC[^1] ([`finalizeEvent`](https://github.com/nbd-wtf/nostr-tools/blob/37b046c047573d12a0d44c7719167c5ca4f048ea/pure.ts#L15-L22), [`Relay`](https://github.com/nbd-wtf/nostr-tools/blob/master/abstract-relay.ts), [`nip04.encrypt`](https://github.com/nbd-wtf/nostr-tools/blob/master/nip04.ts), [`nip04.decrypt`](https://github.com/nbd-wtf/nostr-tools/blob/master/nip04.ts)) are mainly based on [@noble/curves](https://github.com/paulmillr/noble-curves) and [@noble/hashes](https://github.com/paulmillr/noble-hashes) and that's all written in JS afaict (and we certainly don't want to not use the crypto in nobles).

**_However_**, there is a [wasm version for `finalizeEvent`](https://github.com/nbd-wtf/nostr-tools/blob/master/wasm.ts). So maybe some browsers use this instead of the JS version for some reason and then choke on it? That sounds pretty dumb but that's the best explanation I have so far.
Additionally, interestingly, Primal does use a lot from `nostr-tools` but not `finalizeEvent`. [It has a own implementation to sign events](https://github.com/PrimalHQ/primal-web-app/blob/0d85008bcbe7804ed4f5e33cf2f82dbb58a6b161/src/lib/PrimalNostr.ts#L126-L146) which looks very similar to `finalizeEvent`. Maybe just a coincidence and they don't use it for other reasons.

I tried to reproduce this by disabling wasm in Firefox in `about:config` and then made sure it's disabled by trying to access `WebAssembly` in the global scope:

> Uncaught ReferenceError: WebAssembly is not defined

But attaching a NWC wallet still worked fine for me.

The user with the wasm error above [reported that they tried Firefox, Brave and Chrome but all didn't work](https://stacker.news/items/425579):

> I've tried with Brave, Firefox and Chrome but I still get the same red light.

The error message includes `CompileError` which [suggests that their browser doesn't support wasm](https://github.com/WebAssembly/content-security-policy/blob/main/proposals/CSP.md):

> **The `HostEnsureCanCompileWasmBytes` Policy Point**
> 
> It is proposed that the above APIs are gated by a policy point: `HostEnsureCanCompileWasmBytes`. (This is sometimes referred to as an abstract operation that must be performed by the host to permit the compilation.)
>
>**`HostEnsureCanCompileWasmBytes`**
> 
> If `HostEnsureCanCompileWasmBytes` is not enabled, then the `WebAssembly.compile` and `WebAssembly.compileStreaming` functions fail with a `WebAssembly.CompileError` exception. Otherwise, these API functions return results depending on the internal integrity of the WebAssembly module being compiled.

So maybe `wasm-unsafe-eval` would fix this but it bothers me that I can't reproduce the error and don't understand where it comes from.

I would rather know exactly where we use wasm than to just use `wasm-unsafe-eval`.

But would be a good data point to know if using `wasm-unsafe-eval` would fix this for the stackers that reported errors with NWC.

[^1]: where we can't and don't want to use signer extensions

**Comment by ekzyis** [comment]
Might be unrelated to our CSP and these console errors are just weird CSP reports triggered by extensions or something.

For example, one stacker reported that it works with (test) Mutiny wallet but not with NWC 0.4.2 on umbrelOS 0.5.4 [here](https://stacker.news/items/428245).
