### ISSUE TITLE
Some routes aren't resolving as expected with CSP

### ISSUE THREAD

**Issue by huumn** [stackernews/stacker.news#822]
Navigating to `top` throws this error

```
router.js:758 Uncaught (in promise) Error: The provided `as` value (/top/posts/day) is incompatible with the `href` value (/~/top/[type]/[when]). Read more: https://nextjs.org/docs/messages/incompatible-href-as
    at Router.<anonymous> (router.js:758:27)
    at tryCatch (runtime.js:45:16)
    at f._invoke (runtime.js:274:1)
    at r.<computed> [as next] (runtime.js:97:1)
    at asyncGeneratorStep (asyncToGenerator.js:3:1)
    at _next (asyncToGenerator.js:25:1)
```

Nothing has changed in top since the last release so there's likely something in our CSP that throws off the router.

**Comment by ekzyis** [comment]
And only sometimes

**Comment by huumn** [comment]
Afaict the router is all the time, but for some reason it loads the data with the right params occasionally.

**Comment by ekzyis** [comment]
I tried out [this plugin](https://chromewebstore.google.com/detail/disable-content-security/ieelmcmcagommplceebfedjlakkhpden) that should disable CSP and the error still happens:

https://github.com/stackernews/stacker.news/assets/27162016/8b2bc044-83a2-4f24-aa63-262a48d041d2

So either this plugin doesn't work or this isn't related to CSP :thinking:

**Comment by huumn** [comment]
Nothing changed in related parts of the code base though. So weird.

**Comment by huumn** [comment]
I also can't recreate locally.

**Comment by huumn** [comment]
Based on the stacktrace in prod 
![Screenshot 2024-02-13 at 7 07 44 PM](https://github.com/stackernews/stacker.news/assets/34140557/5d6f4272-37fb-4a0c-9f53-1f417bc4299d)

And the source maps, it looks like it's caused by `_app.js:61` which is where I do my `router.replace` hack:
```js
    if (!props?.apollo) return
    // HACK: 'cause there's no way to tell Next to skip SSR
    // So every page load, we modify the route in browser history
    // to point to the same page but without SSR, ie ?nodata=true
    // this nodata var will get passed to the server on back/foward and
    // 1. prevent data from reloading and 2. perserve scroll
    // (2) is not possible while intercepting nav with beforePopState
    router.replace({
      pathname: router.pathname,
      query: { ...router.query, nodata: true }
    }, router.asPath, { ...router.options, shallow: true }).catch((e) => {
      // workaround for https://github.com/vercel/next.js/issues/37362
      if (!e.cancelled) {
        console.log(e)
        throw e
      }
    })
```

So whatever is going on is breaking this.

**Comment by ekzyis** [comment]
You could disable CSP using the nginx patch I sent you to confirm or deny if it's CSP in prod

**Comment by huumn** [comment]
I'm testing a more explicit use of the route with `next/link` which should do the trick if the error message is complaining accurately. Deploying now.

**Comment by ekzyis** [comment]
Just noticed that there is the same error with the link to https://stacker.news/top/stackers/day in the settings:

> Error: The provided `as` value (/top/stackers/day) is incompatible with the `href` value (/~/top/stackers/[when]).

Doesn't happen locally. And if you reload the top page and then go back to settings, `data` and `ssrData` are not defined which results in a crash:

https://github.com/stackernews/stacker.news/assets/27162016/d19ce6a6-b998-493b-85cd-a9cfdf68549a
