### ISSUE TITLE
Broken user settings validation

### ISSUE THREAD

**Issue by alexlwn123** [stackernews/stacker.news#829]
**Description**
Validation fails when `nostrRelays` field is empty.

**Steps to Reproduce**
Save settings with an empty relays field.

**Expected behavior**
nostrRelays is optional, so it should permit being blank.

**Screenshots**
<img width="999" alt="image" src="https://github.com/stackernews/stacker.news/assets/43247027/0dbd6ff5-4de1-4893-b699-3f52b65d18ce">

**Comment by huumn** [comment]
Nice catch!

**Comment by ekzyis** [comment]
Oh lol, just noticed this myself. Fix is here #830
