### ISSUE TITLE
Random sort for items

### ISSUE THREAD

**Issue by huumn** [stackernews/stacker.news#832]
This is @utanapishtim's idea and I think it's a phenomenal idea. We've been discussing adding a "discover" page to surface old, fantastic content, but I never use the "discover" page on any site.

Benefits over discover page:
1. it doesn't need a custom UI and the UX is familiar to existing stackers, ie they would be much more likely to actually use it. 
2. One of the reasons I think discovery pages don't get used is because their UI is bespoke, unfamiliar, and frankly have a "random" UI
3. @ekzyis notes discover pages also "hidden/unclear biases (users pretty much expect some hidden agenda now thanks to web2)"

We probably don't want this to be exactly random. Meaning we don't want it surface sub-standard content, but we do want it surface content above a certain threshold of quality without regard for time.

**Comment by tsmith123** [comment]
I might take a look at this if I can find the time but I'm a bit confused from the description? Are you asking for a discover page or not? 😆 

Or are you thinking more on the lines of this:

![image](https://github.com/user-attachments/assets/dce59a50-3b9b-4282-87bf-c2cda7e4f6a1)

where a "discover" link (or whatever) could be used to resurface old good quality content?

**Comment by tsmith123** [comment]
Sorry, just seen blocked label - what's the main blocker?

**Comment by huumn** [comment]
I removed blocked! 

> Are you asking for a discover page or not?

I'm proposing this instead of a discover page. It'd just be another sort, like in your screenshot, but rather than `discover` I'd prefer it be called `random`.

**Comment by tsmith123** [comment]
Cheers. Will have a play hopefully soon.

**Comment by tsmith123** [comment]
Has anything changed that might be causing my computer to run StackerNews really slowly now. I never use to have any issues but now I'm seeing CPU on docker running at 200%, 300% and more !!!

**Comment by huumn** [comment]
We did assign CPU shares to resources but that should have the opposite effect. Can you confirm your `COMPOSE_PROFILES` is getting picked up and other services aren't running?

**Comment by tsmith123** [comment]
Yeah just db, app and worker though I usually stop worker as I don't really know what it does and it doesn't seem to make a difference when I stop it.

**Comment by tsmith123** [comment]
Seems a bit happier at the moment - I'll keep an eye on it

**Comment by tsmith123** [comment]
So not that comfortable with the queries area of the app as they seem super complex but wanted to ask which fields we can/want to use to ascertain whether posts are "good quality"?

**Comment by huumn** [comment]
It is horribly complex unfortunately. Basically what you want to do is something like the [top query](https://github.com/stackernews/stacker.news/blob/ec2383b99889f47f651860f9e41f38fbcd1940a2/api/resolvers/item.js#L380) but

1. without a time filter
2. sorted randomly

**Comment by tsmith123** [comment]
Ok, so what does `weightedVotes` need to be above then? I don't know what weighted votes means or the scale that it uses.

**Comment by huumn** [comment]
Oh right, ummm, if you make it a named constant, develop it with an arbitrary value and I can modify it to work best in prod. I'm not sure what the value should be though without testing it myself.

**Comment by tsmith123** [comment]
So here's a draft but I'm afraid it's more questions than solutions. It's a world of pain this query stuff 😆 

https://github.com/stackernews/stacker.news/pull/1306

**Comment by tsmith123** [comment]
Btw, not much more I can do with this without some guidance. Cheers.

**Comment by tsmith123** [comment]
Hey @huumn So I've added random() and now it works. I think you mentioned somewhere that you would have a play with it to see what the right setting would be for weightedVotes. Did you still want to do that? Happy to make the changes if you let me know. Otherwise, as things stand, it seems to be selecting posts at random that have a number of votes from any time so I think it's close.

**Comment by huumn** [comment]
Cool! I'll try to review it soon. If all that's left is figuring out the right threshold, I can make any necessary changes.

**Comment by huumn** [comment]
@utanapishtim do you have a lightning address so I can send you sats for this?
