### ISSUE TITLE
Attempt to fund shows "undefined: eR is undefined"

### ISSUE THREAD

**Issue by cointastical** [stackernews/stacker.news#836]
![Screenshot 2024-02-15 080936](https://github.com/stackernews/stacker.news/assets/60823751/3b5b558d-e68f-45d7-8d2e-31011faf13ef)

**Comment by ekzyis** [comment]
Thanks for the report!

This might be fixed by https://github.com/stackernews/stacker.news/pull/834 but I have not seen this error message before.

Might also be related to wasm as mentioned in #821

**Comment by ekzyis** [comment]
We rolled out a potential fix. I created an invoice with a wallet attached and no wallet attached. Was not able to reproduce the error. Can you test on your end?

**Comment by ekzyis** [comment]
Was able to reproduce on the master commit before that (8727f95f). So confirmed that afe096e fixed this.
