### ISSUE TITLE
Related section not collapsed after first reply

### ISSUE THREAD

**Issue by ekzyis** [stackernews/stacker.news#837]
https://stacker.news/items/426061

We want to keep this functionality but it should collapse related posts on the first comment submission.

**Comment by abhiShandy** [comment]
This issue was fixed by https://github.com/stackernews/stacker.news/commit/dc8d35fdcfdaa55b7ba30035fee5bd3a8cd00b9c

**Comment by ekzyis** [comment]
https://github.com/stackernews/stacker.news/commit/dc8d35fdcfdaa55b7ba30035fee5bd3a8cd00b9c is related but this change only collapses the related section when you load the page again. This ticket is about updating the cache so you don't have to reload the page after you replied. See this video:

https://github.com/stackernews/stacker.news/assets/27162016/125101ef-f28c-4cac-b678-24b9ba1b442d

**Comment by tsmith123** [comment]
Turned out that the issue wasn't really to do with Apollo cache but the Accordion component instead. Tricky one to find but added a PR here #1207

**Comment by ekzyis** [comment]
Oh, I thought it might be controlled via the Apollo cache but I didn't look at the code. Sorry for the false pointer
