### ISSUE TITLE
Funding calls sendPayment even if wallets aren't attached

### ISSUE THREAD

**Issue by huumn** [stackernews/stacker.news#838]
Recreation: don't attach wallets, then attempt to fund wallet

![Screenshot 2024-02-15 at 11 13 29 AM](https://github.com/stackernews/stacker.news/assets/34140557/66dcfde8-ee6a-4caa-810b-536846e6ca7b)

**Comment by ekzyis** [comment]
Oh, this should also be fixed by #834. Can you check if you didn't already? Currently not at home

**Comment by huumn** [comment]
Yeah seems to be fixed.
