### ISSUE TITLE
Link for Profile matches current URL, not Profile 

### ISSUE THREAD

**Issue by cointastical** [stackernews/stacker.news#84]
Though clicking on the link for my nym causes a drop down as expected, if I right-click on that link and Open in a new tab, the URL for that nym will match the current page, and not my profile.

To reproduce issue:
- Log into Stacker.News
- Navigate to something like: https://stacker.news/recent
- Hover over the link for the nym

Expected result:
The URL showing for that num to be the Profile, same as if I had clicked on the link and gotten the drop-down
i.e., Stacker.News/[nym]

Observed result:
The URL matching the current page
i.e., https://stacker.news/recent, if that was the current page

**Comment by huumn** [comment]
Yeah, the nym just triggers the dropdown and isn't a link currently. I guess can make it one though and just prevent the link from opening when the user wants the dropdown.

**Comment by huumn** [comment]
Done locally.

**Comment by huumn** [comment]
Going to reintroduce this because my fix nested an anchor tag in an anchor tag and caused react to error.
