### ISSUE TITLE
External pending payment UX

### ISSUE THREAD

**Issue by huumn** [stackernews/stacker.news#849]
**tldr Toasts are perfectly okay for now - and maybe the best thing to do while we're experimenting - but we'll want something better once we nail the UX otherwise**

Some good discussion here: https://stacker.news/items/423928/r/k00b?commentId=428876

In addition to #848, we'll want something more refined than toasts as time goes on to facilitate cancels/retries. Basically these actions will be fundamental parts of the non-custodial UX so we shouldn't offload them to generic toast messages in the longrun.

**Comment by ekzyis** [comment]
I think we can close this
