### ISSUE TITLE
Allow purchase of archived territories by arbitrary stackers

### ISSUE THREAD

**Issue by huumn** [stackernews/stacker.news#863]
MVP: When you create a territory that shares the name of an archived territory, allow them to proceed, but warn them they'll be inheriting the old territory's posts/comments

beyond MVP: 

1. when viewing an archived territory, show an option to "rehydrate it"
2. give them the option to not inherit old posts/comments somehow

**Comment by ekzyis** [comment]
> give them the option to not inherit old posts/comments somehow

would be cool if links to old content still work even if not inherited

**Comment by huumn** [comment]
Absolutely. My hope was the old territories would be moved when they get archived.

My ideal with this is to have a territory called ~graveyard or something and archived territories are sub-territories, e.g `~graveyard/econ`
