### ISSUE TITLE
Login with Nostr NIP-46

### ISSUE THREAD

**Issue by nostrband** [stackernews/stacker.news#864]
**Is your feature request related to a problem? Please describe.**
I don't like using an extension to store Nostr keys, and extension doesn't work on mobile. 

**Describe the solution you'd like**
Adding support for Nostr NIP-46 (remote key access protocol) could solve the problem.

**Describe alternatives you've considered**
Implementing the NIP46 protocol could be an option. Simpler solution is to use a nostr library - nostr-tools and ndk both have nip46 support. Even simpler one is to use a nip-46 client implementation - nostr-login and window.nostr.js both provide a proxy object that converts nip07 extension calls to nip46 calls.

**Comment by lungfulmeme** [comment]
implementation of nsec.app is really sleek and simple. would enjoy using this for SN

**Comment by ekzyis** [comment]
This look like what I always wanted for nostr login. Thanks for the ticket!

**Comment by brugeman** [comment]
> This might also solve #727 for nostr auth in a PWA:

It should, I use a nostr pwa app with nip46 pretty nicely.

**Comment by riccardobl** [comment]
Hey, is anyone working on this? If not, i can do it :+1:

**Comment by huumn** [comment]
Nope, I'll assign you!
