### ISSUE TITLE
Link validation when submitting from /post

### ISSUE THREAD

**Issue by cointastical** [stackernews/stacker.news#88]
I typo'd when creating a post.

I meant to paste the link for a website (e.g., ```https://Stacker.News```), but had prefixed the URL with an extraneous character  "T".

The URL I actually posted was something like:
```Thttps://Stacker.News```

But SN simply prefixed "https://" to it.  So the URL for the post ended up being something like:
```https://Thttps://Stacker.News```

I noticed it right away, so was able to edit the URL for the post, and there was no issue, but SN probably should do validation on the URL from the submit before accepting it.

**Comment by huumn** [comment]
We have an issue for this already: https://github.com/stackernews/stacker.news/issues/14. Going to close this one but thanks for resurfacing it!
