### ISSUE TITLE
Enable readerView compatibility

### ISSUE THREAD

**Issue by h0dlr** [stackernews/stacker.news#884]
**Is your feature request related to a problem? Please describe.**
Yes, in the majority of browsers I've tested, accessing the contents on readingView is not compatible with the HTML structure generated by Stacker.News

**Describe the solution you'd like**
I believe it's just question to use the appropriated HTML tags to format the article: ie. `<article>`

**Describe alternatives you've considered**
The alternative is to install an extension provide data to third parties about the contents I'm reading!

**Additional context**
N/A

**Comment by huumn** [comment]
H0dlr do you have a lightning address I can send the sats for this issue to?

**Comment by h0dlr** [comment]
I'm glad you implemented this feature, thank you very much! you can send to `0xe14b9b5981c729a3@ln.tips`

**Comment by h0dlr** [comment]
I also found the HTML structure isn't still right on Chrome and Safari and the _Reader View_ still unavailable

This has helped me better understand https://stackoverflow.com/questions/30730300/optimize-website-to-show-reader-view-in-firefox

Just submitted https://github.com/stackernews/stacker.news/pull/1005 to add a `<p>` and including the title inside the `<article>`

Have been not able to test

**Comment by felipebueno** [comment]
Hmm I can´t reproduce the bug. What device are you using on your tests?

**Comment by h0dlr** [comment]
Mac OS
