### ISSUE TITLE
Additional post types

### ISSUE THREAD

**Issue by huumn** [stackernews/stacker.news#9]
Currently we only have links and discussions but we can support more types to give users more options.

- [x] images
- [ ] videos
- [x] q&a bounties (tbd the rules)
- [x] polls (one sat per vote)

**Comment by huumn** [comment]
Jimmy asked for polls here: https://stacker.news/items/10515

**Comment by jimmysong** [comment]
Specifically, 1000 sats staked per vote. The sats get returned to you after the vote closes. 1 vote per person and you can get good data about stuff.

**Comment by cointastical** [comment]
- Embed for when Link is a Twitter URL with a Link Post on SN, completed. Issue #63
- Embed for when Link is a Youtube URL with a Link Post on SN, completed, Issue #97.
- Handling for when Link is an Image URL with a Link Post on SN, not completed.  Discussed in [SN Comment Item #10558](https://stacker.news/items/10558)

**Comment by cointastical** [comment]
>  images/videos

Is that request referring to a a Link post where the link is an image (e.g., .png) or a video (e.g., mp4)?   Or is it looking to add a type of "media" post where I upload the media (e.g., a .png or .mp4)?

**Comment by huumn** [comment]
Perhaps both

**Comment by cointastical** [comment]
> Jimmy asked for polls here: https://stacker.news/items/10515

Mark that one off the to-do list.

**Comment by cointastical** [comment]
Automatic rendering of links for Images (in a comment reply or description post) is coming, thanks to a bounty shared in Issue #239

**Comment by huumn** [comment]
Each proposed post type should be its own issue.
