### ISSUE TITLE
Save button on edit shows a cost on hover, when the edit is free

### ISSUE THREAD

**Issue by SatsAllDay** [stackernews/stacker.news#908]
**Description**
When editing a comment (or post, presumably - I didn't try it), the "Save" button shows the same cost that you already paid to make the comment when you hover, which suggests it costs more sats to save an edit.

**Steps to Reproduce**
1. Post a comment on anything (post, other comment). Note the comment fee.
2. Click the edit button on the comment created in the previous step
3. Hover over the "Save" button to display the fee tooltip
4. Note that the fee is non-zero.

**Expected behavior**
The tooltip on the "Save" button when editing an item that you've already paid for should not suggest that you would have to pay again when saving the edit.

**Screenshots**
<img width="769" alt="image" src="https://github.com/stackernews/stacker.news/assets/128755788/3c1955b8-1324-475f-a1fd-9fe303a3a565">

**Logs**
N/A

**Environment:**
Seen on Chrome on macOS

**Additional context**
I don't think edits are actually charging sats, I think this is just a minor UI bug.

I think I actually explored this in one of my last PRs that never ended up getting merged. While the code could be of use, I suspect it's in a heavily merge-conflicted state and at this point should probably only be reviewed as a reference and salvage should not be attempted.

**Comment by SaxenaShiv** [comment]
Hi, I am interested to work on this issue. Please assign it to me.

**Comment by ekzyis** [comment]
> Hi, I am interested to work on this issue. Please assign it to me.

Hi and welcome! I assigned you now.
