### ISSUE TITLE
Link Post Click Targets Wonky

### ISSUE THREAD

**Issue by SatsAllDay** [stackernews/stacker.news#923]
**Description**
When viewing any listing of posts, the click target for links on link posts are longer than the actual link text (likely filling parent container width), resulting in cursor pointer on seemingly blank areas of the screen.

**Steps to Reproduce**
1. View any post listing page (home, any territory with link posts allowed)
2. Find a link-post
3. Hover your cursor to the right of the linked URL

**Expected behavior**
Click target should only be on the URL text

**Screenshots**
![image](https://github.com/stackernews/stacker.news/assets/128755788/048b891f-ea4d-4e07-9911-4ee3d5a5d901)

**Logs**
N/A

**Environment:**
Seen on Chrome on macOS.

**Additional context**
N/A

**Comment by huumn** [comment]
The css around this is rather tricky because we want to truncate the link on narrow screens. Still it might be possible to do something with flex to fix this.

**Comment by SatsAllDay** [comment]
> The css around this is rather tricky because we want to truncate the link on narrow screens. Still it might be possible to do something with flex to fix this.

I actually noticed this several months ago. I spent a few minutes trying to mess with the CSS to fix it, gave up, and unfortunately forgot to log the bug, but I came to a similar conclusion.

**Comment by benalleng** [comment]
mind if I take a crack at this one? I think I've dealt with something similar to this recently

**Comment by huumn** [comment]
Go for it!
