### ISSUE TITLE
Enhance dev experience to support (easily) specifying which docker services to run

### ISSUE THREAD

**Issue by SatsAllDay** [stackernews/stacker.news#928]
**Is your feature request related to a problem? Please describe.**
As a contributor to SN with an older development machine, the amount of docker containers that are spun up via `./sndev start` can cause considerable resource consumption on my machine. This makes it hard to effectively develop. There are many services spun up, but many of them are not required to do certain pieces of work, depending on the changes you're looking to make.

**Describe the solution you'd like**
In my perspective, there are a few options:
1. Update `sndev` to provide a way to opt-out of spinning up certain docker services via `./sndev start`. This could be done by adding a new CLI flag like `--exclude <service>` so the user could execute e.g. `./sndev start --exclude opensearch`. It could also be done by supporting some `.gitignore`d configuration file that is consulted when `./sndev start` is executed. 

2. Similar to number 1 above, `sndev` could be reduced to the minimum required services by default (`app`, `db`?), and developers could opt-in to other services, based on what they're trying to do. I'm not sure if this is better than having to opt-out (option 1).

3. As @huumn mentioned in the related comment thread (linked below), there could also be some cleanup performed on the `depends_on` entries in `docker-compose.yml` to reduce which services are automatically spun up, if you were to just spin up the `app` service (as an example) using `./sndev start app`.  I like the idea of a config-driven approach more, I think, but this option certainly provides a workable solution. I guess it comes down to whether you want `depends_on` to reflect a prod-like configuration, or just the bare minimums for a functional development environment.

**Describe alternatives you've considered**
Enumerated above.

**Additional context**
[Context comments where this was discussed](https://stacker.news/items/466556/r/WeAreAllSatoshi?commentId=467727)

**Comment by SatsAllDay** [comment]
Here's a nice hack that works without making any changes to `sndev`.

Say I want to exclude `opensearch` and `os-dashboard` services, I could run:

`./sndev start --scale opensearch=0 --scale os-dashboard=0`

Inspired from [this comment](https://github.com/docker/compose/issues/1294#issuecomment-374847206). This leverages the `--scale` option in [`docker compose up`](https://docs.docker.com/reference/cli/docker/compose/up/)

**Comment by ekzyis** [comment]
Interesting, we could have some presets using this `--scale` option.

I think starting the minimum required services is best. So that is `app`, `db` and `worker`. It's less error prone and developer can gradually learn about other infrastructure we run like `imgproxy`, `s3`, `opensearch`, ... when they need it.

Since `worker` will try to index items which is not possible without `opensearch`, such jobs should fail gracefully with useful error messages.

**Comment by huumn** [comment]
I’m not sure I would say us starting with less services is the best way. It depends on how we implement running more services (or excluding services), whether running more services is easy to communicate, and what the majority of people are goin to find easiest.

I like that you run one command and that’s it. You don’t need to think about how your feature needs s3. But on the other hand this many containers will gobble up ram.

maybe we can inspect ram on device, if it’s low, start in a “minimal” mode. If not, gobble away.

Also, even the worker isn’t needed if we are really talking minimal.

**Comment by huumn** [comment]
We should probably use profiles for this: https://docs.docker.com/compose/profiles/

- app and db don't get profiles because they're mandatory
- other profiles
    - search (adds search stuff)
    - images (adds image stuff)
    - payments (adds payments stuff)
    - all (default)

**Comment by SatsAllDay** [comment]
Profiles sounds like a perfect fit!
