### ISSUE TITLE
/notifications giving either 504 Gateway Time-out or response only after a long delay

### ISSUE THREAD

**Issue by cointastical** [stackernews/stacker.news#932]
Doing this today:
https://stacker.news/notifications

```
Browser shows:
504 Gateway Time-out
nginx/1.22.1
```

or it might display the correct content, but only after a long-ish delay

I'm seeing it with the SN account with the same username as this github account cointastical.

In Firefox, the Javascript console shows:
`ApolloError: Response not successful: Received status code 504`

The JavaScript errors include:
https://stacker.news/_next/data/575a82/notifications.json 

Not sure if it is the cause of this error, but also getting:

```
nomics.com/:1 
GET https://nomics.com/ net::ERR_FAILED
```

Nomics has been dead for nearly a year.  Not sure what it is being called for.

```
The FetchEvent for "https://nomics.com/" resulted in a network error response: the promise was resolved with an error response object.

sw.js:18
```

**Comment by huumn** [comment]
How far are you going back in your notifications when you get this message?

**Comment by cointastical** [comment]
Simply clicking the Notification (bell) icon, not trying to paginate or whatever.

I just tried again, this time with the Javascript Console running already and I see this:


Hydration failed because the initial UI does not match what was rendered on the server.

```
react-dom.production.min.js:131 Uncaught Error: Minified React error #418; visit https://reactjs.org/docs/error-decoder.html?invariant=418 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Eg (react-dom.production.min.js:131:144)
    at x (react-dom.production.min.js:293:349)
    at Vk (react-dom.production.min.js:280:383)
    at react-dom.production.min.js:280:319
    at Jk (react-dom.production.min.js:280:319)
    at Hk (react-dom.production.min.js:268:166)
    at J (scheduler.production.min.js:13:197)
    at MessagePort.R (scheduler.production.min.js:14:126)
```

I also tried just right click on the notification (bell) icon and then "Open link in a new tab", and can see only:

`Failed to load resource: the server responded with a status of 504 ()`

Hitting reload on that page, after a long wait showed:

`The FetchEvent for "https://nomics.com/" resulted in a network error response: the promise was resolved with an error response object.`

In another tab ... I get (which I saved the log)

```
GET https://nomics.com/ net::ERR_FAILED
Image (async)
(anonymous) @ image.js:31
Rj @ react-dom.production.min.js:244
Ik @ react-dom.production.min.js:286
Fk @ react-dom.production.min.js:273
jg @ react-dom.production.min.js:127
(anonymous) @ react-dom.production.min.js:283
Qk @ react-dom.production.min.js:283
Hk @ react-dom.production.min.js:269
J @ scheduler.production.min.js:13
R @ scheduler.production.min.js:14
Show 9 more frames
Show less
```

🤷‍♂️
