### ISSUE TITLE
Sign Up / Login via e-mail not working

### ISSUE THREAD

**Issue by felipebueno** [stackernews/stacker.news#939]
**Description**
Sign Up / Login via e-mail fails with generic error message

**Steps to Reproduce**
Insert *valid* e-mail on the e-mail field and click the **Sign Up With E-mail** or the **Login With E-mail** buttons

**Expected behavior**
Receive the magic link so I can log in

**Screenshots**
![image](https://github.com/stackernews/stacker.news/assets/241271/c7c66de4-d42c-45c4-a225-f218524d2814)

**Logs**
No relevant logs on the console

**Environment:**
 - OS: Ubuntu 22.04
 - Browser Firefox & Google Chrome

**Comment by huumn** [comment]
This was an issue with our email provider. Certs were rotated today and they messed up or somethin. It's been resolved.
