### ISSUE TITLE
Block duplicate post from same user same post

### ISSUE THREAD

**Issue by cointastical** [stackernews/stacker.news#94]
Reported here:
https://stacker.news/items/9447

This might have been from a double-click.
So maybe this issue is for a report of that causing a duplicate as well -- at least look into that.

As a user, I've seen this unintended duplication of posts submitted on reddit as well.  Maybe it occurs with a network connectivity issue or something, where the user doesn't get see a visual clue that the first submit was successful, so presses Post button again.  The site should probably catch that -- since that's (probably ?) easy to catch, and obviously not ever something intended.

**Comment by cointastical** [comment]
Note ... this is different from issue #31, as the dup in this instance is not intentional.

**Comment by huumn** [comment]
Fixed locally. I'll ship today.

**Comment by huumn** [comment]
Re-opening because the issue persists ... we suspect the browser retries while another post is in transit.

**Comment by huumn** [comment]
We no longer do any retries on failures/delays so I think this is resolved.
