### ISSUE TITLE
Subscription management UI

### ISSUE THREAD

**Issue by SatsAllDay** [stackernews/stacker.news#944]
**Is your feature request related to a problem? Please describe.**
There is no current way to see all the stackers to whom you've subscribed (posts and/or comments). In order to remove a subscription from a stacker, you have to nav to their profile and use the overflow menu to unsub.

**Describe the solution you'd like**
I'd like a page or a tab where you can see all the stackers to whom you've subscribed in one place. I'd also like to be able to remove the subscription from this UI so it's very easy to manage your subscriptions in one central place.

The UI could differentiate between post and comment subscriptions, or it could all be in one list, I don't think this makes a big difference.

One option is just on your own profile page, subscribed stackers could be a new dropdown selection, and the UI could render all of your subscribed stackers. This list should only work for yourself, i.e. you should not be able to see to whom other stackers have subscribed.

Another option is somewhere on your settings page, though there's probably more UI work needed to fit this in. The same usability concerns from above apply here, too.

**Describe alternatives you've considered**
None.

**Additional context**
Very similar to #943

**Comment by SatsAllDay** [comment]
This is an issue I'd like to work on (when I can). The only aspect I am struggling with is _where_ to put this UI. Does anyone have any input or thoughts on where it ought to live? I considered adding horizontal tabs to the Settings page, where the first tab contains all the current settings, and a new tab houses this subscription listing. A third tab could container the list of mutes from #943 , too. Thoughts on that?

**Comment by huumn** [comment]
Horizontal tabs work best for now. 

I want to overhaul settings to be vertically tabbed eventually but I think that's a separate issue.

![Screenshot 2024-03-27 at 10 36 08 AM](https://github.com/stackernews/stacker.news/assets/34140557/49263856-3b1c-4263-af28-e3637cd8b94a)
