### ISSUE TITLE
Duplicate prevention, check both regular URL and shortened version

### ISSUE THREAD

**Issue by cointastical** [stackernews/stacker.news#95]
For Youtube links, the duplicate protection doesn't know to also check the "other" form of the URL.

> To use youtu.be manually, simply take a URL like http://www.youtube.com/watch?v=FdeioVndUhs and replace the "http://www.youtube.com/watch?v=" with "http://youtu.be/" to get: http://youtu.be/FdeioVndUhs 

*Make Way for youtu.be Links*
https://blog.youtube/news-and-events/make-way-for-youtube-links/

This happened again today, a dup was (mis-)reported here:
https://stacker.news/items/9528

So the dup detection code should, for Youtube links, try both.  i.e., if youtu.be/{}, then also check for a youtube.com/watch?v={}   and if youtube.com/watch= also check for a youtu.be/{}

**Comment by huumn** [comment]
Some one reported this on the board `@camari` I think, but thanks for creating the issue!

**Comment by huumn** [comment]
Done locally.

**Comment by cointastical** [comment]
Appears there's an issue yet.

The duplicates detection does not see this shortened URL as a duplicate:

https://youtu.be/4w8qXX0u-y0

That URL gets an HTTP 303 which redirects to:

https://www.youtube.com/watch?v=4w8qXX0u-y0&feature=youtu.be

Now if I try to post that URL, SN will show two posts that already are duplicates:

https://www.youtube.com/watch?v=4w8qXX0u-y0 (https://stacker.news/items/24997)
and
https://youtu.be/4w8qXX0u-y0 (https://stacker.news/items/25336)

So the issue is: there is logic occurring for dup detection that occurs after posting a URL, and that same logic isn't alco occurring after a shortened URL (youtu.be) is decoded / expanded.

If no fix is at-the-ready, can this issue be re-opened? Or should I create a new, separate issue for this?
