### ISSUE TITLE
Stacker news tries to install itself as a PWA - any way to opt out?

### ISSUE THREAD

**Issue by Kodylow** [stackernews/stacker.news#953]
Not sure how new this is but stacker news tries to install itself as a PWA when you navigate to it in Fedi's browser, could we disable this? It's already a mod within Fedi so this installation screen is unnecessary. We route to mods with a URL link so could we add a query param to the url like ?promptDownloadPwa=false to stop it?

![image](https://github.com/stackernews/stacker.news/assets/74332828/e95b728f-65fd-4049-bac8-c4ab1c47c372)

**Comment by ekzyis** [comment]
> Fedi (the company) has "mods" in the app where you can go to a website with webln, web.nostr, and some other bitcoin tools injected. Just use Fedi and connect to any federation, then in settings add a mod for stacker.news or some federations have it set as default.

Ahh, ok!

> Can I set that timesToShow as a query parameter? the only control I have is the initial URL I set for the federation meta

No, not yet, that needs to be added as code.

**Comment by huumn** [comment]
Deploying this now. 

@Kodylow you'll want to use `?disablePrompt=true`
