### ISSUE TITLE
Confirmation on manually entered boost / tip amounts if amount is possibly excessive

### ISSUE THREAD

**Issue by cointastical** [stackernews/stacker.news#96]
When typing in the number of sats for a boost (or a tip), if I am not paying close attention, I might enter a value larger than I had intended.

For instance, say I was going to enter 100 then figured I'ld change it to 200 but ended up with 2100 and then I hit Post.  Live and learn, I suppose. 

But I could see someone wishing there was either a sanity check, or maybe a setting I can adjust where any tips and boosts above that threshold I specified, and then I would be required to confirm it, or something to that effect.

Not SN's hghest priority, I would presume, but wanted to get an issue created for this.

**Comment by huumn** [comment]
This is a repost of this one https://github.com/stackernews/stacker.news/issues/38 ... Different solution but the same problem.
