### ISSUE TITLE
CORS error for Lightning Addresses

### ISSUE THREAD

**Issue by shocknet-justin** [stackernews/stacker.news#979]
When attempting to resolve a lightning address from a browser context the browser will error with "CORS header 'Access-Control-Allow-Origin' missing" 

In my experience the webserver need this header on lnurl routes to be set to `*` for it to work with web wallets and I think browser extensions

**Comment by huumn** [comment]
Which endpoints don't have the correct `Access-Control-Allow-Origin`

**Comment by shocknet-justin** [comment]
Seems like its been squashed, I can't repro today...

It had been happening on the `/.well-known`, I didn't go further yesterday to see if it was on `/api/lnurlp` also
