### ISSUE TITLE
Trigger a notification when payment arrives via Lightning Address

### ISSUE THREAD

**Issue by cointastical** [stackernews/stacker.news#98]
Otherwise user may not realize that a payment was sent (especially since sender requires no action by the recipient to send a payment).

Discussed in [SN Item #10447](https://stacker.news/items/10589)

Presumably, payments received via an invoice are expected, and thus no notification for that is necessarily expected.

But perhaps if the user receives a notification for payments arriving via Lightning Address payment, they may feel notifications are "not working properly" because some of the payments they receive (i.e., those from sender paying an LN Invoice) are not resulting in a notification. 

So, ... maybe all wallet transaction activity should trigger a notification as well, perhaps?

**Comment by huumn** [comment]
This is a solid issue. I think we should probably have notifications for successful invoices and perhaps even withdrawals.
