### ISSUE TITLE
Hide or remove the back navigation button on Desktop

### ISSUE THREAD

**Issue by felipebueno** [stackernews/stacker.news#987]
Desktop browsers already offer navigation buttons

![image](https://github.com/stackernews/stacker.news/assets/241271/a1e6bfb4-a4d4-4a60-bbed-f2b0ad22b750)

**Comment by huumn** [comment]
Going to close. I want to let it breathe more and use it for a few weeks. 

This is deeper thing than "there's another way to get the same behavior."
