### ISSUE TITLE
"Stacked" Filter Issue on Satistics Page

### ISSUE THREAD

**Issue by SouthKoreaLN** [stackernews/stacker.news#995]
**Description**

Based on the report by SN user Onions [here](https://stacker.news/items/484890).

On the satistics page, deselecting all filters, including the `stacked` filter, results in the display of data for the `stacked` type (see evidence bellow), contrary to the expected behavior of no data presentation.
Notably, accessing the satistics page directly from the link https://stacker.news/satistics?inc= correctly shows an empty result, indicating that the issue is in the behavior of selecting/deselecting the filters.

**Steps to Reproduce**

1. Access the satistics page via the usual method.
2. Deselect all filters, including the `stacked` filter.
3. Observe the display of data for the `stacked` type.

**Expected behavior**

When all filters, including the `stacked` filter, are simultaneously deselected on the satistics page, no data should be displayed.

**Screenshots**

![23787](https://github.com/stackernews/stacker.news/assets/11783268/46a4b7cf-3686-4487-9e41-431d00c9c2fa)

**Impact**
This inconsistency in the display of data based on filter selection may lead to confusion among users and compromise the reliability of the satistics page.

**Comment by SouthKoreaLN** [comment]
FYI. I can reproduce this issue.

**Comment by mateusdeap** [comment]
Me too. Looking at the console in my development environment, I noticed that I get this error:
<img width="1155" alt="image" src="https://github.com/stackernews/stacker.news/assets/14188887/53492365-33dd-4d6d-884d-a67f97b61e3e">

I was unable to confirm wether it was related to this. Also, just looking visually, I have multiple entries for the same stacking event. Ticking the `stacked` box removes only one of them

**Comment by itsrealfake** [comment]
<img width="905" alt="image" src="https://github.com/stackernews/stacker.news/assets/107151866/eaebb630-5e5b-4f95-957d-76f0bfdac387">

React docs say don't generate the `key` while rendering the item.

The key is being generated while rendering here https://github.com/stackernews/stacker.news/blob/54bbb0cc528dfd001e370f94ecf8efcc6ee1a224/pages/satistics/index.js#L260

**Comment by itsrealfake** [comment]
I wonder if this query isn't `DISTINCT` enough & we're getting multiple `"Item".id` listed in the result somehow: https://github.com/stackernews/stacker.news/blob/54bbb0cc528dfd001e370f94ecf8efcc6ee1a224/api/resolvers/wallet.js#L196-L219

**Comment by itsrealfake** [comment]
hmm... maybe we are getting funny data from [this query](https://github.com/stackernews/stacker.news/blob/54bbb0cc528dfd001e370f94ecf8efcc6ee1a224/api/resolvers/wallet.js#L196-L219) and so Apollo isn't able to integrate `data` + `previousData` cache??

here's what i'm seeing:

first, i added a `key String` to the graphQL type & then requested it in query.
then i went to `resolver/wallet.js` and added a `key` to the Facts for testing... 

<img width="862" alt="image" src="https://github.com/stackernews/stacker.news/assets/107151866/861396d2-0758-4115-b3e0-b1d71b7b9ef9">

now, i've i logged to the console from the render function and we can see in `ssrData` that there's a duplicated `id` (in this case it's `459394`) between a `stacked` or `spent` item. interestingly, you can see that their random UUIDs are different 

<img width="928" alt="image" src="https://github.com/stackernews/stacker.news/assets/107151866/eef3ece4-5ac9-4e6f-8f7c-79af77dcb9ad">


<img width="779" alt="image" src="https://github.com/stackernews/stacker.news/assets/107151866/966525af-ad0f-4cdc-bfb5-a9ca384c9123">

**Comment by huumn** [comment]
I suspect this is an issue with apollo client cache, because this doesn't persist on refresh. It could be a `key` issue but I don't recall getting warnings about duplicates.

https://github.com/stackernews/stacker.news/blob/fd2008e5d1a2a8521a330a097b5aaf51bba6ce3d/lib/apollo.js#L207C1-L219C14

> [don't generate the key while rendering the item](https://react.dev/learn/rendering-lists#keeping-list-items-in-order-with-key).

This doesn't mean they that they can't be constructed from deterministic values afaik. It just means for the same item in the list it needs to have the same `key`.

**Comment by itsrealfake** [comment]
> This doesn't mean they that they can't be constructed from deterministic values afaik. 

I think you're right.

So i tried this: 

From a cold boot of the app & hard refresh of the page: `http://localhost:3000/satistics/history?inc=invoice,stacked,spent,withdrawal`

I went to `lib/apollo.js` and added this `console.log` everything else on the branch is same as `master`: 
<img width="558" alt="image" src="https://github.com/stackernews/stacker.news/assets/107151866/b3e8faac-9b40-4a02-9401-6ee42413d08d">

I refreshed the page and was given 5 elements, 2 have matched "key": 
<img width="580" alt="image" src="https://github.com/stackernews/stacker.news/assets/107151866/3087e616-23cb-4af9-b0d2-4ea0c174dc52">

<img width="590" alt="image" src="https://github.com/stackernews/stacker.news/assets/107151866/5ccc57b8-737e-4453-bf2c-7ffdc43fe242">



> I suspect this is an issue with apollo client cache

I think you're right.  Also, I've only been able to get this duplicated key error in the inspector through messing with `'stacked'` and `'spent'` 

I think Apollo uses the `ID!` value to handle caching. And i suspect [the query](https://github.com/stackernews/stacker.news/blob/54bbb0cc528dfd001e370f94ecf8efcc6ee1a224/api/resolvers/wallet.js#L196-L219) is returning duplicates in the id value. Both `'stacked'` and `'spent'` are `JOIN`ing from `"Item"` and `"ItemAct"`

<img width="244" alt="image" src="https://github.com/stackernews/stacker.news/assets/107151866/0dfebf57-fd34-4622-b61c-88afda44e9a4">

**Comment by huumn** [comment]
> I think Apollo uses the ID! value to handle caching. And i suspect [the query](https://github.com/stackernews/stacker.news/blob/54bbb0cc528dfd001e370f94ecf8efcc6ee1a224/api/resolvers/wallet.js#L196-L219) is returning duplicates in the id value. Both 'stacked' and 'spent' are JOINing from "Item" and "ItemAct"

Yep, this is the problem! That id needs to be unique for the apollo cache to work. We should be able to define a custom id function for it. 

I think it's just adding a new type policy:

```
        Fact: {
          keyFields: ['id', 'type'],
        },
```

Untested but I reckon that's what we'd do.

**Comment by itsrealfake** [comment]
That worked!

**Comment by huumn** [comment]
@mateusdeap do you have a lightning address I can send `helpfulness` sats to? If not can you send me a bolt11?

**Comment by mateusdeap** [comment]
I'm a bit new to this, would my lightning address on stacker news suffice?

**Comment by huumn** [comment]
It should
